import type { BubbleCard, CourseContent } from "@/content/schema";

function makeAnalysisCard(
  card: Omit<BubbleCard, "subject" | "course" | "courseCode">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Elementary Analysis I",
    courseCode: "MATH 140A",
    ...card,
  };
}

export const analysisOneCourse: CourseContent = {
  id: "analysis-1",
  subject: "Mathematics",
  title: "Elementary Analysis I",
  institution: "UCI",
  courseCodes: ["MATH 140A"],
  aliases: ["Analysis I", "Real Analysis I"],
  shortDescription:
    "Ross-style elementary analysis for MATH 140A, centered on completeness, sequences, continuity, series, and uniform convergence.",
  units: [
    "Foundations of the Real Numbers",
    "Sequences and Limits",
    "Series",
    "Continuity and Function Limits",
    "Uniform Convergence",
  ],
  chapters: [
    "Chapter 1: Foundations of the Real Numbers",
    "Chapter 2: Sequences and Limits",
    "Chapter 3: Series",
    "Chapter 4: Continuity and Function Limits",
    "Chapter 5: Uniform Convergence",
  ],
  cards: [
    makeAnalysisCard({
      id: "analysis140a-induction",
      chapter: "Chapter 1: Foundations of the Real Numbers",
      unit: "Foundations of the Real Numbers",
      topic: "Induction",
      name: "Induction Setup",
      order: 1,
      useItWhen: "the statement depends on n and must hold for every natural number",
      looksLike: "for all n in N, recursive formulas, sums, inequalities",
      doThis: "prove the first case, assume n, then prove n+1",
      thinkOfItAs: "push one domino, then show every domino hits the next",
      watchOutFor: "using the statement for n+1 before you prove it",
      rememberThis: "base case first, step second",
      quickExample: {
        problem: "How do you prove a statement for every n in N?",
        move: "Do the base case, then prove n implies n+1.",
      },
      typicalProblemShapes: [
        "Sums or inequalities indexed by n",
        "A recursively defined sequence with a property to prove for all n",
      ],
      miniDrill: [
        {
          prompt: "What are the two required parts of induction?",
          answer: "Base case and inductive step.",
        },
        {
          prompt: "What does the inductive step usually start with?",
          answer: "Assume the statement holds for n.",
        },
      ],
      memoryHook: "Start it, then pass it forward.",
      tags: ["analysis", "induction", "math140a"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-rational-irrational",
      chapter: "Chapter 1: Foundations of the Real Numbers",
      unit: "Foundations of the Real Numbers",
      topic: "Rationals and irrationals",
      name: "Rational vs Irrational Proof",
      order: 2,
      useItWhen: "you must show a number is not rational or compare Q and R",
      looksLike: "assume x = p/q, gcd(p,q)=1, parity or divisibility clash",
      doThis: "assume rational form in lowest terms, then force a contradiction",
      thinkOfItAs: "trap the fraction until the numerator and denominator both break",
      watchOutFor: "forgetting to start with lowest terms",
      rememberThis: "lowest terms first, contradiction next",
      quickExample: {
        problem: "How do you prove sqrt(2) is irrational?",
        move: "Assume sqrt(2)=p/q in lowest terms and force both p and q even.",
      },
      typicalProblemShapes: [
        "Classic irrationality proofs like sqrt(2)",
        "Proofs that a set contains irrational numbers between rationals",
      ],
      miniDrill: [
        {
          prompt: "Why do you say p/q is in lowest terms first?",
          answer: "So getting both even gives a contradiction.",
        },
        {
          prompt: "What proof method usually drives irrationality proofs?",
          answer: "Contradiction.",
        },
      ],
      memoryHook: "Lowest terms or the contradiction will not bite.",
      tags: ["analysis", "irrational", "contradiction"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-supremum",
      chapter: "Chapter 1: Foundations of the Real Numbers",
      unit: "Foundations of the Real Numbers",
      topic: "Supremum and infimum",
      name: "Supremum Pattern",
      order: 3,
      useItWhen: "a problem asks for least upper bound or greatest lower bound",
      whatItMeans:
        "The supremum of a set is the smallest number that still lies above every point in the set. It can sit outside the set; it just has to be the tightest top bound.",
      looksLike: "sup A, inf A, upper bound, lower bound",
      doThis: "prove two parts: it is a bound, and anything smaller fails",
      whyThisMove:
        "That proof pattern is just the definition unpacked. 'Supremum' means 'least upper bound', so you must prove both pieces: upper bound first, then leastness.",
      thinkOfItAs: "top fence with no lower fence above it",
      watchOutFor: "showing it is an upper bound but not the least one",
      rememberThis: "supremum proofs are always two checks",
      quickExample: {
        problem: "How do you prove s = sup A?",
        move: "Show s bounds A from above, then show any smaller number fails.",
      },
      typicalProblemShapes: [
        "A bounded set with a candidate least upper bound",
        "An epsilon-style proof that values get arbitrarily close to sup A",
      ],
      miniDrill: [
        {
          prompt: "What are the two parts of a supremum proof?",
          answer: "Upper-bound check and leastness check.",
        },
        {
          prompt: "What does the leastness check usually look like?",
          answer: "For every epsilon > 0, some point of A is above s - epsilon.",
        },
      ],
      memoryHook: "Bound it, then squeeze from below.",
      tags: ["analysis", "supremum", "math140a"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-completeness",
      chapter: "Chapter 1: Foundations of the Real Numbers",
      unit: "Foundations of the Real Numbers",
      topic: "Completeness axiom",
      name: "Completeness Trigger",
      order: 4,
      useItWhen: "a nonempty set is bounded above and the proof needs a least upper bound",
      whatItMeans:
        "Completeness says the real numbers do not have missing least-upper-bound holes. If a set is nonempty and bounded above, its supremum exists in R.",
      looksLike: "nonempty set, bounded above, sup A exists",
      doThis: "check nonempty and bounded above, then call completeness",
      whyThisMove:
        "You use completeness when the hard part is existence. Once the set satisfies the two hypotheses, completeness gives you a supremum to work with for the rest of the proof.",
      thinkOfItAs: "R has no missing least-upper-bound holes",
      watchOutFor: "calling completeness before you verify both hypotheses",
      rememberThis: "nonempty plus bounded above buys a supremum",
      quickExample: {
        problem: "When can you invoke completeness in R?",
        move: "When the set is nonempty and bounded above.",
      },
      typicalProblemShapes: [
        "A set built from all lower or upper candidates",
        "Proofs that define s = sup A and then work from that choice",
      ],
      miniDrill: [
        {
          prompt: "What are the two trigger hypotheses for completeness?",
          answer: "Nonempty and bounded above.",
        },
        {
          prompt: "What object does completeness hand you?",
          answer: "A least upper bound.",
        },
      ],
      memoryHook: "Check the set, then call sup.",
      tags: ["analysis", "completeness", "supremum"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-nested-intervals",
      chapter: "Chapter 1: Foundations of the Real Numbers",
      unit: "Foundations of the Real Numbers",
      topic: "Nested interval property",
      name: "Nested Intervals",
      order: 5,
      useItWhen: "closed intervals keep shrinking inside each other",
      looksLike: "[a1, b1] contains [a2, b2] contains [a3, b3]",
      doThis: "use completeness to conclude there is at least one point trapped in all of them",
      thinkOfItAs: "a shrinking hallway still leaves one meeting point",
      watchOutFor: "assuming the intersection is a whole interval when the lengths go to zero",
      rememberThis: "nested closed intervals cannot all miss each other",
      quickExample: {
        problem: "What does the nested interval property guarantee?",
        move: "At least one common point in all the intervals.",
      },
      typicalProblemShapes: [
        "A sequence of shrinking closed intervals",
        "Completeness arguments that trap a number by upper and lower bounds",
      ],
      miniDrill: [
        {
          prompt: "What kind of intervals does this property want?",
          answer: "Closed intervals nested inside each other.",
        },
        {
          prompt: "What extra fact gives a unique point instead of just a nonempty intersection?",
          answer: "The lengths go to zero.",
        },
      ],
      memoryHook: "Nested closed intervals still meet.",
      tags: ["analysis", "nested-intervals", "completeness"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-sequence-limit",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "Sequence convergence",
      name: "Sequence Convergence Proof",
      order: 6,
      useItWhen: "you need to prove a_n tends to L",
      whatItMeans:
        "Sequence convergence means the terms eventually get as close to L as you want and stay that close after some index.",
      looksLike: "for every epsilon > 0 there exists N",
      doThis: "start with epsilon, solve |a_n - L| < epsilon, then choose N",
      whyThisMove:
        "This is not just a style choice. The epsilon-N statement is the definition of convergence, so a real proof has to show exactly how large n must be to force the distance below epsilon.",
      thinkOfItAs: "turn the target into an N-threshold",
      watchOutFor: "writing the epsilon definition without actually choosing an N",
      rememberThis: "epsilon proof means solve for N",
      quickExample: {
        problem: "How do you prove a_n -> L?",
        move: "Take epsilon > 0 and solve the inequality for n.",
      },
      typicalProblemShapes: [
        "A direct epsilon-N limit proof",
        "A sequence with a simple formula like 1/n or (2n+1)/n",
      ],
      miniDrill: [
        {
          prompt: "What is the core algebra move in an epsilon-N proof?",
          answer: "Rewrite |a_n - L| < epsilon into a condition on n.",
        },
        {
          prompt: "What does N depend on?",
          answer: "Epsilon.",
        },
      ],
      memoryHook: "Given epsilon, solve for N.",
      tags: ["analysis", "sequences", "epsilon"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-limit-laws",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "Limit laws for sequences",
      name: "Sequence Limit Laws",
      order: 7,
      useItWhen: "a sequence is built from sums, products, or quotients of simpler sequences",
      looksLike: "a_n + b_n, a_n b_n, a_n / b_n",
      doThis: "break the sequence into parts with known limits, then apply the right law",
      thinkOfItAs: "once the pieces settle, the combined machine settles too",
      watchOutFor: "using the quotient law when the denominator limit is zero",
      rememberThis: "split first, then use the limit law",
      quickExample: {
        problem: "How do you handle (2n+1)/n in analysis style?",
        move: "Split it into 2 + 1/n and use limit laws.",
      },
      typicalProblemShapes: [
        "A rational expression in n that can be split into simple pieces",
        "A proof that builds from already-known sequence limits",
      ],
      miniDrill: [
        {
          prompt: "What should you check before using the quotient law?",
          answer: "The denominator limit is not zero.",
        },
        {
          prompt: "What is the first move on a messy algebraic sequence?",
          answer: "Break it into simpler convergent pieces.",
        },
      ],
      memoryHook: "Small limits combine by rules, not by panic.",
      tags: ["analysis", "limits", "sequence-laws"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-infinite-sequence-limits",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "Limits to infinity",
      name: "Sequence to Infinity",
      order: 8,
      useItWhen: "a sequence grows without bound or dives to negative infinity",
      looksLike: "a_n -> infinity, a_n -> -infinity",
      doThis: "switch from epsilon to M and show eventually the sequence beats every bound",
      thinkOfItAs: "no ceiling can hold the tail down",
      watchOutFor: "using epsilon-N language when the limit is infinity",
      rememberThis: "infinity proofs use M, not epsilon",
      quickExample: {
        problem: "How do you prove a_n -> infinity?",
        move: "Given M, solve a_n > M for n.",
      },
      typicalProblemShapes: [
        "Polynomial or recursive sequences that keep growing",
        "A proof that the tail eventually passes every target height",
      ],
      miniDrill: [
        {
          prompt: "What variable replaces epsilon here?",
          answer: "M.",
        },
        {
          prompt: "What inequality do you solve in an infinity proof?",
          answer: "a_n > M, or a_n < M for negative infinity.",
        },
      ],
      memoryHook: "Infinity means beat every ceiling.",
      tags: ["analysis", "infinity", "sequences"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-monotone-bounded",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "Monotone convergence",
      name: "Monotone + Bounded",
      order: 9,
      useItWhen: "a sequence is monotone and you want convergence fast",
      whatItMeans:
        "Monotone means the sequence only moves one way. Bounded means it cannot escape forever in that direction.",
      looksLike: "increasing and bounded above, or decreasing and bounded below",
      doThis: "state monotone plus bounded, then point to monotone convergence",
      whyThisMove:
        "The theorem is built exactly for this shape. One-way motion stops oscillation, and the bound stops runaway behavior, so the sequence has to settle at a limit.",
      thinkOfItAs: "if it moves one way and cannot escape, it must settle",
      watchOutFor: "showing monotone but forgetting the bound",
      rememberThis: "monotone and bounded means convergent",
      quickExample: {
        problem: "What technique fits first for an increasing bounded sequence?",
        move: "Use monotone convergence.",
      },
      typicalProblemShapes: [
        "Recursive sequences shown to increase and stay below a ceiling",
        "A proof asking whether a sequence converges without finding the exact limit yet",
      ],
      miniDrill: [
        {
          prompt: "What second ingredient must monotonicity pair with?",
          answer: "A bound in the right direction.",
        },
        {
          prompt: "Does bounded alone imply convergence?",
          answer: "No.",
        },
      ],
      memoryHook: "One-way motion plus a fence means convergence.",
      tags: ["analysis", "monotone", "bounded"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-cauchy",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "Cauchy sequences",
      name: "Cauchy Sequence Pattern",
      order: 10,
      useItWhen: "you want an internal convergence test without naming the limit first",
      whatItMeans:
        "A Cauchy sequence means the tail terms get arbitrarily close to each other, even before you know what the limit is.",
      looksLike:
        "for every epsilon > 0 there exists N so m, n >= N implies |a_n - a_m| < epsilon",
      doThis: "compare late terms to each other instead of guessing the limit",
      whyThisMove:
        "That is the definition. A Cauchy proof has to control tail-to-tail distance |a_n-a_m| directly, because the whole point is to avoid assuming the limit first.",
      thinkOfItAs: "the tail of the sequence bunches together",
      watchOutFor: "trying to prove Cauchy by already assuming the limit exists",
      rememberThis: "Cauchy means late terms get arbitrarily close to each other",
      quickExample: {
        problem: "What is the first move in a Cauchy proof?",
        move: "Start with |a_n - a_m| and make the tail small.",
      },
      typicalProblemShapes: [
        "A completeness proof in R",
        "A sequence where the limit is not obvious but tail differences are manageable",
      ],
      miniDrill: [
        {
          prompt: "What variables appear in a Cauchy definition?",
          answer: "Both m and n.",
        },
        {
          prompt: "What is the mental picture of a Cauchy tail?",
          answer: "The terms bunch together.",
        },
      ],
      memoryHook: "No limit in sight? Compare tail to tail.",
      tags: ["analysis", "cauchy", "completeness"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-bolzano-weierstrass",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "Bolzano-Weierstrass",
      name: "Bounded Sequence -> Convergent Subsequence",
      order: 11,
      useItWhen: "a bounded sequence appears and you need some convergence, not full convergence",
      looksLike: "bounded sequence, extract a subsequence",
      doThis: "stop trying to prove the whole sequence converges and extract a convergent subsequence instead",
      thinkOfItAs: "even messy bounded data has a calm strand hidden inside",
      watchOutFor: "mistaking subsequence convergence for full sequence convergence",
      rememberThis:
        "bounded sequence guarantees a good subsequence, not always the whole sequence",
      quickExample: {
        problem:
          "What technique fits first when a bounded sequence refuses to converge?",
        move: "Use Bolzano-Weierstrass to extract a convergent subsequence.",
      },
      typicalProblemShapes: [
        "A bounded sequence with oscillation",
        "Compactness-style arguments in early analysis",
      ],
      miniDrill: [
        {
          prompt: "What does boundedness buy you here?",
          answer: "A convergent subsequence.",
        },
        {
          prompt: "Does it force the full sequence to converge?",
          answer: "No.",
        },
      ],
      memoryHook: "Bounded chaos still hides a convergent thread.",
      tags: ["analysis", "subsequences", "compactness"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-subsequence-test",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "Subsequence test for divergence",
      name: "Subsequence Test",
      order: 12,
      useItWhen: "you want to prove a sequence does not converge",
      looksLike: "two subsequences head to different limits",
      doThis: "find two subsequences with different long-term behavior",
      thinkOfItAs: "if two tails disagree, the full sequence cannot settle",
      watchOutFor:
        "using two random subsequences that do not actually approach different limits",
      rememberThis: "different subsequence limits kill convergence",
      quickExample: {
        problem: "How do you quickly prove (-1)^n does not converge?",
        move: "Use even and odd subsequences.",
      },
      typicalProblemShapes: [
        "Oscillating sequences",
        "A divergence proof where the full sequence keeps switching behavior",
      ],
      miniDrill: [
        {
          prompt: "What is the fastest divergence pattern here?",
          answer: "Two subsequences with different limits.",
        },
        {
          prompt: "What famous sequence is the classic example?",
          answer: "(-1)^n.",
        },
      ],
      memoryHook: "Two different tails means no single limit.",
      tags: ["analysis", "subsequences", "divergence"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-limsup-liminf",
      chapter: "Chapter 2: Sequences and Limits",
      unit: "Sequences and Limits",
      topic: "limsup and liminf",
      name: "limsup / liminf Pattern",
      order: 13,
      useItWhen: "a sequence oscillates and you still need its top and bottom long-run behavior",
      looksLike: "limsup a_n, liminf a_n, tail suprema, tail infima",
      doThis: "track the largest and smallest values the tail keeps revisiting",
      thinkOfItAs: "limsup is the top floor the tail keeps touching; liminf is the bottom floor",
      watchOutFor: "mixing up one-time spikes with values that keep returning in the tail",
      rememberThis: "limsup and liminf are tail behaviors, not first-term behavior",
      quickExample: {
        problem: "What do limsup and liminf measure?",
        move: "The highest and lowest long-run tail values.",
      },
      typicalProblemShapes: [
        "Oscillating sequences with several cluster values",
        "A problem asking for long-run upper and lower limits instead of one limit",
      ],
      miniDrill: [
        {
          prompt: "What does limsup watch?",
          answer: "The top value the tail keeps getting near.",
        },
        {
          prompt: "What happens if limsup equals liminf?",
          answer: "The sequence converges to that common value.",
        },
      ],
      memoryHook: "Tail ceiling, tail floor.",
      tags: ["analysis", "limsup", "liminf"],
      difficulty: "Stretch",
    }),
    makeAnalysisCard({
      id: "analysis140a-series",
      chapter: "Chapter 3: Series",
      unit: "Series",
      topic: "Series as partial sums",
      name: "Series First Move",
      order: 14,
      useItWhen: "you see an infinite sum and need the right entry point",
      looksLike: "sum a_n, partial sums s_n, geometric series, p-series",
      doThis: "stop and translate the series into its partial sums first",
      thinkOfItAs: "a series is really just a sequence in disguise",
      watchOutFor: "treating sum a_n like a single algebra object instead of a limit of sums",
      rememberThis: "series questions start with partial sums",
      quickExample: {
        problem: "What is the first move on an infinite series?",
        move: "Think about the sequence of partial sums.",
      },
      typicalProblemShapes: [
        "A convergence question for sum a_n",
        "A geometric or p-series recognition problem",
      ],
      miniDrill: [
        {
          prompt: "What sequence belongs to a series?",
          answer: "Its partial sums.",
        },
        {
          prompt: "What is the fastest easy pattern to recognize in series?",
          answer: "Geometric and p-series.",
        },
      ],
      memoryHook: "Series = sequence of partial sums.",
      tags: ["analysis", "series", "partial-sums"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-series-tests",
      chapter: "Chapter 3: Series",
      unit: "Series",
      topic: "Series convergence tests",
      name: "Series Test Match",
      order: 15,
      useItWhen: "the series is not geometric or telescoping and you need the right test",
      looksLike: "positive terms, alternating signs, nth roots, ratio shape, comparison shape",
      doThis: "match the shape first: comparison, root, integral, or alternating",
      thinkOfItAs: "series tests are a tool match, not a random guess",
      watchOutFor: "using a fancy test before checking the sign pattern and basic shape",
      rememberThis: "pick the test from the pattern",
      quickExample: {
        problem: "What is the first move on a positive-term series?",
        move: "Ask which comparison-style test fits the shape best.",
      },
      typicalProblemShapes: [
        "A positive-term series with polynomial or exponential pieces",
        "An alternating series where you need monotone decrease and term-to-zero",
      ],
      miniDrill: [
        {
          prompt: "What test often fits n-th powers or factorial/exponential shapes?",
          answer: "Root or ratio style tests.",
        },
        {
          prompt: "What must you check on an alternating series right away?",
          answer: "Terms decrease in size and go to zero.",
        },
      ],
      memoryHook: "Read the sign and growth before picking the test.",
      tags: ["analysis", "series", "tests"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-continuity",
      chapter: "Chapter 4: Continuity and Function Limits",
      unit: "Continuity and Function Limits",
      topic: "Continuity at a point",
      name: "Epsilon-Delta Continuity",
      order: 16,
      useItWhen: "you must prove f is continuous at a point with definitions",
      looksLike: "for every epsilon there exists delta",
      doThis: "start from |f(x) - f(a)| < epsilon and solve backward for a delta condition",
      thinkOfItAs: "delta controls x so epsilon controls y",
      watchOutFor: "picking delta before seeing what the algebra asks for",
      rememberThis: "continuity proof means build delta from epsilon",
      quickExample: {
        problem: "How do you start a continuity proof at a?",
        move: "Write |f(x) - f(a)| < epsilon and work backward.",
      },
      typicalProblemShapes: [
        "A direct definition proof for polynomials or simple rational functions",
        "A pointwise continuity proof where you need an explicit delta",
      ],
      miniDrill: [
        {
          prompt: "What inequality do you solve backward from?",
          answer: "|f(x) - f(a)| < epsilon.",
        },
        {
          prompt: "What is the point of delta?",
          answer: "It controls how close x must stay to a.",
        },
      ],
      memoryHook: "Epsilon asks. Delta answers.",
      tags: ["analysis", "continuity", "epsilon-delta"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-sequential-continuity",
      chapter: "Chapter 4: Continuity and Function Limits",
      unit: "Continuity and Function Limits",
      topic: "Sequential continuity",
      name: "Sequential Continuity Test",
      order: 17,
      useItWhen: "a continuity proof is easier with sequences than epsilon-delta",
      looksLike: "x_n -> a implies f(x_n) -> f(a)",
      doThis: "start with an arbitrary sequence x_n -> a and push it through f",
      thinkOfItAs: "continuity means limits survive the function",
      watchOutFor:
        "choosing a special sequence instead of an arbitrary one when proving continuity",
      rememberThis: "continuous functions preserve sequence limits",
      quickExample: {
        problem: "What is the sequence version of continuity at a?",
        move: "Take any x_n -> a and show f(x_n) -> f(a).",
      },
      typicalProblemShapes: [
        "A proof that continuity follows from a sequence criterion",
        "A discontinuity proof using one bad sequence",
      ],
      miniDrill: [
        {
          prompt: "What kind of sequence starts the proof?",
          answer: "An arbitrary sequence converging to a.",
        },
        {
          prompt: "What does one bad sequence prove?",
          answer: "Discontinuity.",
        },
      ],
      memoryHook: "Continuity lets limits pass through f.",
      tags: ["analysis", "sequential-continuity", "continuity"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-ivt",
      chapter: "Chapter 4: Continuity and Function Limits",
      unit: "Continuity and Function Limits",
      topic: "Intermediate Value Theorem",
      name: "IVT Recognition",
      order: 18,
      useItWhen: "a continuous function crosses from one sign or value to another on an interval",
      looksLike: "f(a) < 0 < f(b) or values on both sides of a target",
      doThis: "check continuity on the interval, then use IVT to trap the missing value",
      thinkOfItAs: "a continuous graph cannot teleport over values",
      watchOutFor: "using IVT without continuity on the full interval",
      rememberThis: "continuous crossing means the middle value is hit",
      quickExample: {
        problem:
          "f(a) is negative and f(b) is positive. What theorem should you test first?",
        move: "The Intermediate Value Theorem.",
      },
      typicalProblemShapes: [
        "Existence of a root from opposite signs",
        "A value-between-two-values question for a continuous function",
      ],
      miniDrill: [
        {
          prompt: "What is the must-have hypothesis for IVT?",
          answer: "Continuity on the interval.",
        },
        {
          prompt: "What does opposite sign usually buy you?",
          answer: "A root somewhere in between.",
        },
      ],
      memoryHook: "No teleporting over middle values.",
      tags: ["analysis", "ivt", "continuity"],
      difficulty: "Starter",
    }),
    makeAnalysisCard({
      id: "analysis140a-uniform-continuity",
      chapter: "Chapter 4: Continuity and Function Limits",
      unit: "Continuity and Function Limits",
      topic: "Uniform continuity",
      name: "Uniform Continuity Trigger",
      order: 19,
      useItWhen: "one delta must work for every point, not just one fixed point",
      looksLike: "same delta for all x and y, continuous on [a,b]",
      doThis: "check whether the problem wants one global delta or use Heine-Cantor on a closed interval",
      thinkOfItAs: "one rule that works everywhere, not a fresh delta at each point",
      watchOutFor: "giving a delta that secretly depends on the point",
      rememberThis: "uniform means one delta works across the whole set",
      quickExample: {
        problem: "How is uniform continuity different from ordinary continuity?",
        move: "The delta cannot depend on the point.",
      },
      typicalProblemShapes: [
        "A proof that continuity on [a,b] is stronger than pointwise continuity",
        "A question asking whether Cauchy inputs stay Cauchy after applying f",
      ],
      miniDrill: [
        {
          prompt: "What changes in the delta condition here?",
          answer: "Delta works for all points at once.",
        },
        {
          prompt: "What theorem often solves this on a closed interval?",
          answer: "Heine-Cantor.",
        },
      ],
      memoryHook: "Same delta, whole set.",
      tags: ["analysis", "uniform-continuity", "heine-cantor"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-function-limits",
      chapter: "Chapter 4: Continuity and Function Limits",
      unit: "Continuity and Function Limits",
      topic: "Limits of functions",
      name: "Function Limit Proof",
      order: 20,
      useItWhen: "you must prove lim f(x) = L as x goes to a or compare left and right limits",
      looksLike: "lim x->a f(x), epsilon-delta, one-sided limits, x->infinity",
      doThis: "decide whether the cleaner route is epsilon-delta or sequential limits, then prove both sides line up",
      thinkOfItAs: "function limits ask what every nearby input makes the output do",
      watchOutFor: "confusing continuity at a with a limit as x goes to a",
      rememberThis: "limits care about nearby x, not the value at the point",
      quickExample: {
        problem: "What is the first check when left and right limits look different?",
        move: "Treat each side separately and compare the results.",
      },
      typicalProblemShapes: [
        "One-sided limit comparisons",
        "A function with different formulas on rational and irrational inputs",
      ],
      miniDrill: [
        {
          prompt: "What kills a two-sided limit fast?",
          answer: "Different left and right limits.",
        },
        {
          prompt: "What is the quickest sequence-based disproof tool?",
          answer: "Choose two sequences approaching the same point with different output limits.",
        },
      ],
      memoryHook: "Nearby inputs decide the limit.",
      tags: ["analysis", "function-limits", "continuity"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-contradiction",
      chapter: "Chapter 4: Continuity and Function Limits",
      unit: "Continuity and Function Limits",
      topic: "Contradiction in analysis",
      name: "Contradiction Pattern in Analysis",
      order: 21,
      useItWhen: "a direct epsilon proof gets ugly and the negation has a cleaner shape",
      looksLike: "assume not, build a bad sequence, force a clash",
      doThis: "negate the target carefully, then manufacture the object that breaks it",
      thinkOfItAs: "analysis contradiction often means build the failure sequence",
      watchOutFor: "using contradiction without writing the correct negation first",
      rememberThis: "the wrong negation ruins the whole proof",
      quickExample: {
        problem: "What often gets built in an analysis contradiction proof?",
        move: "A sequence that witnesses failure over and over.",
      },
      typicalProblemShapes: [
        "Proofs about boundedness, continuity, or uniqueness",
        "Statements where failure naturally produces a bad sequence",
      ],
      miniDrill: [
        {
          prompt: "What should come before the contradiction construction?",
          answer: "The exact negation of the statement.",
        },
        {
          prompt: "What is a very common contradiction gadget in analysis?",
          answer: "A bad sequence.",
        },
      ],
      memoryHook: "Negate cleanly, then build the failure.",
      tags: ["analysis", "contradiction", "proofs"],
      difficulty: "Standard",
    }),
    makeAnalysisCard({
      id: "analysis140a-uniform-convergence",
      chapter: "Chapter 5: Uniform Convergence",
      unit: "Uniform Convergence",
      topic: "Uniform convergence",
      name: "Uniform Convergence Check",
      order: 22,
      useItWhen: "a sequence or series of functions converges and you must know whether the convergence is uniform",
      looksLike: "sup |f_n - f|, uniform in x, exchange limit and continuity questions",
      doThis: "ask whether one N works for every x, not just pointwise for each x",
      thinkOfItAs: "the whole graph settles together, not point by point at different speeds",
      watchOutFor: "proving pointwise convergence and calling it uniform",
      rememberThis: "uniform means the tail is small everywhere at once",
      quickExample: {
        problem: "What is the first clue that convergence should be uniform?",
        move: "Look for one bound that controls all x at the same time.",
      },
      typicalProblemShapes: [
        "A sequence of functions with an x-independent bound",
        "A problem asking whether continuity survives taking the limit",
      ],
      miniDrill: [
        {
          prompt: "What is the key phrase in the definition of uniform convergence?",
          answer: "For all x, with one N working for all of them.",
        },
        {
          prompt: "What common mistake do students make here?",
          answer: "Confusing pointwise convergence with uniform convergence.",
        },
      ],
      memoryHook: "One N for the whole graph.",
      tags: ["analysis", "uniform-convergence", "functions"],
      difficulty: "Stretch",
    }),
  ],
};
