import type { BubbleCard, CourseContent } from "@/content/schema";

function makeCalcCard(
  card: Omit<BubbleCard, "subject" | "course">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Calculus 3",
    ...card,
  };
}

export const calcThreeCourse: CourseContent = {
  id: "calc-3",
  subject: "Mathematics",
  title: "Calculus 3",
  shortDescription:
    "Vectors, partial derivatives, multiple integrals, and vector calculus.",
  units: [
    "Vectors & 3D",
    "Vector Functions",
    "Partial Derivatives",
    "Multiple Integrals",
    "Vector Calculus",
  ],
  chapters: [
    "Chapter 12: Vectors and the Geometry of Space",
    "Chapter 13: Vector Functions",
    "Chapter 14: Partial Derivatives",
    "Chapter 15: Multiple Integrals",
    "Chapter 16: Vector Calculus",
  ],
  cards: [
    makeCalcCard({
      id: "calc3-3d-points",
      chapter: "Chapter 12: Vectors and the Geometry of Space",
      unit: "Vectors & 3D",
      topic: "3D points and distance",
      name: "3D Points",
      order: 1,
      useItWhen: "you move from the plane into x-y-z space",
      looksLike: "(x, y, z)",
      doThis: "plot the point using three coordinates instead of two",
      thinkOfItAs: "2D with one more direction",
      watchOutFor: "forgetting z adds depth",
      rememberThis: "same idea, one more axis",
      quickExample: {
        problem: "Plot (2, -1, 3).",
        move: "Go x, then y, then up in z.",
      },
      typicalProblemShapes: [
        "Points in space",
        "Distance or midpoint in 3D",
      ],
      miniDrill: [
        { prompt: "How many coordinates does a 3D point use?", answer: "Three." },
        { prompt: "What does z add?", answer: "Depth." },
      ],
      memoryHook: "3D is just one extra axis.",
      tags: ["calc3", "3d", "coordinates"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-vectors",
      chapter: "Chapter 12: Vectors and the Geometry of Space",
      unit: "Vectors & 3D",
      topic: "Vectors",
      name: "Vectors",
      order: 2,
      useItWhen: "you need magnitude and direction together",
      looksLike: "<a, b, c>",
      doThis: "treat the entries as a direction move",
      thinkOfItAs: "an arrow, not a location",
      watchOutFor: "mixing up a point with a vector",
      rememberThis: "points locate, vectors move",
      quickExample: {
        problem: "What does <2, -1, 3> mean?",
        move: "A move right 2, back 1, up 3.",
      },
      typicalProblemShapes: [
        "Displacement questions",
        "Magnitude and direction problems",
      ],
      miniDrill: [
        { prompt: "Does a vector represent a place or a move?", answer: "A move." },
        { prompt: "Can vectors live in 2D and 3D?", answer: "Yes." },
      ],
      memoryHook: "A vector is a move with direction.",
      tags: ["calc3", "vectors", "basics"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-dot-product",
      chapter: "Chapter 12: Vectors and the Geometry of Space",
      unit: "Vectors & 3D",
      topic: "Dot product",
      name: "Dot Product",
      order: 3,
      useItWhen: "you need angle, projection, or orthogonality",
      looksLike: "u dot v",
      doThis: "multiply matching components and add",
      thinkOfItAs: "how aligned two arrows are",
      watchOutFor: "confusing dot with cross product",
      rememberThis: "dot gives a number",
      quickExample: {
        problem: "Find <1,2,3> dot <4,5,6>.",
        move: "Multiply matches and add.",
      },
      typicalProblemShapes: [
        "Angle between vectors",
        "Checking if vectors are perpendicular",
      ],
      miniDrill: [
        { prompt: "What does dot product output: number or vector?", answer: "Number." },
        { prompt: "If the dot product is 0, what is the usual meaning?", answer: "Perpendicular." },
      ],
      memoryHook: "Dot = multiply, match, add.",
      tags: ["calc3", "vectors", "dot-product"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-cross-product",
      chapter: "Chapter 12: Vectors and the Geometry of Space",
      unit: "Vectors & 3D",
      topic: "Cross product",
      name: "Cross Product",
      order: 4,
      useItWhen: "you need a vector perpendicular to two others",
      looksLike: "u cross v",
      doThis: "use the determinant pattern and right-hand direction",
      thinkOfItAs: "two vectors making a new normal vector",
      watchOutFor: "reversing the order and flipping the sign",
      rememberThis: "cross gives a perpendicular vector",
      quickExample: {
        problem: "What does u x v point toward?",
        move: "Perpendicular to both, by the right-hand rule.",
      },
      typicalProblemShapes: [
        "Normals to planes",
        "Area of parallelogram problems",
      ],
      miniDrill: [
        { prompt: "Does cross product output a number or vector?", answer: "A vector." },
        { prompt: "What happens if you swap the order?", answer: "The sign flips." },
      ],
      memoryHook: "Cross makes the normal.",
      tags: ["calc3", "vectors", "cross-product"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-lines",
      chapter: "Chapter 12: Vectors and the Geometry of Space",
      unit: "Vectors & 3D",
      topic: "Lines in space",
      name: "Lines in 3D",
      order: 5,
      useItWhen: "you need a line through a point with a direction vector",
      looksLike: "r(t) = r0 + tv",
      doThis: "use one point and one direction vector",
      thinkOfItAs: "starting point plus repeated direction steps",
      watchOutFor: "using a point where a direction vector belongs",
      rememberThis: "point plus direction gives the line",
      quickExample: {
        problem: "Write the line through a point parallel to v.",
        move: "Use r0 + tv.",
      },
      typicalProblemShapes: [
        "Parametric line equations",
        "Symmetric line equations",
      ],
      miniDrill: [
        { prompt: "How many ingredients build a 3D line?", answer: "A point and a direction vector." },
        { prompt: "What does t do?", answer: "Moves along the line." },
      ],
      memoryHook: "Point plus direction builds the line.",
      tags: ["calc3", "3d", "lines"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-planes",
      chapter: "Chapter 12: Vectors and the Geometry of Space",
      unit: "Vectors & 3D",
      topic: "Planes in space",
      name: "Planes",
      order: 6,
      useItWhen: "you need a flat surface in 3D",
      looksLike: "ax + by + cz = d",
      doThis: "use a point and a normal vector",
      thinkOfItAs: "all points facing the same normal",
      watchOutFor: "confusing a normal vector with a direction inside the plane",
      rememberThis: "normal vector controls the plane",
      quickExample: {
        problem: "What does <a,b,c> mean in a plane equation?",
        move: "It is the normal vector.",
      },
      typicalProblemShapes: [
        "Plane equations",
        "Parallel or perpendicular plane questions",
      ],
      miniDrill: [
        { prompt: "What vector defines the plane's orientation?", answer: "The normal vector." },
        { prompt: "Is ax + by + cz = d a line or a plane?", answer: "A plane." },
      ],
      memoryHook: "Plane = point plus normal.",
      tags: ["calc3", "3d", "planes"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-quadric-surfaces",
      chapter: "Chapter 12: Vectors and the Geometry of Space",
      unit: "Vectors & 3D",
      topic: "Quadric surfaces",
      name: "Quadric Surfaces",
      order: 7,
      useItWhen: "you graph 3D equations with squared variables",
      looksLike: "ellipsoids, paraboloids, hyperboloids",
      doThis: "identify the sign pattern and axis directions",
      thinkOfItAs: "conic sections promoted to 3D",
      watchOutFor: "guessing the shape without reading the signs",
      rememberThis: "the sign pattern tells the surface",
      quickExample: {
        problem: "How do you spot an ellipsoid?",
        move: "All squared terms positive with a constant on the other side.",
      },
      typicalProblemShapes: [
        "3D graphing with squared x, y, z terms",
        "Naming the surface from the equation",
      ],
      miniDrill: [
        { prompt: "Do sign changes matter here?", answer: "Yes. A lot." },
        { prompt: "Is a paraboloid a 3D surface?", answer: "Yes." },
      ],
      memoryHook: "Read the signs before you name the shape.",
      tags: ["calc3", "3d", "quadric-surfaces"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-vector-valued-functions",
      chapter: "Chapter 13: Vector Functions",
      unit: "Vector Functions",
      topic: "Vector-valued functions",
      name: "Vector-Valued Functions",
      order: 8,
      useItWhen: "a particle moves through space with time",
      looksLike: "r(t) = <x(t), y(t), z(t)>",
      doThis: "differentiate or integrate component by component",
      thinkOfItAs: "parametric motion in vector form",
      watchOutFor: "trying to treat the whole vector as one scalar formula",
      rememberThis: "work component by component",
      quickExample: {
        problem: "Differentiate <t, t^2, sin t>.",
        move: "Differentiate each entry.",
      },
      typicalProblemShapes: [
        "Position, velocity, acceleration in space",
        "Vector equations of curves",
      ],
      miniDrill: [
        { prompt: "How do you differentiate a vector function?", answer: "One component at a time." },
        { prompt: "What is r-prime usually called in motion?", answer: "Velocity." },
      ],
      memoryHook: "Vector functions split into components.",
      tags: ["calc3", "vectors", "motion"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-curvature",
      chapter: "Chapter 13: Vector Functions",
      unit: "Vector Functions",
      topic: "Arc length and curvature",
      name: "Curvature",
      order: 9,
      useItWhen: "you need how sharply a space curve bends",
      looksLike: "arc length, unit tangent, curvature formulas",
      doThis: "find velocity and tangent behavior, then measure the bend",
      thinkOfItAs: "how hard the path turns",
      watchOutFor: "mixing speed with curvature",
      rememberThis: "curvature measures turning, not just motion",
      quickExample: {
        problem: "What does large curvature mean?",
        move: "The curve bends sharply there.",
      },
      typicalProblemShapes: [
        "Space curves with tangent and normal vectors",
        "Questions about how sharply a path bends",
      ],
      miniDrill: [
        { prompt: "Does big curvature mean straighter or bendier?", answer: "Bendier." },
        { prompt: "Is curvature the same as speed?", answer: "No." },
      ],
      memoryHook: "Curvature is turning intensity.",
      tags: ["calc3", "space-curves", "curvature"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-multivariable-functions",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Functions of several variables",
      name: "Multivariable Functions",
      order: 10,
      useItWhen: "the output depends on two or more inputs",
      looksLike: "f(x, y) or f(x, y, z)",
      doThis: "read the function as a surface or higher-dimensional rule",
      thinkOfItAs: "one output fed by several knobs",
      watchOutFor: "forgetting the domain can be restricted",
      rememberThis: "more inputs still means one output",
      quickExample: {
        problem: "What does z = f(x, y) usually graph as?",
        move: "A surface in 3D.",
      },
      typicalProblemShapes: [
        "Surfaces like z = x^2 + y^2",
        "Functions with two inputs",
      ],
      miniDrill: [
        { prompt: "Does f(x,y) have one output or two?", answer: "One output." },
        { prompt: "What does z = f(x,y) usually make?", answer: "A surface." },
      ],
      memoryHook: "More inputs, still one output.",
      tags: ["calc3", "multivariable", "surfaces"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-multivariable-limits",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Limits and continuity in several variables",
      name: "Multivariable Limits",
      order: 11,
      useItWhen: "you need the behavior near a point on a surface",
      looksLike: "limit as (x, y) goes to (a, b)",
      doThis: "test whether different paths give the same answer",
      thinkOfItAs: "path-checking instead of left-right checking",
      watchOutFor: "testing only one path",
      rememberThis: "different paths, different answer means no limit",
      quickExample: {
        problem: "How can a two-variable limit fail?",
        move: "Different paths can give different values.",
      },
      typicalProblemShapes: [
        "Limits at the origin in x and y",
        "Path comparison problems",
      ],
      miniDrill: [
        { prompt: "Do multivariable limits use left and right only?", answer: "No. There are many paths." },
        { prompt: "If two paths disagree, does the limit exist?", answer: "No." },
      ],
      memoryHook: "If paths disagree, the limit dies.",
      tags: ["calc3", "limits", "multivariable"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-partial-derivatives",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Partial derivatives",
      name: "Partial Derivatives",
      order: 12,
      useItWhen: "you change one variable and freeze the others",
      looksLike: "f_x, f_y, f_z",
      doThis: "differentiate with respect to one variable at a time",
      thinkOfItAs: "one knob moves while the others stay still",
      watchOutFor: "changing the frozen variables too",
      rememberThis: "treat the other variables like constants",
      quickExample: {
        problem: "Find f_x of x^2 y + y^3.",
        move: "Treat y like a constant.",
      },
      typicalProblemShapes: [
        "Functions in x and y with subscripts like f_x",
        "Rate of change in one input direction",
      ],
      miniDrill: [
        { prompt: "When finding f_x, what happens to y?", answer: "Treat it like a constant." },
        { prompt: "Can a function have more than one partial derivative?", answer: "Yes." },
      ],
      memoryHook: "One variable moves, the rest freeze.",
      tags: ["calc3", "partials", "derivatives"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-tangent-plane",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Tangent planes and linearization",
      name: "Tangent Plane",
      order: 13,
      useItWhen: "you need the flat local approximation to a surface",
      looksLike: "find the tangent plane at a point",
      doThis: "use the point, f_x, and f_y",
      thinkOfItAs: "the local flat patch of the surface",
      watchOutFor: "forgetting the base point values",
      rememberThis: "point plus partial slopes builds the plane",
      quickExample: {
        problem: "What derivatives drive the tangent plane?", 
        move: "f_x and f_y at the point.",
      },
      typicalProblemShapes: [
        "Linearization of z = f(x,y)",
        "Approximation near one point on a surface",
      ],
      miniDrill: [
        { prompt: "How many first partials drive the tangent plane in 2 variables?", answer: "Two." },
        { prompt: "Is the tangent plane exact far away from the point?", answer: "No." },
      ],
      memoryHook: "Use the point and the partial slopes.",
      tags: ["calc3", "tangent-plane", "linearization"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-multivariable-chain-rule",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Chain rule in several variables",
      name: "Multivariable Chain Rule",
      order: 14,
      useItWhen: "variables depend on other variables in layers",
      looksLike: "z = f(x, y) with x and y both depending on t",
      doThis: "take all dependency paths into account",
      thinkOfItAs: "a flowchart of derivatives",
      watchOutFor: "missing one path",
      rememberThis: "every path contributes",
      quickExample: {
        problem: "If z depends on x and y, and both depend on t, what shows up in dz/dt?",
        move: "Both x-path and y-path pieces.",
      },
      typicalProblemShapes: [
        "x and y both functions of t",
        "Tree diagrams for derivatives",
      ],
      miniDrill: [
        { prompt: "If there are two input paths, do both matter?", answer: "Yes." },
        { prompt: "What is the common mistake here?", answer: "Missing a path." },
      ],
      memoryHook: "Follow every dependency path.",
      tags: ["calc3", "chain-rule", "partials"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-directional-derivative",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Directional derivatives",
      name: "Directional Derivative",
      order: 15,
      useItWhen: "you need the rate of change in a chosen direction",
      looksLike: "D_u f",
      doThis: "use gradient dot unit direction vector",
      thinkOfItAs: "how steep it is if you walk this way",
      watchOutFor: "forgetting to make the direction vector a unit vector",
      rememberThis: "directional derivative = grad f dot u",
      quickExample: {
        problem: "How do you test the slope toward a direction u?",
        move: "Dot the gradient with the unit vector.",
      },
      typicalProblemShapes: [
        "Rate of change in a specific direction",
        "Questions giving a vector direction at a point",
      ],
      miniDrill: [
        { prompt: "Does u need length 1?", answer: "Yes." },
        { prompt: "What vector is paired with u?", answer: "The gradient." },
      ],
      memoryHook: "Pick a direction, dot the gradient.",
      tags: ["calc3", "directional-derivative", "gradient"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-gradient",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Gradient",
      name: "Gradient",
      order: 16,
      useItWhen: "you need the direction of fastest increase",
      looksLike: "grad f or nabla f",
      doThis: "build the vector of first partial derivatives",
      thinkOfItAs: "the steepest uphill arrow",
      watchOutFor: "thinking the gradient is a number",
      rememberThis: "gradient points uphill fastest",
      quickExample: {
        problem: "What is grad f for f(x,y)?",
        move: "<f_x, f_y>.",
      },
      typicalProblemShapes: [
        "Steepest ascent questions",
        "Normal vectors to level curves or surfaces",
      ],
      miniDrill: [
        { prompt: "Is the gradient a vector or scalar?", answer: "A vector." },
        { prompt: "What direction does it point?", answer: "Fastest increase." },
      ],
      memoryHook: "Gradient is the uphill arrow.",
      tags: ["calc3", "gradient", "partials"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-two-variable-extrema",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Local extrema in two variables",
      name: "Two-Variable Extrema",
      order: 17,
      useItWhen: "you need max or min of f(x,y)",
      looksLike: "find critical points and classify them",
      doThis: "set first partials to zero, then use the second-derivative test",
      thinkOfItAs: "hill, valley, or saddle on a surface",
      watchOutFor: "calling every critical point a max or min",
      rememberThis: "critical point first, classification second",
      quickExample: {
        problem: "What can a critical point be besides max or min?",
        move: "A saddle point.",
      },
      typicalProblemShapes: [
        "f_x = 0 and f_y = 0 systems",
        "Questions about local max, min, or saddle",
      ],
      miniDrill: [
        { prompt: "What equations define critical points in two variables?", answer: "f_x = 0 and f_y = 0." },
        { prompt: "Can a critical point be neither max nor min?", answer: "Yes." },
      ],
      memoryHook: "Surfaces can saddle, not just peak or dip.",
      tags: ["calc3", "optimization", "critical-points"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-lagrange-multipliers",
      chapter: "Chapter 14: Partial Derivatives",
      unit: "Partial Derivatives",
      topic: "Lagrange multipliers",
      name: "Lagrange Multipliers",
      order: 18,
      useItWhen: "you optimize with a constraint",
      looksLike: "maximize f subject to g = c",
      doThis: "set grad f = lambda grad g and use the constraint too",
      thinkOfItAs: "best point while stuck on a fence",
      watchOutFor: "forgetting the original constraint equation",
      rememberThis: "optimize plus constraint means gradients line up",
      quickExample: {
        problem: "How do you start constrained optimization?",
        move: "Write grad f = lambda grad g.",
      },
      typicalProblemShapes: [
        "Max/min with a curve or surface restriction",
        "Optimization with one explicit constraint",
      ],
      miniDrill: [
        { prompt: "What extra equation must stay in the system?", answer: "The constraint." },
        { prompt: "What symbol usually appears here?", answer: "Lambda." },
      ],
      memoryHook: "Constraint problem? Line up the gradients.",
      tags: ["calc3", "optimization", "lagrange"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-double-integrals",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Double integrals",
      name: "Double Integrals",
      order: 19,
      useItWhen: "you add values over an area",
      looksLike: "double integral over a region R",
      doThis: "set the bounds and integrate twice",
      thinkOfItAs: "adding little tiles over a region",
      watchOutFor: "using wrong region bounds",
      rememberThis: "double integral means sum over area",
      quickExample: {
        problem: "What does a double integral accumulate over?",
        move: "A 2D region.",
      },
      typicalProblemShapes: [
        "Area regions in the xy-plane",
        "Average value or mass over a region",
      ],
      miniDrill: [
        { prompt: "How many integrations happen?", answer: "Two." },
        { prompt: "What kind of region is used?", answer: "A 2D region." },
      ],
      memoryHook: "Tiles over a region.",
      tags: ["calc3", "double-integrals", "area"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-iterated-integrals",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Iterated integrals",
      name: "Iterated Integrals",
      order: 20,
      useItWhen: "a double integral is written as one inside another",
      looksLike: "integral of integral f(x,y) dy dx",
      doThis: "read inside bounds first, outside bounds second",
      thinkOfItAs: "one direction at a time",
      watchOutFor: "mixing up which bounds go with which variable",
      rememberThis: "inside bounds match inside variable",
      quickExample: {
        problem: "Which bounds belong to dy in an iterated integral?",
        move: "The inner pair.",
      },
      typicalProblemShapes: [
        "Nested integral notation",
        "Changing integration order questions",
      ],
      miniDrill: [
        { prompt: "Which variable goes first: inner or outer?", answer: "Inner." },
        { prompt: "Do bounds attach to the variable right beside them?", answer: "Yes." },
      ],
      memoryHook: "Read from the inside out.",
      tags: ["calc3", "double-integrals", "iterated"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-changing-order",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Changing order of integration",
      name: "Change the Order",
      order: 21,
      useItWhen: "the current iterated integral is ugly",
      looksLike: "dy dx becomes dx dy",
      doThis: "redraw the region and write new bounds",
      thinkOfItAs: "same region, different slicing",
      watchOutFor: "flipping the bounds without redrawing",
      rememberThis: "draw first, rewrite second",
      quickExample: {
        problem: "How do you safely change the order?",
        move: "Sketch the region first.",
      },
      typicalProblemShapes: [
        "Nested integrals with awkward inner antiderivative",
        "Region given by curves in the plane",
      ],
      miniDrill: [
        { prompt: "First move when changing order?", answer: "Draw the region." },
        { prompt: "Does the region change?", answer: "No." },
      ],
      memoryHook: "Same region, new slices.",
      tags: ["calc3", "double-integrals", "change-order"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-polar-double-integrals",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Double integrals in polar coordinates",
      name: "Polar Double Integrals",
      order: 22,
      useItWhen: "the region is circular or radial",
      looksLike: "disks, rings, sectors, x^2 + y^2",
      doThis: "switch to r and theta and remember the extra r",
      thinkOfItAs: "circles want circular coordinates",
      watchOutFor: "forgetting the extra r factor",
      rememberThis: "polar double integral needs an extra r",
      quickExample: {
        problem: "What extra factor appears in polar double integrals?",
        move: "r.",
      },
      typicalProblemShapes: [
        "Circular regions",
        "Integrands with x^2 + y^2 or round symmetry",
      ],
      miniDrill: [
        { prompt: "What coordinate change is used?", answer: "x = r cos theta, y = r sin theta." },
        { prompt: "What extra factor must appear?", answer: "r." },
      ],
      memoryHook: "Round region? Go polar and add r.",
      tags: ["calc3", "double-integrals", "polar"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-triple-integrals",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Triple integrals",
      name: "Triple Integrals",
      order: 23,
      useItWhen: "you add values over a 3D solid",
      looksLike: "triple integral over a solid E",
      doThis: "set the solid bounds and integrate three times",
      thinkOfItAs: "stacking tiny boxes in a volume",
      watchOutFor: "using area-style bounds on a 3D region",
      rememberThis: "triple integrals sum over volume",
      quickExample: {
        problem: "What kind of region does a triple integral use?",
        move: "A 3D solid region.",
      },
      typicalProblemShapes: [
        "Mass or volume over a solid",
        "Three nested integrals",
      ],
      miniDrill: [
        { prompt: "How many integrals are nested here?", answer: "Three." },
        { prompt: "Does this cover area or volume?", answer: "Volume." },
      ],
      memoryHook: "Triple integral = little boxes in space.",
      tags: ["calc3", "triple-integrals", "volume"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-cylindrical-coordinates",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Cylindrical coordinates",
      name: "Cylindrical Coordinates",
      order: 24,
      useItWhen: "a 3D solid has circular symmetry around the z-axis",
      looksLike: "x^2 + y^2 with z still separate",
      doThis: "use polar in the xy-part and keep z as z",
      thinkOfItAs: "polar plus height",
      watchOutFor: "forgetting the Jacobian factor r",
      rememberThis: "cylindrical = polar with z",
      quickExample: {
        problem: "When is cylindrical better than rectangular?",
        move: "When the solid is round around the z-axis.",
      },
      typicalProblemShapes: [
        "Cylinders and tubes",
        "Integrands with x^2 + y^2",
      ],
      miniDrill: [
        { prompt: "What stays unchanged in cylindrical coordinates?", answer: "z." },
        { prompt: "What extra factor still appears?", answer: "r." },
      ],
      memoryHook: "Polar downstairs, z upstairs.",
      tags: ["calc3", "coordinates", "cylindrical"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-spherical-coordinates",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Spherical coordinates",
      name: "Spherical Coordinates",
      order: 25,
      useItWhen: "the solid is ball-shaped or sphere-friendly",
      looksLike: "spheres, cones, rho^2 terms",
      doThis: "switch to rho, theta, phi and include the full Jacobian",
      thinkOfItAs: "3D polar coordinates",
      watchOutFor: "mixing up phi and theta or forgetting the sine factor",
      rememberThis: "sphere problems like spherical coordinates",
      quickExample: {
        problem: "What kind of solid usually wants spherical coordinates?",
        move: "A sphere or spherical shell.",
      },
      typicalProblemShapes: [
        "Balls, shells, cones with spherical symmetry",
        "Integrands in x^2 + y^2 + z^2",
      ],
      miniDrill: [
        { prompt: "What extra trig factor appears in the Jacobian?", answer: "sin phi." },
        { prompt: "Best coordinates for a sphere?", answer: "Spherical." },
      ],
      memoryHook: "Sphere shape? Go spherical.",
      tags: ["calc3", "coordinates", "spherical"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-change-of-variables",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Change of variables",
      name: "Change of Variables",
      order: 26,
      useItWhen: "a region or integrand gets cleaner in new variables",
      looksLike: "u-v substitution for double integrals",
      doThis: "rewrite the region and multiply by the Jacobian",
      thinkOfItAs: "switching maps before you compute",
      watchOutFor: "changing variables but not the area or volume factor",
      rememberThis: "new variables need the Jacobian",
      quickExample: {
        problem: "What must change besides the formula?", 
        move: "The region and the Jacobian factor.",
      },
      typicalProblemShapes: [
        "Tilted or stretched regions",
        "Custom substitutions in double integrals",
      ],
      miniDrill: [
        { prompt: "What matrix-like factor shows up here?", answer: "The Jacobian." },
        { prompt: "Do the bounds stay the same?", answer: "No." },
      ],
      memoryHook: "New variables mean new bounds and Jacobian.",
      tags: ["calc3", "double-integrals", "jacobian"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-vector-fields",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Vector fields",
      name: "Vector Fields",
      order: 27,
      useItWhen: "every point in space gets its own vector",
      looksLike: "F(x, y) = <P, Q> or F(x, y, z) = <P, Q, R>",
      doThis: "read the field as an arrow attached to every point",
      thinkOfItAs: "a wind map",
      watchOutFor: "treating a vector field like a scalar function",
      rememberThis: "vector field = arrow at every point",
      quickExample: {
        problem: "What does a vector field assign to each point?",
        move: "A vector.",
      },
      typicalProblemShapes: [
        "Flow, force, or velocity field pictures",
        "Arrow maps in the plane or space",
      ],
      miniDrill: [
        { prompt: "Does a vector field output a number or a vector?", answer: "A vector." },
        { prompt: "What common picture matches vector fields?", answer: "A wind map." },
      ],
      memoryHook: "A vector field is a map of arrows.",
      tags: ["calc3", "vector-calculus", "vector-fields"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-line-integrals",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Line integrals",
      name: "Line Integrals",
      order: 28,
      useItWhen: "you add a field along a curve",
      looksLike: "integral over C",
      doThis: "parametrize the curve, then integrate along the path",
      thinkOfItAs: "adding up work along a trip",
      watchOutFor: "forgetting the path matters",
      rememberThis: "line integrals accumulate along curves",
      quickExample: {
        problem: "What extra ingredient do you need for a line integral?",
        move: "A path or parametrization.",
      },
      typicalProblemShapes: [
        "Work done by a force field",
        "Integrals over paths C",
      ],
      miniDrill: [
        { prompt: "Do line integrals happen over regions or curves?", answer: "Curves." },
        { prompt: "What often starts the setup?", answer: "A parametrization." },
      ],
      memoryHook: "Line integrals ride along a path.",
      tags: ["calc3", "line-integrals", "work"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-conservative-fields",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Conservative vector fields",
      name: "Conservative Fields",
      order: 29,
      useItWhen: "you want path independence or an easy line integral",
      looksLike: "F = grad f",
      doThis: "find a potential function if the field is conservative",
      thinkOfItAs: "a field that comes from one hidden scalar function",
      watchOutFor: "assuming every field is conservative",
      rememberThis: "conservative means gradient field",
      quickExample: {
        problem: "Why are conservative fields nice?",
        move: "Line integrals get much easier.",
      },
      typicalProblemShapes: [
        "Potential function problems",
        "Path independence questions",
      ],
      miniDrill: [
        { prompt: "What hidden function are you looking for?", answer: "A potential function." },
        { prompt: "What does path independence usually suggest?", answer: "Conservative field." },
      ],
      memoryHook: "Find the potential, simplify the path work.",
      tags: ["calc3", "vector-calculus", "conservative-fields"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-ftc-line-integrals",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Fundamental theorem for line integrals",
      name: "FTC for Line Integrals",
      order: 30,
      useItWhen: "the field is conservative",
      looksLike: "integral of grad f dot dr",
      doThis: "use the potential at the endpoint minus the start point",
      thinkOfItAs: "top minus bottom for paths",
      watchOutFor: "using it on a field that is not conservative",
      rememberThis: "potential at end minus start",
      quickExample: {
        problem: "How do you evaluate a conservative field line integral fast?",
        move: "Potential at final point minus initial point.",
      },
      typicalProblemShapes: [
        "Given potential function f",
        "Conservative field with start and end points",
      ],
      miniDrill: [
        { prompt: "Does the path matter in this theorem?", answer: "No, not once the field is conservative." },
        { prompt: "What two points matter?", answer: "Start and end." },
      ],
      memoryHook: "Start-end beats full path.",
      tags: ["calc3", "line-integrals", "ftc"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-greens-theorem",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Green's theorem",
      name: "Green's Theorem",
      order: 31,
      useItWhen: "a line integral around a closed plane curve should become a double integral",
      looksLike: "closed curve C around region R in the plane",
      doThis: "swap boundary work for area work",
      thinkOfItAs: "edge information turning into region information",
      watchOutFor: "forgetting the curve must be closed and oriented right",
      rememberThis: "closed curve in the plane can become a double integral",
      quickExample: {
        problem: "When is Green's Theorem in play?",
        move: "Closed curve, plane region, line integral around the boundary.",
      },
      typicalProblemShapes: [
        "Counterclockwise closed curves in 2D",
        "Line integrals that look easier as double integrals",
      ],
      miniDrill: [
        { prompt: "Does Green's theorem live in 2D or 3D?", answer: "2D." },
        { prompt: "Does the curve need to be closed?", answer: "Yes." },
      ],
      memoryHook: "Closed plane loop? Think Green.",
      tags: ["calc3", "greens-theorem", "vector-calculus"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-surface-integrals",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Surface integrals",
      name: "Surface Integrals",
      order: 32,
      useItWhen: "you add values across a surface",
      looksLike: "double integral over a surface S",
      doThis: "parametrize the surface or use a graph formula",
      thinkOfItAs: "double integrals lifted onto curved sheets",
      watchOutFor: "treating the surface like a flat region",
      rememberThis: "surface integrals spread over a surface, not a plane",
      quickExample: {
        problem: "What kind of object do you integrate over here?",
        move: "A surface.",
      },
      typicalProblemShapes: [
        "Scalar field over a surface",
        "Curved sheet area accumulation",
      ],
      miniDrill: [
        { prompt: "Does a surface integral use a flat region directly?", answer: "No." },
        { prompt: "Do you often parametrize the surface?", answer: "Yes." },
      ],
      memoryHook: "Same idea as double integrals, but on a sheet.",
      tags: ["calc3", "surface-integrals", "vector-calculus"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-flux",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Flux",
      name: "Flux",
      order: 33,
      useItWhen: "you want how much field passes through a surface",
      looksLike: "F dot n over a surface",
      doThis: "use the normal direction and measure through-flow",
      thinkOfItAs: "how much wind passes through a net",
      watchOutFor: "using the wrong normal orientation",
      rememberThis: "flux measures through, not along",
      quickExample: {
        problem: "What does positive flux usually mean?",
        move: "Net flow through the surface in the chosen normal direction.",
      },
      typicalProblemShapes: [
        "Flow through a surface",
        "Normal vector orientation questions",
      ],
      miniDrill: [
        { prompt: "Does flux use tangent or normal direction?", answer: "Normal direction." },
        { prompt: "Can orientation change the sign?", answer: "Yes." },
      ],
      memoryHook: "Flux is through-flow.",
      tags: ["calc3", "flux", "surface-integrals"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-divergence-and-curl",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Divergence and curl",
      name: "Divergence and Curl",
      order: 34,
      useItWhen: "you need local spread-out or local spin of a field",
      looksLike: "div F and curl F",
      doThis: "read divergence as source/sink and curl as rotation",
      thinkOfItAs: "spread versus spin",
      watchOutFor: "mixing up what each one measures",
      rememberThis: "divergence spreads, curl spins",
      quickExample: {
        problem: "What does curl describe?",
        move: "Local rotation.",
      },
      typicalProblemShapes: [
        "Field behavior at one point",
        "Tests before using big theorems",
      ],
      miniDrill: [
        { prompt: "Which one measures spin?", answer: "Curl." },
        { prompt: "Which one measures source or sink behavior?", answer: "Divergence." },
      ],
      memoryHook: "Diverge = spread. Curl = spin.",
      tags: ["calc3", "divergence", "curl"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-divergence-theorem",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Divergence theorem",
      name: "Divergence Theorem",
      order: 35,
      useItWhen: "closed-surface flux should become a triple integral",
      looksLike: "flux across a closed surface",
      doThis: "swap surface flux for triple integral of divergence",
      thinkOfItAs: "skin flow becoming inside spread",
      watchOutFor: "using it on an open surface",
      rememberThis: "closed surface flux can become volume integral",
      quickExample: {
        problem: "What does the theorem trade?", 
        move: "Closed-surface flux for a triple integral inside.",
      },
      typicalProblemShapes: [
        "Closed surfaces like spheres or boxes",
        "Flux problems easier from the inside",
      ],
      miniDrill: [
        { prompt: "Does the surface need to be closed?", answer: "Yes." },
        { prompt: "What shows up inside the triple integral?", answer: "Divergence." },
      ],
      memoryHook: "Closed skin? Move inside with divergence.",
      tags: ["calc3", "divergence-theorem", "flux"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-stokes-theorem",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Stokes' theorem",
      name: "Stokes' Theorem",
      order: 36,
      useItWhen: "a line integral around a space curve should become a surface integral",
      looksLike: "boundary curve of a surface in 3D",
      doThis: "swap the boundary line integral for surface integral of curl",
      thinkOfItAs: "3D Green's Theorem",
      watchOutFor: "mismatching the boundary orientation and surface normal",
      rememberThis: "boundary work can become curl through the surface",
      quickExample: {
        problem: "What theorem turns a boundary line integral into a surface integral of curl?",
        move: "Stokes' Theorem.",
      },
      typicalProblemShapes: [
        "Closed space curve bounding a surface",
        "Line integrals that are easier as surface problems",
      ],
      miniDrill: [
        { prompt: "What field quantity appears inside the surface integral?", answer: "Curl." },
        { prompt: "What common theorem is this like in 2D?", answer: "Green's Theorem." },
      ],
      memoryHook: "Stokes is Green in 3D.",
      tags: ["calc3", "stokes-theorem", "curl"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-vector-derivatives-integrals",
      chapter: "Chapter 13: Vector Functions",
      unit: "Vector Functions",
      topic: "Derivatives and integrals of vector functions",
      name: "Vector Derivatives / Integrals",
      order: 37,
      useItWhen: "a space curve is written as a vector and you need motion data",
      looksLike: "r-prime(t), integral of r(t)",
      doThis: "differentiate or integrate component by component",
      thinkOfItAs: "same rule, three lanes",
      watchOutFor: "trying to combine components before differentiating",
      rememberThis: "do each component on its own",
      quickExample: {
        problem: "How do you integrate <f,g,h>?",
        move: "Integrate each component separately.",
      },
      typicalProblemShapes: [
        "Position, velocity, acceleration in vector form",
        "Space-curve derivative questions",
      ],
      miniDrill: [
        { prompt: "What is the derivative of a vector function made from?", answer: "Derivatives of each component." },
        { prompt: "What appears after integrating a vector function?", answer: "A constant vector." },
      ],
      memoryHook: "Same move, component by component.",
      tags: ["calc3", "vector-functions", "derivatives"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-motion-in-space",
      chapter: "Chapter 13: Vector Functions",
      unit: "Vector Functions",
      topic: "Motion in space",
      name: "Motion in Space",
      order: 38,
      useItWhen: "a particle moves on a space curve",
      looksLike: "position, velocity, acceleration vectors",
      doThis: "differentiate position for velocity and again for acceleration",
      thinkOfItAs: "Calc 1 motion with 3D arrows",
      watchOutFor: "mixing speed with velocity",
      rememberThis: "velocity is vector, speed is its length",
      quickExample: {
        problem: "How do you get speed from velocity?",
        move: "Take the magnitude of the velocity vector.",
      },
      typicalProblemShapes: [
        "Particle motion in three dimensions",
        "Position to velocity to acceleration chains",
      ],
      miniDrill: [
        { prompt: "Is speed a vector?", answer: "No. It is a scalar." },
        { prompt: "How do you get acceleration?", answer: "Differentiate velocity." },
      ],
      memoryHook: "Velocity points. Speed just measures.",
      tags: ["calc3", "motion", "vector-functions"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc3-double-integral-applications",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Applications of double integrals",
      name: "Double Integral Applications",
      order: 39,
      useItWhen: "you need mass, average value, or totals across a region",
      looksLike: "density over a 2D region",
      doThis: "integrate the right quantity over the region",
      thinkOfItAs: "area totals with extra meaning",
      watchOutFor: "using area alone when density is not 1",
      rememberThis: "same double integral, different interpretation",
      quickExample: {
        problem: "How do you find mass from density over a region?",
        move: "Double integrate the density.",
      },
      typicalProblemShapes: [
        "Mass of a lamina",
        "Average value over a region",
      ],
      miniDrill: [
        { prompt: "What do you integrate for mass?", answer: "Density." },
        { prompt: "Can double integrals find averages too?", answer: "Yes." },
      ],
      memoryHook: "Change the integrand, change the meaning.",
      tags: ["calc3", "double-integrals", "applications"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-parametric-surfaces",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Parametric surfaces and their areas",
      name: "Parametric Surfaces",
      order: 40,
      useItWhen: "a surface is easier from parameters than from z = f(x,y)",
      looksLike: "r(u,v)",
      doThis: "build the surface from two parameters and use the cross-product area factor",
      thinkOfItAs: "a sheet woven by two sliders",
      watchOutFor: "forgetting the cross-product magnitude in the area piece",
      rememberThis: "two parameters make the surface patch",
      quickExample: {
        problem: "What area factor comes from a parametric surface?",
        move: "The magnitude of r_u cross r_v.",
      },
      typicalProblemShapes: [
        "Surfaces written as vectors in u and v",
        "Surface area from a parametrization",
      ],
      miniDrill: [
        { prompt: "How many parameters drive a surface patch?", answer: "Two." },
        { prompt: "What vector product gives the area factor?", answer: "r_u cross r_v." },
      ],
      memoryHook: "Surface patch = two parameters plus a cross product.",
      tags: ["calc3", "surfaces", "parametric-surfaces"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-space-curve-arc-length",
      chapter: "Chapter 13: Vector Functions",
      unit: "Vector Functions",
      topic: "Arc length of space curves",
      name: "Space Curve Arc Length",
      order: 41,
      useItWhen: "you need the actual length of a 3D path",
      looksLike: "r(t) on an interval from a to b",
      doThis: "integrate the magnitude of r-prime of t",
      thinkOfItAs: "3D distance added up along the path",
      watchOutFor: "forgetting the speed magnitude inside the integral",
      rememberThis: "path length comes from speed",
      quickExample: {
        problem: "What goes inside the arc-length integral for r(t)?",
        move: "The magnitude of r-prime(t).",
      },
      typicalProblemShapes: [
        "Length of a particle path in space",
        "A vector-valued curve with time bounds",
      ],
      miniDrill: [
        {
          prompt: "Does arc length use r-prime or r-double-prime?",
          answer: "r-prime.",
        },
        {
          prompt: "Do you integrate the vector or its magnitude?",
          answer: "Its magnitude.",
        },
      ],
      memoryHook: "Space curve length = integrate speed.",
      tags: ["calc3", "vector-functions", "arc-length"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc3-surface-area-double-integrals",
      chapter: "Chapter 15: Multiple Integrals",
      unit: "Multiple Integrals",
      topic: "Surface area",
      name: "Surface Area with Double Integrals",
      order: 42,
      useItWhen: "a surface z = f(x,y) needs actual skin area",
      looksLike: "find the area of a surface over a region",
      doThis: "use the surface-area root factor over the base region",
      thinkOfItAs: "flat region below, tilted skin above",
      watchOutFor: "forgetting the 1 plus partials squared under the root",
      rememberThis: "surface area adds a root factor to dA",
      quickExample: {
        problem: "What derivatives appear in the surface-area factor?",
        move: "The partials with respect to x and y.",
      },
      typicalProblemShapes: [
        "Surface area for z = f(x,y)",
        "A region in the xy-plane paired with a surface above it",
      ],
      miniDrill: [
        {
          prompt: "Does the base region live in the xy-plane?",
          answer: "Yes.",
        },
        {
          prompt: "What warning sign sits in the formula?",
          answer: "The square-root factor with the partial derivatives.",
        },
      ],
      memoryHook: "Surface area = dA with a tilt factor.",
      tags: ["calc3", "multiple-integrals", "surface-area"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc3-summary-theorems",
      chapter: "Chapter 16: Vector Calculus",
      unit: "Vector Calculus",
      topic: "Summary of the big vector calculus theorems",
      name: "Vector Calculus Big Picture",
      order: 43,
      useItWhen: "you keep mixing up Green, Stokes, divergence, and line-integral FTC",
      looksLike: "different integral theorems with boundaries, surfaces, or regions",
      doThis: "match the theorem to the object: path, surface, or volume",
      thinkOfItAs: "the same idea moving through 1D, 2D, and 3D",
      watchOutFor: "using the right theorem on the wrong geometric object",
      rememberThis: "boundary tells you the theorem",
      quickExample: {
        problem: "If the problem has a volume and a flux through its boundary, what do you think of?",
        move: "The Divergence Theorem.",
      },
      typicalProblemShapes: [
        "Recognition questions about which theorem fits",
        "Problems built around paths, surfaces, or closed volumes",
      ],
      miniDrill: [
        {
          prompt: "Closed curve in the plane usually points toward what theorem?",
          answer: "Green's Theorem.",
        },
        {
          prompt: "Closed surface around a volume points toward what theorem?",
          answer: "The Divergence Theorem.",
        },
      ],
      memoryHook: "Path, surface, volume: match the theorem to the shape.",
      tags: ["calc3", "vector-calculus", "theorems", "recognition"],
      difficulty: "Standard",
    }),
  ],
};
