import type { BubbleCard, CourseContent } from "@/content/schema";

function makeCalcCard(
  card: Omit<BubbleCard, "subject" | "course" | "courseCode">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Single Variable Calculus 2",
    courseCode: "MATH 2B",
    ...card,
  };
}

export const calcTwoCourse: CourseContent = {
  id: "calc-2",
  subject: "Mathematics",
  title: "Single Variable Calculus 2",
  institution: "UCI",
  courseCodes: ["MATH 2B"],
  aliases: ["Calculus II"],
  shortDescription:
    "Integration tricks, polar and parametric ideas, and single-variable series recognition.",
  units: [
    "Inverse, Exponential, and Logarithmic Functions",
    "Integration Techniques",
    "Applications & Curves",
    "Differential Equations",
    "Sequences & Series",
  ],
  chapters: [
    "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
    "Chapter 7: Techniques of Integration",
    "Chapter 8: Further Applications of Integration",
    "Chapter 9: Differential Equations",
    "Chapter 10: Parametric Equations and Polar Coordinates",
    "Chapter 11: Sequences, Series, and Power Series",
  ],
  cards: [
    makeCalcCard({
      id: "calc2-integration-by-parts",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Integration by parts",
      name: "Integration by Parts",
      order: 1,
      useItWhen: "a product is inside the integral",
      looksLike: "x e^x, x sin x, x ln x",
      doThis: "pick u and dv, then use uv minus integral v du",
      thinkOfItAs: "product rule backward",
      watchOutFor: "choosing u so the new integral gets worse",
      rememberThis: "pick u to simplify",
      quickExample: {
        problem: "Integral of x e^x dx",
        move: "Take u = x and dv = e^x dx.",
      },
      typicalProblemShapes: [
        "A polynomial times trig, exponential, or log",
        "An integral where one factor gets simpler when differentiated",
      ],
      miniDrill: [
        { prompt: "What formula runs this method?", answer: "uv minus integral v du." },
        { prompt: "For x ln x, what is the natural u?", answer: "ln x." },
      ],
      memoryHook: "Product inside? Think product rule backward.",
      tags: ["calc2", "integration", "integration-by-parts"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-trig-integrals",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Trig integrals",
      name: "Trig Integrals",
      order: 2,
      useItWhen: "the integral is built from powers of sin, cos, sec, or tan",
      looksLike: "sin^3 x cos^2 x or sec^3 x tan x",
      doThis: "look for the odd power or the sec-tan pair and split smartly",
      thinkOfItAs: "pattern matching with trig costumes",
      watchOutFor: "using one rule for every trig mix",
      rememberThis: "odd power or sec-tan clue first",
      quickExample: {
        problem: "Integral of sin^3 x cos^2 x dx",
        move: "Save one sin x and turn the rest into cos pieces.",
      },
      typicalProblemShapes: [
        "Powers of sine and cosine together",
        "Secant and tangent powers mixed",
      ],
      miniDrill: [
        { prompt: "Odd power of sine present. Save one what?", answer: "Save one sine factor." },
        { prompt: "sec^3 x tan x usually suggests what?", answer: "Keep sec x tan x together." },
      ],
      memoryHook: "Trig powers are pattern games.",
      tags: ["calc2", "integration", "trig-integrals"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-trig-substitution",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Trig substitution",
      name: "Trig Substitution",
      order: 3,
      useItWhen: "a square root has a^2 - x^2, a^2 + x^2, or x^2 - a^2",
      looksLike: "sqrt(9 - x^2), sqrt(x^2 + 16), sqrt(x^2 - 25)",
      doThis: "match the root pattern to sin, tan, or sec substitution",
      thinkOfItAs: "using a trig identity to clean the root",
      watchOutFor: "picking the wrong trig match",
      rememberThis: "root pattern chooses the trig",
      quickExample: {
        problem: "Integral with sqrt(9 - x^2)",
        move: "Use x = 3 sin theta.",
      },
      typicalProblemShapes: [
        "Square roots built from quadratic forms",
        "A root that does not simplify by regular u-sub",
      ],
      miniDrill: [
        { prompt: "a^2 - x^2 matches which trig?", answer: "Sine." },
        { prompt: "x^2 + a^2 matches which trig?", answer: "Tangent." },
      ],
      memoryHook: "See the root, choose the trig.",
      tags: ["calc2", "integration", "trig-substitution"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-partial-fractions",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Partial fractions",
      name: "Partial Fractions",
      order: 4,
      useItWhen: "you have a rational function ready to break apart",
      looksLike: "(2x + 3)/(x^2 - x - 2)",
      doThis: "factor the denominator, split the fraction, solve for constants",
      thinkOfItAs: "turning one ugly fraction into easy ones",
      watchOutFor: "forgetting to factor first or doing it on an improper fraction",
      rememberThis: "factor, split, solve, integrate",
      quickExample: {
        problem: "Integral of (2x + 3)/(x^2 - x - 2) dx",
        move: "Factor the bottom before splitting.",
      },
      typicalProblemShapes: [
        "A rational function with factorable denominator",
        "Fractions that look harder to integrate as one piece",
      ],
      miniDrill: [
        { prompt: "What do you check before partial fractions?", answer: "Top degree must be smaller than bottom degree." },
        { prompt: "First move on x^2 - x - 2?", answer: "Factor it." },
      ],
      memoryHook: "One fraction, many easier fractions.",
      tags: ["calc2", "integration", "partial-fractions"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-improper-integrals",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Improper integrals",
      name: "Improper Integrals",
      order: 5,
      useItWhen: "a bound is infinite or the integrand blows up",
      looksLike: "integral to infinity or integral with a vertical asymptote",
      doThis: "replace the bad spot with a limit",
      thinkOfItAs: "a regular integral with a warning label",
      watchOutFor: "plugging the bad bound in directly",
      rememberThis: "bad bound means limit first",
      quickExample: {
        problem: "Integral from 1 to infinity of 1/x^2 dx",
        move: "Turn the infinity into a limit.",
      },
      typicalProblemShapes: [
        "An upper or lower bound is infinity",
        "The function is undefined somewhere in the interval",
      ],
      miniDrill: [
        { prompt: "What replaces infinity in the setup?", answer: "A limit." },
        { prompt: "Can an improper integral diverge?", answer: "Yes." },
      ],
      memoryHook: "Infinity or blow-up means limits.",
      tags: ["calc2", "integration", "improper-integrals"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-numerical-integration",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Numerical integration",
      name: "Numerical Integration",
      order: 6,
      useItWhen: "you need an estimate instead of a clean antiderivative",
      looksLike: "Trapezoidal Rule or Simpson's Rule",
      doThis: "build equal subintervals, then apply the formula",
      thinkOfItAs: "estimating area with simple pieces",
      watchOutFor: "mixing up endpoint weights",
      rememberThis: "estimate with a pattern, not guesswork",
      quickExample: {
        problem: "Use trapezoids to estimate an integral.",
        move: "Find delta x, list points, apply the weight pattern.",
      },
      typicalProblemShapes: [
        "A table of values with no easy antiderivative",
        "Prompts naming trapezoidal or Simpson's Rule",
      ],
      miniDrill: [
        { prompt: "Do endpoints get counted once or twice in trapezoidal rule?", answer: "Once." },
        { prompt: "Simpson's Rule needs what kind of subinterval count?", answer: "An even number." },
      ],
      memoryHook: "Use the weight pattern, not a rough eyeball.",
      tags: ["calc2", "integration", "numerical"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-arc-length",
      chapter: "Chapter 8: Further Applications of Integration",
      unit: "Applications & Curves",
      topic: "Arc length",
      name: "Arc Length",
      order: 7,
      useItWhen: "you need how long a curve really is",
      looksLike: "find the length of y = f(x) from a to b",
      doThis: "use the arc length formula and simplify before integrating",
      thinkOfItAs: "measuring the bend, not the horizontal distance",
      watchOutFor: "forgetting the square root piece",
      rememberThis: "length needs the root formula",
      quickExample: {
        problem: "Find the arc length of a curve on an interval.",
        move: "Start with 1 + (y-prime)^2 under the root.",
      },
      typicalProblemShapes: [
        "A smooth curve and an interval",
        "Questions about actual path length",
      ],
      miniDrill: [
        { prompt: "What derivative shows up in the x-formula?", answer: "y-prime." },
        { prompt: "Does arc length use a square root?", answer: "Yes." },
      ],
      memoryHook: "Curved length means root formula.",
      tags: ["calc2", "applications", "arc-length"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-surface-area",
      chapter: "Chapter 8: Further Applications of Integration",
      unit: "Applications & Curves",
      topic: "Surface area of revolution",
      name: "Surface Area of Revolution",
      order: 8,
      useItWhen: "a curve spins around an axis and you need the skin area",
      looksLike: "surface area about the x-axis or y-axis",
      doThis: "radius times arc-length piece, then integrate",
      thinkOfItAs: "wrapping paper around a spun curve",
      watchOutFor: "using the wrong radius",
      rememberThis: "surface area is spin radius times length piece",
      quickExample: {
        problem: "Rotate y = f(x) around the x-axis.",
        move: "Use radius y and the arc-length factor.",
      },
      typicalProblemShapes: [
        "Rotate a curve about an axis",
        "A problem asking for the outside skin, not volume",
      ],
      miniDrill: [
        { prompt: "For rotation about the x-axis, what is the radius?", answer: "y." },
        { prompt: "Does surface area reuse the arc-length root?", answer: "Yes." },
      ],
      memoryHook: "Surface area = spin radius times length factor.",
      tags: ["calc2", "applications", "surface-area"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-parametric-curves",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Parametric curves",
      name: "Parametric Curves",
      order: 9,
      useItWhen: "x and y are both given in terms of t",
      looksLike: "x = f(t), y = g(t)",
      doThis: "treat t like the driver and track the path it makes",
      thinkOfItAs: "one hidden knob controlling both coordinates",
      watchOutFor: "forgetting the curve can trace backward or repeat",
      rememberThis: "t moves both x and y",
      quickExample: {
        problem: "x = cos t, y = sin t",
        move: "Read it as a curve traced by time.",
      },
      typicalProblemShapes: [
        "Separate formulas for x and y",
        "A particle tracing a path over time",
      ],
      miniDrill: [
        { prompt: "What variable controls both x and y?", answer: "t." },
        { prompt: "Can the same parametric curve trace twice?", answer: "Yes." },
      ],
      memoryHook: "One parameter drives the whole path.",
      tags: ["calc2", "parametric", "curves"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-parametric-derivatives",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Derivatives of parametric curves",
      name: "Parametric Derivative",
      order: 10,
      useItWhen: "you need dy/dx from x(t) and y(t)",
      looksLike: "x = f(t), y = g(t), find slope",
      doThis: "use dy/dt over dx/dt",
      thinkOfItAs: "change in y over change in x, both through t",
      watchOutFor: "using dy/dt as if it were dy/dx",
      rememberThis: "dy/dx = (dy/dt)/(dx/dt)",
      quickExample: {
        problem: "Find the slope of a parametric curve at t = 1.",
        move: "Differentiate x and y with respect to t first.",
      },
      typicalProblemShapes: [
        "Slope of tangent line for a parametric path",
        "Questions using t instead of x directly",
      ],
      miniDrill: [
        { prompt: "What goes in the denominator?", answer: "dx/dt." },
        { prompt: "If dx/dt = 0, what warning appears?", answer: "The slope formula breaks there." },
      ],
      memoryHook: "Slope is y-rate over x-rate.",
      tags: ["calc2", "parametric", "derivative"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-parametric-arc-length",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Arc length for parametric curves",
      name: "Parametric Arc Length",
      order: 11,
      useItWhen: "you need the length of a parametric path",
      looksLike: "x = f(t), y = g(t), find length from t = a to b",
      doThis: "use the root of (dx/dt)^2 + (dy/dt)^2",
      thinkOfItAs: "Pythagorean speed inside an integral",
      watchOutFor: "using the x-formula for ordinary curves",
      rememberThis: "parametric length uses both rates",
      quickExample: {
        problem: "Find length on a parametric interval.",
        move: "Build the root from x-rate and y-rate.",
      },
      typicalProblemShapes: [
        "Path length of a particle motion",
        "A parametric curve with time bounds",
      ],
      miniDrill: [
        { prompt: "How many derivatives go under the root?", answer: "Two: x-rate and y-rate." },
        { prompt: "Does parametric arc length integrate in x or in t?", answer: "In t." },
      ],
      memoryHook: "Both rates go under the root.",
      tags: ["calc2", "parametric", "arc-length"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-polar-coordinates",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Polar coordinates",
      name: "Polar Coordinates",
      order: 12,
      useItWhen: "a point is easier as distance and angle",
      looksLike: "r = f(theta)",
      doThis: "read r as distance from the origin and theta as direction",
      thinkOfItAs: "a graph drawn by spin and stretch",
      watchOutFor: "forgetting negative r can flip the point",
      rememberThis: "polar means radius plus angle",
      quickExample: {
        problem: "What does r = 2 cos theta describe?",
        move: "Think in terms of radius changing with angle.",
      },
      typicalProblemShapes: [
        "Rose curves, circles, limacons",
        "Equations using r and theta instead of x and y",
      ],
      miniDrill: [
        { prompt: "What does theta control?", answer: "Direction." },
        { prompt: "What does r control?", answer: "Distance from the origin." },
      ],
      memoryHook: "Angle points, radius reaches.",
      tags: ["calc2", "polar", "graphing"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-polar-area",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Area in polar coordinates",
      name: "Polar Area",
      order: 13,
      useItWhen: "you need area inside a polar curve",
      looksLike: "find area of one loop of r = f(theta)",
      doThis: "use one-half integral of r squared d theta",
      thinkOfItAs: "adding thin pizza slices",
      watchOutFor: "using the wrong theta bounds",
      rememberThis: "polar area is one-half r squared",
      quickExample: {
        problem: "Find area of one petal of a rose curve.",
        move: "Use the petal bounds, not the full circle.",
      },
      typicalProblemShapes: [
        "Area enclosed by a loop or petal",
        "Integrals written in theta instead of x",
      ],
      miniDrill: [
        { prompt: "What power hits r in the formula?", answer: "Squared." },
        { prompt: "What constant sits in front?", answer: "One-half." },
      ],
      memoryHook: "Polar area = half r squared.",
      tags: ["calc2", "polar", "area"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-polar-slope",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Slope of polar curves",
      name: "Polar Slope",
      order: 14,
      useItWhen: "you need a tangent line to a polar curve",
      looksLike: "r = f(theta), find dy/dx",
      doThis: "convert to x(theta) and y(theta), then use parametric slope",
      thinkOfItAs: "polar turning into parametric for one move",
      watchOutFor: "trying to use ordinary derivative rules on r directly",
      rememberThis: "polar slope becomes parametric slope",
      quickExample: {
        problem: "Find the tangent slope for a polar curve.",
        move: "Build x = r cos theta and y = r sin theta first.",
      },
      typicalProblemShapes: [
        "A polar curve with a tangent or horizontal/vertical slope question",
        "Slope requests in theta-form",
      ],
      miniDrill: [
        { prompt: "What do you build first from polar form?", answer: "x(theta) and y(theta)." },
        { prompt: "After that, which slope formula do you use?", answer: "dy/dt over dx/dt style." },
      ],
      memoryHook: "Polar slope is really parametric slope.",
      tags: ["calc2", "polar", "tangent"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-polar-arc-length",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Arc length in polar coordinates",
      name: "Polar Arc Length",
      order: 15,
      useItWhen: "you need the length of a polar curve",
      looksLike: "find length of r = f(theta)",
      doThis: "use the root of r squared plus (dr/dtheta) squared",
      thinkOfItAs: "polar length has its own speed formula",
      watchOutFor: "forgetting the derivative of r",
      rememberThis: "polar length needs r and r-prime",
      quickExample: {
        problem: "Find the length of a polar loop.",
        move: "Use the polar arc-length formula with theta bounds.",
      },
      typicalProblemShapes: [
        "Length of a rose, limacon, or spiral piece",
        "Polar curve with interval in theta",
      ],
      miniDrill: [
        { prompt: "What two pieces go under the root?", answer: "r squared and r-prime squared." },
        { prompt: "Does polar arc length integrate in theta?", answer: "Yes." },
      ],
      memoryHook: "Polar length uses r and r-prime.",
      tags: ["calc2", "polar", "arc-length"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-sequences",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Sequences",
      name: "Sequences",
      order: 16,
      useItWhen: "terms come one after another instead of as a continuous curve",
      looksLike: "a_n with n going to infinity",
      doThis: "ask what the terms do as n gets huge",
      thinkOfItAs: "a list with a long-run mood",
      watchOutFor: "treating a sequence like a regular function graph",
      rememberThis: "sequence means term-by-term behavior",
      quickExample: {
        problem: "Does a_n = 1/n settle somewhere?",
        move: "Yes. It heads to 0.",
      },
      typicalProblemShapes: [
        "Questions about a_n as n goes to infinity",
        "Lists of terms or explicit nth formulas",
      ],
      miniDrill: [
        { prompt: "What variable usually indexes a sequence?", answer: "n." },
        { prompt: "Can a sequence diverge?", answer: "Yes." },
      ],
      memoryHook: "A sequence is a list with a limit question.",
      tags: ["calc2", "sequences", "limits"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-sequence-limits",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Limits of sequences",
      name: "Sequence Limits",
      order: 17,
      useItWhen: "you need to know whether a sequence settles down",
      looksLike: "limit as n goes to infinity of a_n",
      doThis: "look at the dominant behavior for large n",
      thinkOfItAs: "end behavior for lists",
      watchOutFor: "checking only early terms",
      rememberThis: "big n controls the answer",
      quickExample: {
        problem: "Limit of (3n + 1)/(n + 5)",
        move: "Highest-power thinking still works.",
      },
      typicalProblemShapes: [
        "Rational expressions in n",
        "Terms built from roots, powers, or factorials",
      ],
      miniDrill: [
        { prompt: "Do first few terms guarantee the limit?", answer: "No." },
        { prompt: "What matters most for large n?", answer: "The dominant growth." },
      ],
      memoryHook: "Sequence limits are long-run term behavior.",
      tags: ["calc2", "sequences", "limits"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-series-basics",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Series basics",
      name: "Series Basics",
      order: 18,
      useItWhen: "you are adding infinitely many terms",
      looksLike: "sum a_n from n = 1 to infinity",
      doThis: "look at the partial sums, not just the terms",
      thinkOfItAs: "a running total with no final last term",
      watchOutFor: "thinking term limit alone proves convergence",
      rememberThis: "series care about sums, not single terms",
      quickExample: {
        problem: "What decides a series: terms or partial sums?",
        move: "Partial sums decide it.",
      },
      typicalProblemShapes: [
        "Sigma notation with infinity",
        "Converges or diverges questions",
      ],
      miniDrill: [
        { prompt: "Does a series use partial sums?", answer: "Yes." },
        { prompt: "If terms do not go to 0, can the series converge?", answer: "No." },
      ],
      memoryHook: "Series are about the running total.",
      tags: ["calc2", "series", "sigma"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-geometric-series",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Geometric series",
      name: "Geometric Series",
      order: 19,
      useItWhen: "every term is made by multiplying by the same ratio",
      looksLike: "a + ar + ar^2 + ...",
      doThis: "find r and check if absolute r is less than 1",
      thinkOfItAs: "same multiplier, over and over",
      watchOutFor: "forgetting the ratio test for convergence is just on r here",
      rememberThis: "absolute r less than 1 means converge",
      quickExample: {
        problem: "Series 3 + 3/2 + 3/4 + ...",
        move: "Ratio is 1/2, so it converges.",
      },
      typicalProblemShapes: [
        "A fixed multiplier between terms",
        "Powers like c(r)^n",
      ],
      miniDrill: [
        { prompt: "What is the key number in a geometric series?", answer: "The ratio r." },
        { prompt: "If r = 2, converge or diverge?", answer: "Diverge." },
      ],
      memoryHook: "Geometric series live or die by r.",
      tags: ["calc2", "series", "geometric"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-telescoping-series",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Telescoping series",
      name: "Telescoping Series",
      order: 20,
      useItWhen: "terms cancel in a chain",
      looksLike: "1/(n(n + 1)) after partial fraction splitting",
      doThis: "write out early partial sums and watch the cancellation",
      thinkOfItAs: "dominoes knocking each other out",
      watchOutFor: "trying a fancy test before checking for cancellation",
      rememberThis: "if terms cancel, write a few out",
      quickExample: {
        problem: "Series from 1/(n(n + 1))",
        move: "Split it and inspect the first few partial sums.",
      },
      typicalProblemShapes: [
        "Terms that break into neighbors like 1/n - 1/(n + 1)",
        "Lots of visible cancellation after expansion",
      ],
      miniDrill: [
        { prompt: "Best first move on a telescoping-looking series?", answer: "Write partial sums." },
        { prompt: "Do most middle terms survive?", answer: "No." },
      ],
      memoryHook: "Write it out and let the cancellation show.",
      tags: ["calc2", "series", "telescoping"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-nth-term-test",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Nth-term test",
      name: "Nth-Term Test",
      order: 21,
      useItWhen: "you want a fast divergence check",
      looksLike: "sum a_n where term limit is easy to see",
      doThis: "take the limit of a_n; if it is not 0, the series diverges",
      thinkOfItAs: "a quick bouncer at the door",
      watchOutFor: "thinking limit 0 means convergence",
      rememberThis: "not 0 means diverge; 0 means maybe",
      quickExample: {
        problem: "Sum of n/(n + 1)",
        move: "Terms go to 1, so the series diverges right away.",
      },
      typicalProblemShapes: [
        "A series with easy term limit",
        "First test before trying harder tools",
      ],
      miniDrill: [
        { prompt: "If a_n goes to 3, what happens?", answer: "The series diverges." },
        { prompt: "If a_n goes to 0, are you done?", answer: "No." },
      ],
      memoryHook: "Not zero kills the series fast.",
      tags: ["calc2", "series", "divergence-test"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-integral-test",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Integral test",
      name: "Integral Test",
      order: 22,
      useItWhen: "the terms come from a positive decreasing continuous function",
      looksLike: "sum 1/n^p or similar positive formulas",
      doThis: "integrate the matching function from 1 to infinity",
      thinkOfItAs: "letting an improper integral judge the series",
      watchOutFor: "using it when the function is not decreasing",
      rememberThis: "positive, decreasing, continuous first",
      quickExample: {
        problem: "Test sum 1/n^2",
        move: "Compare it to the improper integral of 1/x^2.",
      },
      typicalProblemShapes: [
        "Positive terms with function-like formulas",
        "Series that look close to p-series or reciprocal powers",
      ],
      miniDrill: [
        { prompt: "What three conditions should you check first?", answer: "Positive, decreasing, continuous." },
        { prompt: "What kind of integral appears?", answer: "An improper integral." },
      ],
      memoryHook: "If it acts like a nice positive function, integrate it.",
      tags: ["calc2", "series", "integral-test"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-p-series",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "P-series",
      name: "p-Series",
      order: 23,
      useItWhen: "the series looks like 1/n^p",
      looksLike: "sum 1/n^p",
      doThis: "check whether p is bigger than 1",
      thinkOfItAs: "the fastest shortcut in the room",
      watchOutFor: "mixing up the cutoff value",
      rememberThis: "p bigger than 1 converges",
      quickExample: {
        problem: "Sum 1/n^(3/2)",
        move: "p is bigger than 1, so it converges.",
      },
      typicalProblemShapes: [
        "Reciprocal powers of n",
        "Series that can be compared to 1/n^p",
      ],
      miniDrill: [
        { prompt: "What if p = 1?", answer: "Diverges." },
        { prompt: "What if p = 4?", answer: "Converges." },
      ],
      memoryHook: "p over 1 lives. p at or below 1 dies.",
      tags: ["calc2", "series", "p-series"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-comparison-test",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Comparison test",
      name: "Comparison Test",
      order: 24,
      useItWhen: "your series is messy but you can compare its size to a familiar one",
      looksLike: "positive terms you can trap above or below another series",
      doThis: "compare to something simpler that you already know",
      thinkOfItAs: "guilt by association for series",
      watchOutFor: "using the wrong comparison direction",
      rememberThis: "smaller than a convergent or bigger than a divergent",
      quickExample: {
        problem: "Compare 1/(n^2 + 1) to 1/n^2.",
        move: "Use the simpler p-series as the benchmark.",
      },
      typicalProblemShapes: [
        "Positive-term series with extra constants or lower-order terms",
        "Fractions that resemble a known p-series",
      ],
      miniDrill: [
        { prompt: "To prove convergence, compare with something bigger or smaller?", answer: "Bigger convergent benchmark." },
        { prompt: "To prove divergence, compare with something bigger or smaller?", answer: "Smaller divergent benchmark." },
      ],
      memoryHook: "Compare to a series you already trust.",
      tags: ["calc2", "series", "comparison-test"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-limit-comparison-test",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Limit comparison test",
      name: "Limit Comparison Test",
      order: 25,
      useItWhen: "two positive-term series have the same dominant shape",
      looksLike: "messy rational or root expressions in n",
      doThis: "take the limit of a_n over b_n and check for a positive finite answer",
      thinkOfItAs: "same growth, same fate",
      watchOutFor: "using a comparison series with a totally different dominant term",
      rememberThis: "positive finite ratio means same result",
      quickExample: {
        problem: "Compare n/(n^3 + 2) to 1/n^2.",
        move: "Use dominant powers and take the ratio limit.",
      },
      typicalProblemShapes: [
        "Positive terms with similar dominant behavior",
        "Rational expressions where ordinary comparison feels messy",
      ],
      miniDrill: [
        { prompt: "What kind of ratio limit do you want?", answer: "Positive and finite." },
        { prompt: "If the ratio limit is 7, what does that mean?", answer: "They converge or diverge together." },
      ],
      memoryHook: "Same dominant shape means same verdict.",
      tags: ["calc2", "series", "limit-comparison"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-alternating-series-test",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Alternating series test",
      name: "Alternating Series Test",
      order: 26,
      useItWhen: "signs flip back and forth",
      looksLike: "(-1)^n, (-1)^(n+1), or plus-minus-plus-minus",
      doThis: "check that term sizes go down to 0",
      thinkOfItAs: "a tug-of-war that settles down",
      watchOutFor: "checking the signs but not the shrinking",
      rememberThis: "alternate, decrease, hit 0",
      quickExample: {
        problem: "Sum (-1)^n / n",
        move: "Signs alternate and term sizes shrink to 0.",
      },
      typicalProblemShapes: [
        "Explicit alternating signs",
        "Series with a shrinking positive part times (-1)^n",
      ],
      miniDrill: [
        { prompt: "Do alternating terms need to shrink?", answer: "Yes." },
        { prompt: "Do terms need to go to 0?", answer: "Yes." },
      ],
      memoryHook: "Alternating alone is not enough. Terms must calm down.",
      tags: ["calc2", "series", "alternating-series"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-absolute-conditional",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Absolute and conditional convergence",
      name: "Absolute vs Conditional",
      order: 27,
      useItWhen: "an alternating series converges and you need the stronger label",
      looksLike: "test the series and then test the absolute-value version",
      doThis: "drop the signs and test again",
      thinkOfItAs: "take off the sign costume and see what remains",
      watchOutFor: "calling every convergent alternating series absolute",
      rememberThis: "absolute means it still works without the signs",
      quickExample: {
        problem: "If sum (-1)^n/n converges, what about sum 1/n?",
        move: "It diverges, so the original is only conditional.",
      },
      typicalProblemShapes: [
        "Alternating series after AST says converge",
        "Questions asking for absolute or conditional convergence",
      ],
      miniDrill: [
        { prompt: "What do you test for absolute convergence?", answer: "The series of absolute values." },
        { prompt: "If that absolute-value series diverges but the original converges, what is the label?", answer: "Conditional convergence." },
      ],
      memoryHook: "Absolute means signs do not matter.",
      tags: ["calc2", "series", "absolute-convergence"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-ratio-test",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Ratio test",
      name: "Ratio Test",
      order: 28,
      useItWhen: "factorials or powers keep showing up",
      looksLike: "n!, c^n, or both",
      doThis: "take the limit of absolute a_(n+1)/a_n",
      thinkOfItAs: "asking how each term compares to the one before it",
      watchOutFor: "forgetting absolute value",
      rememberThis: "ratio under 1 converges, over 1 diverges",
      quickExample: {
        problem: "Series with n! in the terms",
        move: "Try ratio test early.",
      },
      typicalProblemShapes: [
        "Factorials",
        "Exponential powers in n",
      ],
      miniDrill: [
        { prompt: "What if the ratio limit is 1/3?", answer: "Converges." },
        { prompt: "What if the ratio limit is 2?", answer: "Diverges." },
      ],
      memoryHook: "Factorials and powers love ratio test.",
      tags: ["calc2", "series", "ratio-test"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-root-test",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Root test",
      name: "Root Test",
      order: 29,
      useItWhen: "the nth power or nth root is built into the terms",
      looksLike: "(3n/(n+1))^n or nth roots",
      doThis: "take the nth root of absolute a_n and find the limit",
      thinkOfItAs: "peeling off the big outer power",
      watchOutFor: "using it when no nth power pattern is present",
      rememberThis: "nth powers suggest nth roots",
      quickExample: {
        problem: "Series with [(2n+1)/(3n)]^n",
        move: "Root test removes the outer power fast.",
      },
      typicalProblemShapes: [
        "Terms raised to n",
        "Nth-root structures",
      ],
      miniDrill: [
        { prompt: "What if the root-test limit is below 1?", answer: "Converges." },
        { prompt: "What if the root-test limit is above 1?", answer: "Diverges." },
      ],
      memoryHook: "Big outer n power? Use root test.",
      tags: ["calc2", "series", "root-test"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-power-series",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Power series",
      name: "Power Series",
      order: 30,
      useItWhen: "terms are built around powers of x - a",
      looksLike: "sum c_n (x - a)^n",
      doThis: "treat it like a movable geometric-style series around a center",
      thinkOfItAs: "an infinite polynomial around one point",
      watchOutFor: "forgetting the center a",
      rememberThis: "power series live around a center",
      quickExample: {
        problem: "Sum c_n (x - 2)^n",
        move: "Center is x = 2.",
      },
      typicalProblemShapes: [
        "Series with x inside the terms",
        "Expanded around x = 0 or x = a",
      ],
      miniDrill: [
        { prompt: "What is the center of sum c_n (x + 4)^n?", answer: "x = -4." },
        { prompt: "Does a power series behave the same for every x?", answer: "No." },
      ],
      memoryHook: "A power series is a polynomial with no final term.",
      tags: ["calc2", "series", "power-series"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-radius-interval",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Radius and interval of convergence",
      name: "Radius / Interval of Convergence",
      order: 31,
      useItWhen: "a power series needs its valid x-values",
      looksLike: "find where a series converges in x",
      doThis: "use ratio or root test for the radius, then check endpoints by hand",
      thinkOfItAs: "the safe zone around the center",
      watchOutFor: "forgetting endpoint checks",
      rememberThis: "radius first, endpoints last",
      quickExample: {
        problem: "Find interval of convergence of a power series.",
        move: "Get the radius, then test both ends separately.",
      },
      typicalProblemShapes: [
        "Series with x and factorial or power patterns",
        "Questions asking for radius or interval of convergence",
      ],
      miniDrill: [
        { prompt: "After ratio test gives radius, are you done?", answer: "No. Check endpoints." },
        { prompt: "Do endpoints always behave the same?", answer: "No." },
      ],
      memoryHook: "Radius gives the circle. Endpoints decide the edges.",
      tags: ["calc2", "series", "radius-of-convergence"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-taylor-polynomials",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Taylor polynomials",
      name: "Taylor Polynomial",
      order: 32,
      useItWhen: "you want a short polynomial approximation near a point",
      looksLike: "find the nth-degree Taylor polynomial about x = a",
      doThis: "use derivatives at a and build term by term",
      thinkOfItAs: "a local fake version of the function",
      watchOutFor: "using derivatives at the wrong center",
      rememberThis: "all roads go through the center a",
      quickExample: {
        problem: "Build a quadratic Taylor polynomial at x = 0.",
        move: "Use function, first derivative, and second derivative at 0.",
      },
      typicalProblemShapes: [
        "Approximation near one point",
        "Prompts asking for degree n polynomial around a",
      ],
      miniDrill: [
        { prompt: "What point controls the coefficients?", answer: "The center a." },
        { prompt: "Degree 2 means how many derivative levels?", answer: "Up to the second derivative." },
      ],
      memoryHook: "Taylor polynomials are local stand-ins.",
      tags: ["calc2", "series", "taylor-polynomial"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-taylor-series",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Taylor series",
      name: "Taylor Series",
      order: 33,
      useItWhen: "you want the infinite polynomial version near a point",
      looksLike: "sum built from derivatives at a",
      doThis: "spot the pattern in the derivatives and write the full series",
      thinkOfItAs: "Taylor polynomial with no stopping point",
      watchOutFor: "dropping the factorial",
      rememberThis: "derivatives at a build the whole series",
      quickExample: {
        problem: "Find the Taylor series for e^x at 0.",
        move: "Every derivative stays e^x, so the pattern is easy.",
      },
      typicalProblemShapes: [
        "Maclaurin or Taylor expansion requests",
        "Functions with repeating derivative patterns",
      ],
      miniDrill: [
        { prompt: "What changes between Taylor polynomial and Taylor series?", answer: "The series keeps going forever." },
        { prompt: "What sits under each term with order n?", answer: "n factorial." },
      ],
      memoryHook: "Taylor series is the all-the-way version.",
      tags: ["calc2", "series", "taylor-series"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-maclaurin-series",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Maclaurin series",
      name: "Maclaurin Series",
      order: 34,
      useItWhen: "the Taylor series is centered at 0",
      looksLike: "series around x = 0",
      doThis: "treat it like Taylor with a = 0",
      thinkOfItAs: "Taylor's zero-centered cousin",
      watchOutFor: "forgetting Maclaurin just means center 0",
      rememberThis: "Maclaurin is Taylor at 0",
      quickExample: {
        problem: "What makes a series Maclaurin?",
        move: "Its center is x = 0.",
      },
      typicalProblemShapes: [
        "sin x, cos x, e^x, 1/(1-x) around 0",
        "Prompts naming Maclaurin specifically",
      ],
      miniDrill: [
        { prompt: "What is the center of Maclaurin?", answer: "0." },
        { prompt: "Is every Maclaurin series also Taylor?", answer: "Yes." },
      ],
      memoryHook: "Maclaurin just means center at zero.",
      tags: ["calc2", "series", "maclaurin"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-common-series",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Common Maclaurin series",
      name: "Common Maclaurin Series",
      order: 35,
      useItWhen: "you want to recognize the standard big four fast",
      looksLike: "e^x, sin x, cos x, 1/(1-x)",
      doThis: "memorize the base patterns and plug them into new problems",
      thinkOfItAs: "the formula sheet you want in your head",
      watchOutFor: "mixing up the signs in sine and cosine",
      rememberThis: "know the base series cold",
      quickExample: {
        problem: "What is the Maclaurin series for e^x?",
        move: "Sum x^n over n factorial.",
      },
      typicalProblemShapes: [
        "Rewrite a function as a known series",
        "Use a base series to build a new one",
      ],
      miniDrill: [
        { prompt: "Which common series has all positive terms?", answer: "e^x." },
        { prompt: "Which common series alternates odd powers?", answer: "sin x." },
      ],
      memoryHook: "Know the big four and build from there.",
      tags: ["calc2", "series", "maclaurin", "memorization"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-inverse-functions",
      chapter: "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
      unit: "Inverse, Exponential, and Logarithmic Functions",
      topic: "Inverse functions and their derivatives",
      name: "Inverse Functions",
      order: 36,
      useItWhen: "a function needs to be undone",
      looksLike: "f and f^-1, swap x and y",
      doThis: "flip x and y, solve, then use inverse-derivative rules if needed",
      thinkOfItAs: "running the function backward",
      watchOutFor: "forgetting inverse means inputs and outputs switch jobs",
      rememberThis: "inverse undoes the original function",
      quickExample: {
        problem: "How do you start finding an inverse?",
        move: "Swap x and y.",
      },
      typicalProblemShapes: [
        "Find the inverse of a one-to-one function",
        "Differentiate an inverse function",
      ],
      miniDrill: [
        { prompt: "What is the first move for an inverse?", answer: "Swap x and y." },
        { prompt: "Does every function have an inverse function?", answer: "No. It needs to be one-to-one." },
      ],
      memoryHook: "Inverse means undo.",
      tags: ["calc2", "inverse-functions", "chapter6"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-exponential-derivatives",
      chapter: "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
      unit: "Inverse, Exponential, and Logarithmic Functions",
      topic: "Exponential functions and their derivatives",
      name: "Exponential Derivatives",
      order: 37,
      useItWhen: "the variable is in the exponent",
      looksLike: "e^x, a^x, e^(g(x))",
      doThis: "differentiate the exponential and keep the exponential",
      thinkOfItAs: "the function reproduces itself",
      watchOutFor: "forgetting chain rule on e^(g(x))",
      rememberThis: "e^x stays e^x",
      quickExample: {
        problem: "Derivative of e^(3x)?",
        move: "Keep e^(3x), then multiply by 3.",
      },
      typicalProblemShapes: [
        "Exponential growth formulas",
        "e raised to a linear or nonlinear expression",
      ],
      miniDrill: [
        { prompt: "What happens to e^x when you differentiate it?", answer: "It stays e^x." },
        { prompt: "What extra step appears in e^(x^2)?", answer: "Chain rule." },
      ],
      memoryHook: "Exponential stays exponential.",
      tags: ["calc2", "exponential", "derivatives"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-log-functions",
      chapter: "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
      unit: "Inverse, Exponential, and Logarithmic Functions",
      topic: "Logarithmic functions",
      name: "Log Functions",
      order: 38,
      useItWhen: "you need to undo an exponential or simplify products and powers",
      looksLike: "ln x, log_a x",
      doThis: "use log rules to turn multiply into add and powers into front coefficients",
      thinkOfItAs: "a formula untangler",
      watchOutFor: "treating ln(x+y) like ln x + ln y",
      rememberThis: "logs break products, not sums",
      quickExample: {
        problem: "What is ln(ab)?",
        move: "ln a + ln b.",
      },
      typicalProblemShapes: [
        "Log simplification",
        "Log equations or inverse-exponential questions",
      ],
      miniDrill: [
        { prompt: "Does ln(x + y) split nicely?", answer: "No." },
        { prompt: "What does ln(a^5) become?", answer: "5 ln a." },
      ],
      memoryHook: "Logs split products, not sums.",
      tags: ["calc2", "logs", "chapter6"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-growth-decay",
      chapter: "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
      unit: "Inverse, Exponential, and Logarithmic Functions",
      topic: "Exponential growth and decay",
      name: "Growth and Decay",
      order: 39,
      useItWhen: "a rate is proportional to the current amount",
      looksLike: "P(t) = P_0 e^(kt)",
      doThis: "read k for growth or decay and plug into the model",
      thinkOfItAs: "change that feeds on the current amount",
      watchOutFor: "mixing positive k with negative k",
      rememberThis: "positive k grows, negative k decays",
      quickExample: {
        problem: "What does a negative k mean in P_0 e^(kt)?",
        move: "Decay.",
      },
      typicalProblemShapes: [
        "Population, cooling, radioactive decay, compound growth",
        "Models with e^(kt)",
      ],
      miniDrill: [
        { prompt: "What sign of k means growth?", answer: "Positive." },
        { prompt: "What sign of k means decay?", answer: "Negative." },
      ],
      memoryHook: "k tells the story.",
      tags: ["calc2", "exponential", "growth-decay"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-inverse-trig",
      chapter: "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
      unit: "Inverse, Exponential, and Logarithmic Functions",
      topic: "Inverse trigonometric functions",
      name: "Inverse Trig Functions",
      order: 40,
      useItWhen: "you need the angle that gave a trig value",
      looksLike: "arcsin, arccos, arctan",
      doThis: "read the output as an angle and use the standard derivative patterns when needed",
      thinkOfItAs: "trig in reverse",
      watchOutFor: "forgetting inverse trig outputs are angles",
      rememberThis: "inverse trig returns angles",
      quickExample: {
        problem: "What does arctan(1) mean?",
        move: "The angle whose tangent is 1.",
      },
      typicalProblemShapes: [
        "Angle recovery from a trig ratio",
        "Derivative formulas involving inverse trig",
      ],
      miniDrill: [
        { prompt: "Does arcsin output a number or an angle?", answer: "An angle." },
        { prompt: "What does arctan do?", answer: "Undoes tangent on its principal range." },
      ],
      memoryHook: "Inverse trig gives back the angle.",
      tags: ["calc2", "inverse-trig", "chapter6"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-lhopitals-rule",
      chapter: "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
      unit: "Inverse, Exponential, and Logarithmic Functions",
      topic: "Indeterminate forms and l'Hospital's Rule",
      name: "l'Hospital's Rule",
      order: 41,
      useItWhen: "a limit gives 0/0 or infinity/infinity",
      looksLike: "fraction limits with indeterminate form",
      doThis: "differentiate top and bottom, then try the limit again",
      thinkOfItAs: "one more derivative pass to clear the stalemate",
      watchOutFor: "using it before checking the form",
      rememberThis: "0/0 or inf/inf first, then differentiate top and bottom",
      quickExample: {
        problem: "When can l'Hospital start?",
        move: "After you verify 0/0 or infinity/infinity.",
      },
      typicalProblemShapes: [
        "Hard fraction limits with matching blow-up or matching zeros",
        "Exponential-log limits after algebra cleanup",
      ],
      miniDrill: [
        { prompt: "Can you use l'Hospital on any limit?", answer: "No." },
        { prompt: "What two forms are the green light?", answer: "0/0 and infinity/infinity." },
      ],
      memoryHook: "Check the form before you differentiate.",
      tags: ["calc2", "limits", "lhopital"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-center-of-mass",
      chapter: "Chapter 8: Further Applications of Integration",
      unit: "Applications & Curves",
      topic: "Center of mass",
      name: "Center of Mass",
      order: 42,
      useItWhen: "you need the balance point of a region or wire",
      looksLike: "mass density and weighted averages",
      doThis: "find total mass, then divide moments by mass",
      thinkOfItAs: "the balancing spot",
      watchOutFor: "forgetting density changes the weighting",
      rememberThis: "moment over mass",
      quickExample: {
        problem: "What comes after total mass?",
        move: "Moments, then divide by mass.",
      },
      typicalProblemShapes: [
        "Lamina or wire balance point",
        "Density-weighted average location",
      ],
      miniDrill: [
        { prompt: "What do you divide by at the end?", answer: "Total mass." },
        { prompt: "Does density matter?", answer: "Yes." },
      ],
      memoryHook: "Balance point = moment over mass.",
      tags: ["calc2", "applications", "center-of-mass"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-hydrostatic-force",
      chapter: "Chapter 8: Further Applications of Integration",
      unit: "Applications & Curves",
      topic: "Hydrostatic force",
      name: "Hydrostatic Force",
      order: 43,
      useItWhen: "liquid pressure changes with depth",
      looksLike: "force on a plate or gate in water",
      doThis: "use pressure times thin strip area, then integrate by depth",
      thinkOfItAs: "deeper means harder push",
      watchOutFor: "using one constant pressure everywhere",
      rememberThis: "pressure grows with depth",
      quickExample: {
        problem: "What variable usually drives hydrostatic force?",
        move: "Depth.",
      },
      typicalProblemShapes: [
        "Water pushing on a vertical plate",
        "Variable pressure with depth",
      ],
      miniDrill: [
        { prompt: "Does pressure stay constant in water?", answer: "No." },
        { prompt: "What gets integrated: one strip or the whole plate at once?", answer: "Thin strips." },
      ],
      memoryHook: "Deeper strip, stronger push.",
      tags: ["calc2", "applications", "hydrostatic-force"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-probability-density",
      chapter: "Chapter 8: Further Applications of Integration",
      unit: "Applications & Curves",
      topic: "Probability density",
      name: "Probability Density",
      order: 44,
      useItWhen: "probability is given by a density function instead of separate cases",
      looksLike: "f(x) with total area 1",
      doThis: "integrate over the interval you care about",
      thinkOfItAs: "probability as area again",
      watchOutFor: "forgetting total area must be 1",
      rememberThis: "probability from a density is area",
      quickExample: {
        problem: "How do you get P(a < X < b)?",
        move: "Integrate the density from a to b.",
      },
      typicalProblemShapes: [
        "Continuous random variable",
        "Find a constant so total probability is 1",
      ],
      miniDrill: [
        { prompt: "What should the total area under a density be?", answer: "1." },
        { prompt: "How do you get probability on an interval?", answer: "Integrate on that interval." },
      ],
      memoryHook: "Probability density means area under the curve.",
      tags: ["calc2", "probability", "integration"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-direction-fields",
      chapter: "Chapter 9: Differential Equations",
      unit: "Differential Equations",
      topic: "Direction fields and Euler's Method",
      name: "Direction Fields / Euler",
      order: 45,
      useItWhen: "a differential equation is easier to read or approximate than solve exactly",
      looksLike: "dy/dx = f(x,y) with slope marks",
      doThis: "read the slope field or step forward with Euler's Method",
      thinkOfItAs: "following tiny slope arrows",
      watchOutFor: "thinking Euler gives an exact answer",
      rememberThis: "Euler walks by slope steps",
      quickExample: {
        problem: "What does a direction field show?",
        move: "Tiny slope hints at many points.",
      },
      typicalProblemShapes: [
        "Slope fields drawn in the plane",
        "Approximate y-values from an initial condition",
      ],
      miniDrill: [
        { prompt: "Is Euler exact or approximate?", answer: "Approximate." },
        { prompt: "What does a direction field show at each point?", answer: "A slope." },
      ],
      memoryHook: "Tiny slopes guide the curve.",
      tags: ["calc2", "differential-equations", "euler"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-separable-equations",
      chapter: "Chapter 9: Differential Equations",
      unit: "Differential Equations",
      topic: "Separable equations",
      name: "Separable Equations",
      order: 46,
      useItWhen: "y terms and x terms can be split apart",
      looksLike: "dy/dx = g(x)h(y)",
      doThis: "move y stuff with dy and x stuff with dx, then integrate",
      thinkOfItAs: "putting x and y on different sides of the room",
      watchOutFor: "separating terms that are not actually separable",
      rememberThis: "split, integrate, solve",
      quickExample: {
        problem: "What is the signature move in a separable equation?",
        move: "Separate variables before integrating.",
      },
      typicalProblemShapes: [
        "Products of x-only and y-only pieces",
        "Differential equations that rearrange cleanly",
      ],
      miniDrill: [
        { prompt: "What happens before integrating?", answer: "Separate the variables." },
        { prompt: "After integrating, what often appears?", answer: "A constant and maybe an initial condition." },
      ],
      memoryHook: "If x and y can split, separate first.",
      tags: ["calc2", "differential-equations", "separable"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-population-growth-models",
      chapter: "Chapter 9: Differential Equations",
      unit: "Differential Equations",
      topic: "Population growth models",
      name: "Population Growth Models",
      order: 47,
      useItWhen: "a quantity grows based on its current size",
      looksLike: "exponential growth or logistic growth",
      doThis: "identify whether the model is unlimited or capped",
      thinkOfItAs: "grow freely or grow toward a ceiling",
      watchOutFor: "mixing logistic growth with plain exponential growth",
      rememberThis: "logistic growth has a carrying capacity",
      quickExample: {
        problem: "What extra feature does logistic growth have?",
        move: "A ceiling or carrying capacity.",
      },
      typicalProblemShapes: [
        "Population changing over time",
        "Growth models with or without a cap",
      ],
      miniDrill: [
        { prompt: "Does exponential growth have a carrying capacity?", answer: "No." },
        { prompt: "Does logistic growth level off?", answer: "Yes." },
      ],
      memoryHook: "Logistic growth slows near a ceiling.",
      tags: ["calc2", "differential-equations", "logistic"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-linear-differential-equations",
      chapter: "Chapter 9: Differential Equations",
      unit: "Differential Equations",
      topic: "Linear equations",
      name: "Linear Differential Equations",
      order: 48,
      useItWhen: "a first-order differential equation is in linear form",
      looksLike: "y-prime + P(x)y = Q(x)",
      doThis: "put it in standard form, then use the integrating factor",
      thinkOfItAs: "a messy equation unlocked by one multiplier",
      watchOutFor: "forgetting to get standard form first",
      rememberThis: "linear first-order means integrating factor",
      quickExample: {
        problem: "What is the setup form for a linear first-order ODE?",
        move: "y-prime + P(x)y = Q(x).",
      },
      typicalProblemShapes: [
        "First-order equations with y and y-prime only",
        "Problems that mention integrating factor",
      ],
      miniDrill: [
        { prompt: "What comes after standard form?", answer: "Find the integrating factor." },
        { prompt: "Does this method need the equation in standard form first?", answer: "Yes." },
      ],
      memoryHook: "Standard form, then integrating factor.",
      tags: ["calc2", "differential-equations", "linear"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-hyperbolic-functions",
      chapter: "Chapter 6: Inverse, Exponential, and Logarithmic Functions",
      unit: "Inverse, Exponential, and Logarithmic Functions",
      topic: "Hyperbolic functions",
      name: "Hyperbolic Functions",
      order: 49,
      useItWhen: "sinh, cosh, or tanh shows up",
      looksLike: "sinh x, cosh x, tanh x",
      doThis: "treat them like trig cousins built from exponentials",
      thinkOfItAs: "trig-looking functions with exponential guts",
      watchOutFor: "assuming they use the exact same identities as sine and cosine",
      rememberThis: "hyperbolic functions act trig-ish but come from e^x",
      quickExample: {
        problem: "What is the derivative of sinh x?",
        move: "cosh x.",
      },
      typicalProblemShapes: [
        "A derivative or identity involving sinh or cosh",
        "A catenary or hyperbolic-substitution style setting",
      ],
      miniDrill: [
        {
          prompt: "What powers hyperbolic functions behind the scenes?",
          answer: "Exponentials.",
        },
        {
          prompt: "Does sinh x differentiate to cosh x?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Hyperbolic = trig flavor, exponential engine.",
      tags: ["calc2", "hyperbolic", "transcendentals"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-integration-strategy",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Strategy for integration",
      name: "Integration Strategy",
      order: 50,
      useItWhen: "you see an integral and do not know the first tool",
      looksLike: "a mixed expression with several possible methods",
      doThis: "scan for patterns: u-sub, parts, trig, partial fractions, or a formula",
      thinkOfItAs: "a decision tree, not a blind guess",
      watchOutFor: "forcing one favorite method on every problem",
      rememberThis: "match the pattern before you swing",
      quickExample: {
        problem: "What should you do before choosing a method?",
        move: "Read the pattern and classify the integral.",
      },
      typicalProblemShapes: [
        "Mixed expressions with products, roots, or rational pieces",
        "Homework that asks which technique should be tried first",
      ],
      miniDrill: [
        {
          prompt: "Product with one factor that simplifies when differentiated?",
          answer: "Try integration by parts.",
        },
        {
          prompt: "Inner function sitting neatly inside its derivative?",
          answer: "Try u-substitution.",
        },
      ],
      memoryHook: "Do not guess. Pattern-match the integral.",
      tags: ["calc2", "integration", "strategy"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-integration-tables-tech",
      chapter: "Chapter 7: Techniques of Integration",
      unit: "Integration Techniques",
      topic: "Integration using tables and technology",
      name: "Tables and Technology",
      order: 51,
      useItWhen: "the antiderivative is ugly but standard tools or software can finish it",
      looksLike: "a weird integrand that still fits a known form",
      doThis: "rewrite it into a known pattern or use tech to evaluate and check",
      thinkOfItAs: "using a map when the road is too messy to improvise",
      watchOutFor: "trusting a calculator output without checking the setup",
      rememberThis: "set it up right before you let tech help",
      quickExample: {
        problem: "What should you do before using technology on an integral?",
        move: "Clean the form and make sure the input is correct.",
      },
      typicalProblemShapes: [
        "Complicated antiderivatives with a table entry",
        "Definite integrals evaluated numerically by software",
      ],
      miniDrill: [
        {
          prompt: "Should tech replace setup?",
          answer: "No. It should help after setup.",
        },
        {
          prompt: "What is the trap with calculator integrals?",
          answer: "Bad input or wrong mode.",
        },
      ],
      memoryHook: "Tech helps after the math is set up.",
      tags: ["calc2", "integration", "technology"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-econ-bio-applications",
      chapter: "Chapter 8: Further Applications of Integration",
      unit: "Applications & Curves",
      topic: "Applications to economics and biology",
      name: "Economics and Biology Integrals",
      order: 52,
      useItWhen: "a total value comes from a rate, density, or marginal quantity",
      looksLike: "marginal cost, marginal revenue, growth rate, or density model",
      doThis: "integrate the rate-like quantity to get the total meaning",
      thinkOfItAs: "translating a per-unit story into the whole story",
      watchOutFor: "forgetting the constant or baseline amount",
      rememberThis: "if the problem gives a rate, integrate to get the total",
      quickExample: {
        problem: "What do you do with marginal cost to get total cost change?",
        move: "Integrate it.",
      },
      typicalProblemShapes: [
        "Marginal cost or revenue questions",
        "Population or biological totals built from rate data",
      ],
      miniDrill: [
        {
          prompt: "Marginal quantity means rate of change of what?",
          answer: "A total quantity.",
        },
        {
          prompt: "How do you recover the total from the rate?",
          answer: "Integrate.",
        },
      ],
      memoryHook: "Rate first, total after the integral.",
      tags: ["calc2", "applications", "economics", "biology"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-modeling-differential-equations",
      chapter: "Chapter 9: Differential Equations",
      unit: "Differential Equations",
      topic: "Modeling with differential equations",
      name: "Modeling with Differential Equations",
      order: 53,
      useItWhen: "a word problem says how something changes, not the final formula",
      looksLike: "rate depends on current amount, time, or another variable",
      doThis: "translate the story into an equation for the rate of change",
      thinkOfItAs: "turning a story into a change rule",
      watchOutFor: "writing the quantity itself when the problem describes its rate",
      rememberThis: "model the change, then solve the model",
      quickExample: {
        problem: "If growth is proportional to the amount, what is the model shape?",
        move: "Rate equals k times the amount.",
      },
      typicalProblemShapes: [
        "Word problems about growth, cooling, mixing, or motion",
        "Prompts asking you to form, not just solve, the DE",
      ],
      miniDrill: [
        {
          prompt: "Does a DE model the quantity or its rate of change?",
          answer: "Its rate of change.",
        },
        {
          prompt: "What is the first job in a modeling problem?",
          answer: "Translate the story into a rate equation.",
        },
      ],
      memoryHook: "Story about change? Write a change equation.",
      tags: ["calc2", "differential-equations", "modeling"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "calc2-predator-prey",
      chapter: "Chapter 9: Differential Equations",
      unit: "Differential Equations",
      topic: "Predator-prey systems",
      name: "Predator-Prey Systems",
      order: 54,
      useItWhen: "two populations push each other up and down together",
      looksLike: "one equation for prey and one for predators",
      doThis: "track how each population affects the other instead of solving one variable alone",
      thinkOfItAs: "a population tug-of-war loop",
      watchOutFor: "treating the two equations like they are independent",
      rememberThis: "two populations means a coupled system",
      quickExample: {
        problem: "Why do predator-prey graphs often cycle?",
        move: "Each population changes the other with a delay.",
      },
      typicalProblemShapes: [
        "Rabbits and foxes style models",
        "Two first-order equations linked together",
      ],
      miniDrill: [
        {
          prompt: "Is predator-prey one equation or a system?",
          answer: "A system.",
        },
        {
          prompt: "Do the populations affect each other?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Predators and prey rise and fall together.",
      tags: ["calc2", "differential-equations", "systems"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-conic-sections",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Conic sections",
      name: "Conic Sections",
      order: 55,
      useItWhen: "the graph is a parabola, ellipse, or hyperbola",
      looksLike: "squared x and y terms in a standard pattern",
      doThis: "put the equation in standard form and name the shape from the signs",
      thinkOfItAs: "shape recognition from the algebra costume",
      watchOutFor: "naming the conic before cleaning the equation",
      rememberThis: "rewrite first, then identify the conic",
      quickExample: {
        problem: "How do you identify a conic fast?",
        move: "Get it into standard form and read the pattern.",
      },
      typicalProblemShapes: [
        "Parabola, ellipse, or hyperbola identification",
        "Completing the square to clean the equation",
      ],
      miniDrill: [
        {
          prompt: "Do you identify the conic before or after standard form?",
          answer: "After.",
        },
        {
          prompt: "What usually signals a hyperbola?",
          answer: "A subtraction between squared terms.",
        },
      ],
      memoryHook: "Clean the equation, then read the shape.",
      tags: ["calc2", "conics", "graphing"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-polar-conics",
      chapter: "Chapter 10: Parametric Equations and Polar Coordinates",
      unit: "Applications & Curves",
      topic: "Conic sections in polar coordinates",
      name: "Polar Conics",
      order: 56,
      useItWhen: "a conic is written with r and theta",
      looksLike: "r = ed / (1 plus or minus e cos theta)",
      doThis: "spot the eccentricity form and use e to tell the shape",
      thinkOfItAs: "the same conics wearing polar clothes",
      watchOutFor: "ignoring the role of eccentricity",
      rememberThis: "eccentricity tells the conic type",
      quickExample: {
        problem: "What does e less than 1 mean in a polar conic?",
        move: "Ellipse.",
      },
      typicalProblemShapes: [
        "Orbital or focus-directrix style polar equations",
        "Questions asking whether the curve is an ellipse, parabola, or hyperbola",
      ],
      miniDrill: [
        {
          prompt: "What number decides the conic type here?",
          answer: "Eccentricity e.",
        },
        {
          prompt: "What does e = 1 give?",
          answer: "A parabola.",
        },
      ],
      memoryHook: "In polar conics, e runs the show.",
      tags: ["calc2", "polar", "conics"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "calc2-series-strategy",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Strategy for testing series",
      name: "Series Test Strategy",
      order: 57,
      useItWhen: "a series appears and you need the first test to try",
      looksLike: "sigma with infinity and no obvious label",
      doThis: "check the term limit, then match the pattern to geometric, p-series, comparison, ratio, root, or alternating",
      thinkOfItAs: "a sorting step before the test step",
      watchOutFor: "jumping to ratio test on every series",
      rememberThis: "identify the pattern before picking the test",
      quickExample: {
        problem: "What is the first quick check on any series?",
        move: "See whether the terms go to 0.",
      },
      typicalProblemShapes: [
        "A fresh series with no hint about which test applies",
        "Recognition questions asking for the best first test",
      ],
      miniDrill: [
        {
          prompt: "If terms do not go to 0, converge or diverge?",
          answer: "Diverge.",
        },
        {
          prompt: "Factorials or powers often point toward which test?",
          answer: "Ratio test.",
        },
      ],
      memoryHook: "Sort the series before you test it.",
      tags: ["calc2", "series", "strategy"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "calc2-taylor-applications",
      chapter: "Chapter 11: Sequences, Series, and Power Series",
      unit: "Sequences & Series",
      topic: "Applications of Taylor polynomials",
      name: "Taylor Polynomial Applications",
      order: 58,
      useItWhen: "you need a nearby estimate with a polynomial instead of the full function",
      looksLike: "approximate f(x) near a center a",
      doThis: "use a short Taylor polynomial near the center and keep x close to that center",
      thinkOfItAs: "a local stand-in for a harder function",
      watchOutFor: "using the approximation far away from the center",
      rememberThis: "Taylor works best near the center",
      quickExample: {
        problem: "When is a Taylor approximation most trustworthy?",
        move: "Near the expansion center.",
      },
      typicalProblemShapes: [
        "Approximate a function value without a calculator",
        "Estimate error or decide how many terms are enough",
      ],
      miniDrill: [
        {
          prompt: "Does Taylor get better near or far from the center?",
          answer: "Near the center.",
        },
        {
          prompt: "Why use a Taylor polynomial?",
          answer: "To replace a hard function with an easier local polynomial.",
        },
      ],
      memoryHook: "Taylor = local shortcut polynomial.",
      tags: ["calc2", "series", "taylor"],
      difficulty: "Standard",
    }),
  ],
};
