import type { BubbleCard, CourseContent } from "@/content/schema";

function makeCalcCard(
  card: Omit<BubbleCard, "subject" | "course" | "courseCode">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Single-Variable Calculus I",
    courseCode: "MATH 2A",
    ...card,
  };
}

export const calcOneCourse: CourseContent = {
  id: "calc-1",
  subject: "Mathematics",
  title: "Single-Variable Calculus I",
  institution: "UCI",
  courseCodes: ["MATH 2A"],
  aliases: ["Calculus I", "Single Variable Calculus 1"],
  shortDescription:
    "Fast single-variable calculus review for students who need the move first.",
  units: [
    "Limits",
    "Derivatives",
    "Applications",
    "Integrals",
    "Applications of Integration",
  ],
  chapters: [
    "Chapter 1: Functions and Limits",
    "Chapter 2: Derivatives",
    "Chapter 3: Applications of Differentiation",
    "Chapter 4: Integrals",
    "Chapter 5: Applications of Integration",
  ],
  cards: [
    makeCalcCard({
      id: "intuitive-limit",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Intuitive idea of a limit",
      name: "Intuitive Limit Idea",
      order: 1,
      useItWhen: "you care about what the output is heading toward",
      looksLike: "a graph, table, or lim as x goes to a number",
      doThis: "look from the left and right and name the target value",
      thinkOfItAs: "walking up to a door without stepping through it",
      watchOutFor: "mixing up at the point with near the point",
      rememberThis: "limits are about near, not at",
      quickExample: {
        problem: "As x approaches 3, what does x^2 approach?",
        move: "The outputs head to 9.",
      },
      typicalProblemShapes: [
        "A graph asks what y-value the curve approaches near x = a",
        "A table shows x-values closing in on a number from both sides",
      ],
      miniDrill: [
        {
          prompt: "If the left side goes to 4 and the right side goes to 4, does the limit exist?",
          answer: "Yes. Both sides agree on 4.",
        },
        {
          prompt: "If f(2) = 9 but nearby values head to 5, what is the limit as x approaches 2?",
          answer: "5. The point value does not control the limit.",
        },
      ],
      memoryHook: "Near the point, not on the point.",
      tags: ["limits", "graph-reading", "intuition"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "direct-substitution",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Direct substitution",
      name: "Direct Substitution",
      order: 2,
      useItWhen: "plugging in does not break anything",
      looksLike: "polynomials or clean fractions with no zero downstairs",
      doThis: "plug in first",
      thinkOfItAs: "trying the front door before looking for side entrances",
      watchOutFor: "getting 0/0 and still trying to plug",
      rememberThis: "no break means just plug",
      quickExample: {
        problem: "Limit as x approaches 2 of x^2 + 1",
        move: "Plug in 2 and get 5.",
      },
      typicalProblemShapes: [
        "A polynomial like x^3 - 4x + 7",
        "A rational expression where the denominator is not zero at the target",
      ],
      miniDrill: [
        {
          prompt: "Try x = 1 in (x^2 + 5x)/(x + 4). What happens first?",
          answer: "It stays legal, so direct substitution works.",
        },
        {
          prompt: "You plug in and get 0/0. Keep direct substitution or switch?",
          answer: "Switch. 0/0 means simplify first.",
        },
      ],
      memoryHook: "No break, just plug.",
      tags: ["limits", "substitution", "continuous"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "factoring-0-0",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Factoring to remove 0/0",
      name: "Factoring Out 0/0",
      order: 3,
      useItWhen: "plugging in gives 0/0 and you can factor",
      looksLike: "(x^2 - 9)/(x - 3) or another factorable fraction",
      doThis: "factor, cancel the shared piece, then plug in",
      thinkOfItAs: "unzipping a stuck jacket before trying to pull it apart",
      watchOutFor: "cancelling terms that are added instead of multiplied",
      rememberThis: "0/0 often means simplify first",
      quickExample: {
        problem: "Limit as x approaches 3 of (x^2 - 9)/(x - 3)",
        move: "Factor to (x - 3)(x + 3), cancel, then plug in 3 to get 6.",
      },
      typicalProblemShapes: [
        "Difference of squares on top or bottom",
        "Quadratics or polynomials that can be factored before plugging in",
      ],
      miniDrill: [
        {
          prompt: "You get 0/0 from a polynomial fraction. First move?",
          answer: "Look for factoring.",
        },
        {
          prompt: "Can you cancel x - 2 from x^2 - 4 after factoring?",
          answer: "Yes, because x^2 - 4 becomes (x - 2)(x + 2).",
        },
      ],
      memoryHook: "Zero over zero means clean it up.",
      tags: ["limits", "factoring", "algebra"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "rationalizing",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Rationalizing",
      name: "Rationalizing a Limit",
      order: 4,
      useItWhen: "plugging in gives 0/0 and a root is involved",
      looksLike: "(sqrt(x + 5) - 3)/(x - 4)",
      doThis: "multiply by the conjugate, clean it up, then plug in",
      thinkOfItAs: "using a mirror image to make the root disappear",
      watchOutFor: "sign mistakes in the conjugate",
      rememberThis: "radicals often want the conjugate",
      quickExample: {
        problem: "Limit as x approaches 4 of (sqrt(x + 5) - 3)/(x - 4)",
        move: "Multiply by sqrt(x + 5) + 3, simplify, then plug in 4.",
      },
      typicalProblemShapes: [
        "A square root minus or plus a number in the numerator",
        "A root expression that turns into 0/0 at the target point",
      ],
      miniDrill: [
        {
          prompt: "What is the conjugate of sqrt(x + 2) - 5?",
          answer: "sqrt(x + 2) + 5",
        },
        {
          prompt: "Substitution gives 0/0 and there is a square root. Best tool?",
          answer: "Rationalize with the conjugate.",
        },
      ],
      memoryHook: "Roots like mirror moves.",
      tags: ["limits", "radicals", "conjugates"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "infinite-limits",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Infinite limits",
      name: "Infinite Limits",
      order: 5,
      useItWhen: "the output blows up near one x-value",
      looksLike: "1/(x - 2), 1/(x - 2)^2, vertical asymptotes",
      doThis: "check the sign on each side and decide up or down",
      thinkOfItAs: "a graph racing up or down a vertical wall",
      watchOutFor: "assuming both sides do the same thing",
      rememberThis: "tiny denominator, huge output",
      quickExample: {
        problem: "As x approaches 2 from the right, what happens to 1/(x - 2)?",
        move: "The denominator is tiny positive, so the output goes to positive infinity.",
      },
      typicalProblemShapes: [
        "Fractions with denominator approaching zero",
        "Questions about vertical asymptotes and one-sided behavior",
      ],
      miniDrill: [
        {
          prompt: "As x approaches 2 from the left, is x - 2 positive or negative?",
          answer: "Negative.",
        },
        {
          prompt: "If a denominator is tiny negative, what can happen to 1 over that number?",
          answer: "It can drop toward negative infinity.",
        },
      ],
      memoryHook: "Near zero downstairs means chaos upstairs.",
      tags: ["limits", "asymptotes", "one-sided"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "limits-at-infinity",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Limits at infinity",
      name: "Limits at Infinity",
      order: 6,
      useItWhen: "x goes way left or way right",
      looksLike: "ratios of polynomials like (3x^2 + 1)/(x^2 - 4)",
      doThis: "ignore the small stuff and compare the biggest powers",
      thinkOfItAs: "the loudest term in the room drowning out the rest",
      watchOutFor: "letting small constants distract you",
      rememberThis: "biggest power wins at the ends",
      quickExample: {
        problem: "Limit as x approaches infinity of (3x^2 + 1)/(x^2 - 4)",
        move: "Top and bottom have the same degree, so the limit is 3/1.",
      },
      typicalProblemShapes: [
        "Polynomial ratios with x heading to infinity",
        "Questions asking for horizontal behavior of a graph",
      ],
      miniDrill: [
        {
          prompt: "Which matters more at infinity: x^3 or 7x?",
          answer: "x^3 dominates.",
        },
        {
          prompt: "Top degree smaller than bottom degree. What usually happens to the limit?",
          answer: "It usually goes to 0.",
        },
      ],
      memoryHook: "At the edges, the highest power drives.",
      tags: ["limits", "end-behavior", "polynomials"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "continuity",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Continuity",
      name: "Continuity",
      order: 7,
      useItWhen: "you need to check for a break",
      looksLike: "graphs with holes, jumps, corners, or piecewise definitions",
      doThis: "check defined, limit exists, and both match",
      thinkOfItAs: "a road with no gap, jump, or missing plank",
      watchOutFor: "checking the picture but not the point value",
      rememberThis: "continuous means no tear at that spot",
      quickExample: {
        problem: "A function has a hole at x = 2 even though both sides approach 5.",
        move: "It is not continuous at x = 2 unless the function value is also 5 there.",
      },
      typicalProblemShapes: [
        "Piecewise functions that switch formulas at one point",
        "A graph with a hole, jump, or vertical asymptote",
      ],
      miniDrill: [
        {
          prompt: "If the left and right limits disagree, is the function continuous there?",
          answer: "No. The limit does not exist.",
        },
        {
          prompt: "If the limit is 4 and f(1) is also 4, what else do you still need?",
          answer: "The function must be defined at x = 1, which it is in this case.",
        },
      ],
      memoryHook: "Defined, limit exists, values match.",
      tags: ["limits", "continuity", "piecewise"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "derivative-slope-rate",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Derivative as slope and rate of change",
      name: "Derivative = Slope / Rate",
      order: 8,
      useItWhen: "you want the slope now or the speed now",
      looksLike: "f'(x), dy/dx, tangent slope, velocity",
      doThis: "read it as right-now change",
      thinkOfItAs: "a speedometer instead of the whole road trip",
      watchOutFor: "mixing up average change with instantaneous change",
      rememberThis: "derivative means how fast right now",
      quickExample: {
        problem: "If s(t) is position, what does s'(t) mean?",
        move: "Instantaneous velocity.",
      },
      typicalProblemShapes: [
        "Words like instant, tangent, slope now, or rate now",
        "Position, cost, temperature, or population changing with input",
      ],
      miniDrill: [
        {
          prompt: "Does a derivative describe a secant line or a tangent line?",
          answer: "A tangent line.",
        },
        {
          prompt: "If f'(3) is negative, is the graph rising or falling there?",
          answer: "Falling.",
        },
      ],
      memoryHook: "Derivative = right-now speed.",
      tags: ["derivatives", "slope", "rate-of-change"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "derivative-definition",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Derivative from definition",
      name: "Derivative from Definition",
      order: 9,
      useItWhen: "the problem says use the definition",
      looksLike: "limit as h approaches 0 of [f(x + h) - f(x)] / h",
      doThis: "build it, expand it, cancel, then let h go to 0",
      thinkOfItAs: "zooming in with smaller and smaller secant steps",
      watchOutFor: "plugging in h = 0 before simplifying",
      rememberThis: "simplify first, then take the limit",
      quickExample: {
        problem: "Find the derivative of x^2 from definition.",
        move: "Expand (x + h)^2, cancel, divide by h, then let h go to 0.",
      },
      typicalProblemShapes: [
        "An explicit difference quotient already written down",
        "A prompt that says use the limit definition only",
      ],
      miniDrill: [
        {
          prompt: "What usually cancels after expanding f(x + h) - f(x)?",
          answer: "The original f(x) terms.",
        },
        {
          prompt: "When do you finally let h go to 0?",
          answer: "After the quotient is simplified enough to avoid 0/0.",
        },
      ],
      memoryHook: "Expand, cancel, divide, limit.",
      tags: ["derivatives", "definition", "limits"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "power-rule",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Power rule",
      name: "Power Rule",
      order: 10,
      useItWhen: "you see x to a power",
      looksLike: "x^5, x^-2, x^(1/3)",
      doThis: "bring the power down, then drop it by 1",
      thinkOfItAs: "the exponent drops down and one gets shaved off",
      watchOutFor: "thinking it only works for nice whole numbers",
      rememberThis: "down front, minus one",
      quickExample: {
        problem: "Derivative of x^7",
        move: "7x^6",
      },
      typicalProblemShapes: [
        "Plain power terms with x as the base",
        "Polynomials built from multiple power-rule terms",
      ],
      miniDrill: [
        {
          prompt: "Derivative of x^-3?",
          answer: "-3x^-4",
        },
        {
          prompt: "Derivative of sqrt(x) written as x^(1/2)?",
          answer: "One-half x^-1/2",
        },
      ],
      memoryHook: "Bring it down, drop it by one.",
      tags: ["derivatives", "rules", "powers"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "constant-rule",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Constant rule",
      name: "Constant Rule",
      order: 11,
      useItWhen: "a term has no x in it",
      looksLike: "7, pi, -12, or any fixed number",
      doThis: "turn that constant term into 0",
      thinkOfItAs: "a flat line with zero tilt",
      watchOutFor: "treating coefficients like constants with no x attached",
      rememberThis: "constants disappear",
      quickExample: {
        problem: "Derivative of 9",
        move: "0",
      },
      typicalProblemShapes: [
        "A standalone number in a polynomial",
        "A question asking for the derivative of a fixed value",
      ],
      miniDrill: [
        {
          prompt: "Derivative of -4?",
          answer: "0",
        },
        {
          prompt: "In 5x^2 + 8, which part becomes 0?",
          answer: "The 8.",
        },
      ],
      memoryHook: "Flat line, zero slope.",
      tags: ["derivatives", "rules", "constants"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "sum-difference-rules",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Sum and difference rules",
      name: "Sum and Difference Rules",
      order: 12,
      useItWhen: "terms are added or subtracted",
      looksLike: "x^3 + 4x - 7 or 2x^5 - sqrt(x)",
      doThis: "differentiate each term and keep the signs",
      thinkOfItAs: "grading each term separately, then adding the scores",
      watchOutFor: "dropping a negative sign",
      rememberThis: "term by term works",
      quickExample: {
        problem: "Derivative of x^3 + 4x - 7",
        move: "3x^2 + 4",
      },
      typicalProblemShapes: [
        "Polynomials with several terms",
        "Mixed expressions where the pieces are joined by plus or minus",
      ],
      miniDrill: [
        {
          prompt: "Do you need product rule for x^2 + x^5?",
          answer: "No. Differentiate term by term.",
        },
        {
          prompt: "What sign should stay with the derivative of -3x^2?",
          answer: "Negative.",
        },
      ],
      memoryHook: "Split the terms, not the signs.",
      tags: ["derivatives", "rules", "polynomials"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "product-rule",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Product rule",
      name: "Product Rule",
      order: 13,
      useItWhen: "two changing pieces are multiplied",
      looksLike: "(x^2 + 1)(x^3 - 4) or x sin x",
      doThis: "first-prime second plus first second-prime",
      thinkOfItAs: "both pieces are moving, so both get a turn",
      watchOutFor: "multiplying the derivatives together",
      rememberThis: "first prime second plus first second prime",
      quickExample: {
        problem: "Derivative of x^2 sin x",
        move: "2x sin x + x^2 cos x",
      },
      typicalProblemShapes: [
        "Two visible factors next to each other",
        "An algebra piece times a trig or exponential piece",
      ],
      miniDrill: [
        {
          prompt: "Which rule fits x(x^2 + 4)?",
          answer: "Product rule.",
        },
        {
          prompt: "In product rule, how many terms appear after differentiating?",
          answer: "Two terms.",
        },
      ],
      memoryHook: "Both changing means both get counted.",
      tags: ["derivatives", "product-rule", "rules"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "quotient-rule",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Quotient rule",
      name: "Quotient Rule",
      order: 14,
      useItWhen: "one changing thing is over another",
      looksLike: "(x^2 + 1)/(x - 3)",
      doThis:
        "low d-high minus high d-low, all over low squared",
      thinkOfItAs: "top and bottom trade hits, bottom stays squared",
      watchOutFor: "flipping the order and changing the sign",
      rememberThis: "low d-high minus high d-low over low squared",
      quickExample: {
        problem: "Derivative of (x^2 + 1)/(x - 3)",
        move: "Use low d-high minus high d-low, then divide by (x - 3)^2.",
      },
      typicalProblemShapes: [
        "A fraction with x in the numerator and denominator",
        "A rational function where both top and bottom change",
      ],
      miniDrill: [
        {
          prompt: "Which comes first in the top: denominator times numerator derivative, or the other way?",
          answer: "Denominator times numerator derivative.",
        },
        {
          prompt: "What happens to the denominator in quotient rule?",
          answer: "It gets squared.",
        },
      ],
      memoryHook: "Low d-high, high d-low, low squared.",
      tags: ["derivatives", "quotient-rule", "fractions"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "chain-rule",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Chain rule",
      name: "Chain Rule",
      order: 15,
      useItWhen: "one function is inside another",
      looksLike: "(3x^2 + 1)^5, sin(x^3), e^(2x)",
      doThis: "do the outside, keep the inside, then multiply by inside prime",
      thinkOfItAs: "peeling an onion layer by layer",
      watchOutFor: "forgetting the inside derivative",
      rememberThis: "outside first, inside next",
      quickExample: {
        problem: "Derivative of (3x^2 + 1)^5",
        move: "5(3x^2 + 1)^4 times 6x",
      },
      typicalProblemShapes: [
        "A power wrapped around a polynomial",
        "Trig, exponential, or log with another expression inside",
      ],
      miniDrill: [
        {
          prompt: "Which rule fits sin(x^4)?",
          answer: "Chain rule.",
        },
        {
          prompt: "After differentiating the outside of (x^2 + 3)^7, what must still happen?",
          answer: "Multiply by the derivative of x^2 + 3.",
        },
      ],
      memoryHook: "Outside-inside, then multiply.",
      tags: ["derivatives", "chain-rule", "composition"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "implicit-differentiation",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Implicit differentiation",
      name: "Implicit Differentiation",
      order: 16,
      useItWhen: "x and y are mixed and y is not alone",
      looksLike: "x^2 + y^2 = 25 or xy + y^3 = 7",
      doThis: "differentiate both sides, attach y-prime to y terms, solve for y-prime",
      thinkOfItAs: "pulling y-prime out from a crowd",
      watchOutFor: "forgetting the y-prime on y terms",
      rememberThis: "differentiate both sides and solve for y-prime",
      quickExample: {
        problem: "Differentiate x^2 + y^2 = 25",
        move: "2x + 2y y' = 0, then solve for y'.",
      },
      typicalProblemShapes: [
        "Equations defining curves, not explicit y = ... forms",
        "Products or powers involving y",
      ],
      miniDrill: [
        {
          prompt: "Derivative of y^3 with respect to x?",
          answer: "3y^2 y'",
        },
        {
          prompt: "After differentiating implicitly, what final algebra step often appears?",
          answer: "Solve for y'.",
        },
      ],
      memoryHook: "Differentiate everything, rescue y-prime.",
      tags: ["derivatives", "implicit", "chain-rule"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "logarithmic-differentiation",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Logarithmic differentiation",
      name: "Logarithmic Differentiation",
      order: 17,
      useItWhen: "powers or exponents get weird",
      looksLike: "y = x^x or y = (x^2 + 1)^x",
      doThis: "take ln, spread things out, then differentiate",
      thinkOfItAs: "turning a tangled knot into separate strings",
      watchOutFor: "forgetting ln(y) turns into y-prime over y",
      rememberThis: "take ln first when exponents get weird",
      quickExample: {
        problem: "Differentiate y = x^x",
        move: "Use ln(y) = x ln x, differentiate, then solve back for y'.",
      },
      typicalProblemShapes: [
        "Variable in the exponent like x^x",
        "Big products or quotients raised to powers",
      ],
      miniDrill: [
        {
          prompt: "What is the first move for y = x^x?",
          answer: "Take ln of both sides.",
        },
        {
          prompt: "After differentiating ln(y), what appears on the left?",
          answer: "y'/y",
        },
      ],
      memoryHook: "Weird exponents? Log it first.",
      tags: ["derivatives", "logs", "advanced-rules"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "higher-derivatives",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Higher derivatives",
      name: "Higher Derivatives",
      order: 18,
      useItWhen: "they ask for second, third, or more",
      looksLike: "f''(x), y'', d^3y/dx^3",
      doThis: "differentiate again until you hit the right order",
      thinkOfItAs: "taking the derivative in layers",
      watchOutFor: "stopping after the first derivative",
      rememberThis: "prime again if they ask again",
      quickExample: {
        problem: "If f(x) = x^4, what is f''(x)?",
        move: "First derivative is 4x^3, second derivative is 12x^2.",
      },
      typicalProblemShapes: [
        "Notation with double primes or second derivative wording",
        "Concavity or acceleration problems",
      ],
      miniDrill: [
        {
          prompt: "If s(t) is position, what is s''(t)?",
          answer: "Acceleration.",
        },
        {
          prompt: "Do you reuse the original function or the first derivative to find f''?",
          answer: "Use the first derivative.",
        },
      ],
      memoryHook: "Differentiate the derivative.",
      tags: ["derivatives", "second-derivative", "notation"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "tangent-line",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Tangent line",
      name: "Tangent Line",
      order: 19,
      useItWhen: "you need the line that matches the curve at one point",
      looksLike: "find the tangent line to y = f(x) at x = a",
      doThis: "find the point, get the slope from the derivative, write the line",
      thinkOfItAs: "the line that matches the curve's direction for one instant",
      watchOutFor: "using x = a as the slope",
      rememberThis: "point plus derivative slope gives the line",
      quickExample: {
        problem: "Find the tangent line to y = x^2 at x = 2",
        move: "Point is (2, 4), slope is 4, so y - 4 = 4(x - 2).",
      },
      typicalProblemShapes: [
        "A point on a curve and the words tangent line",
        "A prompt asking for linearization at a point",
      ],
      miniDrill: [
        {
          prompt: "What gives the tangent slope: f(a) or f'(a)?",
          answer: "f'(a)",
        },
        {
          prompt: "After getting slope and point, which line formula is fastest?",
          answer: "Point-slope form.",
        },
      ],
      memoryHook: "Slope from derivative, line from point.",
      tags: ["applications", "tangent", "lines"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "normal-line",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Normal line",
      name: "Normal Line",
      order: 20,
      useItWhen: "you need the line perpendicular to the tangent",
      looksLike: "find the normal line at x = a",
      doThis: "find tangent slope, flip it, change the sign, write the line",
      thinkOfItAs: "the tangent line's sideways partner",
      watchOutFor: "forgetting the negative reciprocal",
      rememberThis: "normal slope is the negative reciprocal",
      quickExample: {
        problem: "If tangent slope is 2, what is the normal slope?",
        move: "-1/2",
      },
      typicalProblemShapes: [
        "A tangent line problem with the word normal instead",
        "A request for a perpendicular line to the curve at a point",
      ],
      miniDrill: [
        {
          prompt: "If tangent slope is -3, what is normal slope?",
          answer: "1/3",
        },
        {
          prompt: "Do you still need the point on the curve for the normal line?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Flip, change sign, use the same point.",
      tags: ["applications", "normal-line", "perpendicular"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "increasing-decreasing",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Increasing and decreasing",
      name: "Increasing / Decreasing",
      order: 21,
      useItWhen: "you need where the graph goes up or down",
      looksLike: "find intervals of increase and decrease",
      doThis: "make an f-prime sign chart",
      thinkOfItAs: "green light for rising, red light for falling",
      watchOutFor: "using f instead of f-prime for the sign chart",
      rememberThis: "f-prime positive means increasing",
      quickExample: {
        problem: "If f'(x) is negative on (1, 4), what is f doing there?",
        move: "It is decreasing on (1, 4).",
      },
      typicalProblemShapes: [
        "Interval questions about where the graph rises or falls",
        "Derivative sign charts or critical-point tables",
      ],
      miniDrill: [
        {
          prompt: "If f'(x) > 0, is the graph going up or down?",
          answer: "Up.",
        },
        {
          prompt: "Where do sign-chart intervals usually start and stop?",
          answer: "At critical points and places where f' is undefined.",
        },
      ],
      memoryHook: "Positive prime up, negative prime down.",
      tags: ["applications", "first-derivative", "sign-chart"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "local-max-min",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Local max and min",
      name: "Local Max / Min",
      order: 22,
      useItWhen: "you want nearby peaks and valleys",
      looksLike: "find local extrema or turning points",
      doThis: "find critical points, then test around them",
      thinkOfItAs: "hilltops and valleys on a short hike",
      watchOutFor: "calling every critical point a max or min without testing",
      rememberThis: "critical point first, decision second",
      quickExample: {
        problem: "At a critical point, f' changes from positive to negative. What is it?",
        move: "A local maximum.",
      },
      typicalProblemShapes: [
        "Questions about turning points",
        "Critical points followed by sign or second-derivative tests",
      ],
      miniDrill: [
        {
          prompt: "Positive to negative in f'. Max or min?",
          answer: "Local max.",
        },
        {
          prompt: "Negative to positive in f'. Max or min?",
          answer: "Local min.",
        },
      ],
      memoryHook: "Find the critical point, then read the turn.",
      tags: ["applications", "extrema", "critical-points"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "concavity",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Concavity",
      name: "Concavity",
      order: 23,
      useItWhen: "you need the bend of the graph",
      looksLike: "concave up, concave down, or second derivative sign questions",
      doThis: "check f-double-prime: plus is up, minus is down",
      thinkOfItAs: "a smile versus a frown",
      watchOutFor: "using f-prime instead of f-double-prime",
      rememberThis: "second derivative tells the bend",
      quickExample: {
        problem: "If f''(x) > 0 on an interval, what shape is the graph?",
        move: "Concave up.",
      },
      typicalProblemShapes: [
        "Questions about curvature or bending",
        "A second derivative already given as a function or sign chart",
      ],
      miniDrill: [
        {
          prompt: "If f''(x) < 0, smile or frown?",
          answer: "Frown. Concave down.",
        },
        {
          prompt: "Which derivative controls concavity?",
          answer: "The second derivative.",
        },
      ],
      memoryHook: "Second derivative = smile or frown.",
      tags: ["applications", "concavity", "second-derivative"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "inflection-points",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Inflection points",
      name: "Inflection Points",
      order: 24,
      useItWhen: "you need where the bend flips",
      looksLike: "find possible inflection points",
      doThis: "find f-double-prime trouble spots, then check for a sign change",
      thinkOfItAs: "the spot where the bend flips",
      watchOutFor: "calling every zero an inflection point",
      rememberThis: "it only counts if the bend changes",
      quickExample: {
        problem: "If f'' changes from negative to positive at x = 1, what happens there?",
        move: "There is an inflection point at x = 1.",
      },
      typicalProblemShapes: [
        "Second derivative equal to zero followed by a sign check",
        "A graph that switches from frown to smile",
      ],
      miniDrill: [
        {
          prompt: "Is f''(a) = 0 enough by itself?",
          answer: "No. Concavity must change.",
        },
        {
          prompt: "What are you testing around a candidate point?",
          answer: "The sign of f'' on each side.",
        },
      ],
      memoryHook: "Zero is a maybe. Sign change is the proof.",
      tags: ["applications", "inflection", "concavity"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "first-derivative-test",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "First derivative test",
      name: "First Derivative Test",
      order: 25,
      useItWhen: "you want max or min from f-prime signs",
      looksLike: "a sign chart around a critical number",
      doThis: "check f-prime left and right of the point",
      thinkOfItAs: "watching traffic before and after an intersection",
      watchOutFor: "testing only the point itself instead of nearby intervals",
      rememberThis: "the sign switch tells the story",
      quickExample: {
        problem: "f' goes negative to positive around x = 2. What is x = 2?",
        move: "A local minimum.",
      },
      typicalProblemShapes: [
        "Critical numbers followed by interval testing",
        "A table of signs for f-prime",
      ],
      miniDrill: [
        {
          prompt: "Positive to negative in f'. Max or min?",
          answer: "Local max.",
        },
        {
          prompt: "No sign change in f'. What can happen?",
          answer: "The point may be neither a max nor a min.",
        },
      ],
      memoryHook: "Read the sign switch, not just the point.",
      tags: ["applications", "first-derivative-test", "critical-points"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "second-derivative-test",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Second derivative test",
      name: "Second Derivative Test",
      order: 26,
      useItWhen: "you already have a critical point and want a quick check",
      looksLike: "find f'(c) = 0, then check f''(c)",
      doThis: "plug c into f-double-prime: plus min, minus max",
      thinkOfItAs: "letting the bend decide the turn",
      watchOutFor: "using it when f-double-prime is 0",
      rememberThis: "second derivative decides only when it is not zero",
      quickExample: {
        problem: "At a critical point c, f''(c) = 5. Max or min?",
        move: "Local minimum.",
      },
      typicalProblemShapes: [
        "A critical point already found from f' = 0",
        "Questions asking for a faster alternative to the first derivative test",
      ],
      miniDrill: [
        {
          prompt: "If f''(c) < 0 at a critical point, what is c?",
          answer: "A local max.",
        },
        {
          prompt: "If f''(c) = 0, what does the second derivative test say?",
          answer: "Nothing definite. Use another test.",
        },
      ],
      memoryHook: "Positive bowl = min. Negative cap = max.",
      tags: ["applications", "second-derivative-test", "extrema"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "optimization",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Optimization",
      name: "Optimization",
      order: 27,
      useItWhen: "the problem says biggest, smallest, cheapest, or best",
      looksLike: "maximize area, minimize cost, optimize volume",
      doThis: "write one-variable target, differentiate, test the winner",
      thinkOfItAs: "turning a word mess into one clean hill or valley",
      watchOutFor: "differentiating before you get one variable",
      rememberThis: "one variable first, optimize second",
      quickExample: {
        problem: "A rectangle has fixed perimeter. What should you optimize?",
        move: "Write area using one variable, then differentiate that area function.",
      },
      typicalProblemShapes: [
        "Words like maximize, minimize, most, least, shortest, largest",
        "Geometry or business word problems with a constraint",
      ],
      miniDrill: [
        {
          prompt: "Before you differentiate, how many variables should your target function have?",
          answer: "One.",
        },
        {
          prompt: "After finding a critical point, are you finished?",
          answer: "No. You still need to confirm it gives the best value.",
        },
      ],
      memoryHook: "Write one variable, then hunt the peak or valley.",
      tags: ["applications", "optimization", "word-problems"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "related-rates",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Related rates",
      name: "Related Rates",
      order: 28,
      useItWhen: "several changing things are linked by time",
      looksLike: "a radius grows while volume changes, or a ladder slides while height changes",
      doThis: "write the equation, differentiate in time, then plug in",
      thinkOfItAs: "all the variables move together on one clock",
      watchOutFor: "plugging numbers in too early",
      rememberThis: "differentiate first, then plug the moment in",
      quickExample: {
        problem: "A balloon radius changes with time and volume is asked for. What variable should you differentiate with respect to?",
        move: "Time.",
      },
      typicalProblemShapes: [
        "Given rates like dx/dt or dV/dt",
        "A geometric formula with values changing over time",
      ],
      miniDrill: [
        {
          prompt: "Do you usually plug numbers in before or after implicit differentiation in related rates?",
          answer: "After.",
        },
        {
          prompt: "If two variables depend on time, what derivative often appears for each one?",
          answer: "A rate like dx/dt or dy/dt.",
        },
      ],
      memoryHook: "Differentiate in time, then freeze the moment.",
      tags: ["applications", "related-rates", "implicit"],
      difficulty: "Stretch",
    }),
    makeCalcCard({
      id: "linear-approximation",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Linear approximation",
      name: "Linear Approximation",
      order: 29,
      useItWhen: "you need a quick estimate near a nice point",
      looksLike: "approximate sqrt(4.1) or estimate a function near x = a",
      doThis: "use the tangent-line formula",
      thinkOfItAs: "using the local straight-line version of the curve",
      watchOutFor: "picking a base point that is not close",
      rememberThis: "close to a, use the tangent line",
      quickExample: {
        problem: "Estimate sqrt(4.1) using a = 4",
        move: "Use the tangent line for sqrt(x) at x = 4.",
      },
      typicalProblemShapes: [
        "Approximate a function value near a nice number",
        "A prompt that mentions local linearization or tangent-line estimate",
      ],
      miniDrill: [
        {
          prompt: "For estimating sqrt(4.1), should a be 1, 4, or 9?",
          answer: "4, because it is close and easy.",
        },
        {
          prompt: "What two ingredients does linear approximation need at x = a?",
          answer: "f(a) and f'(a).",
        },
      ],
      memoryHook: "Near a nice point, use the tangent line.",
      tags: ["applications", "approximation", "tangent-line"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "antiderivative-idea",
      chapter: "Chapter 4: Integrals",
      unit: "Integrals",
      topic: "Antiderivative idea",
      name: "Antiderivative Idea",
      order: 30,
      useItWhen: "you want to undo a derivative",
      looksLike: "find a function whose derivative is 6x or cos x",
      doThis: "ask what function would differentiate to this",
      thinkOfItAs: "running the derivative movie backward",
      watchOutFor: "forgetting the constant family",
      rememberThis: "antiderivative means reverse the derivative",
      quickExample: {
        problem: "What function has derivative 6x?",
        move: "x^2-type functions work; the basic antiderivative is 3x^2 plus a constant later.",
      },
      typicalProblemShapes: [
        "Prompts asking for a function whose derivative is known",
        "Early integral questions before formal notation appears",
      ],
      miniDrill: [
        {
          prompt: "If the derivative is 4x^3, what family of functions could work?",
          answer: "x^4 plus a constant.",
        },
        {
          prompt: "Does reversing a derivative give one answer or a family?",
          answer: "A family.",
        },
      ],
      memoryHook: "Integral thinking starts with reverse mode.",
      tags: ["integrals", "antiderivative", "reverse"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "indefinite-integral",
      chapter: "Chapter 4: Integrals",
      unit: "Integrals",
      topic: "Indefinite integral",
      name: "Indefinite Integral",
      order: 31,
      useItWhen: "you want the whole antiderivative family",
      looksLike: "integral of f(x) dx",
      doThis: "find the antiderivative and add plus C",
      thinkOfItAs: "the answer with room for vertical shifts",
      watchOutFor: "forgetting the plus C",
      rememberThis: "indefinite integrals travel with plus C",
      quickExample: {
        problem: "Integral of 2x dx",
        move: "x^2 + C",
      },
      typicalProblemShapes: [
        "Integral notation with no upper or lower limits",
        "Prompts asking for a general antiderivative",
      ],
      miniDrill: [
        {
          prompt: "What extra piece belongs on every indefinite integral answer?",
          answer: "+ C",
        },
        {
          prompt: "Does a definite integral get + C?",
          answer: "No.",
        },
      ],
      memoryHook: "No bounds means plus C.",
      tags: ["integrals", "indefinite", "notation"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "integral-power-rule",
      chapter: "Chapter 4: Integrals",
      unit: "Integrals",
      topic: "Basic power rule for integrals",
      name: "Integral Power Rule",
      order: 32,
      useItWhen: "you are integrating x to a power, but not x^-1",
      looksLike: "integral of x^n dx",
      doThis: "add 1, divide by the new power, add C",
      thinkOfItAs: "the derivative power rule played backward",
      watchOutFor: "using it on x^-1",
      rememberThis: "add one, divide by the new one",
      quickExample: {
        problem: "Integral of x^4 dx",
        move: "x^5 / 5 + C",
      },
      typicalProblemShapes: [
        "Plain powers of x in an indefinite integral",
        "Polynomials integrated term by term",
      ],
      miniDrill: [
        {
          prompt: "Integral of x^2 dx?",
          answer: "x^3 / 3 + C",
        },
        {
          prompt: "What is the special exponent you should not feed into the basic power rule?",
          answer: "-1",
        },
      ],
      memoryHook: "Add one, divide, plus C.",
      tags: ["integrals", "power-rule", "antiderivative"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "definite-integral-area",
      chapter: "Chapter 4: Integrals",
      unit: "Integrals",
      topic: "Definite integral as area idea",
      name: "Definite Integral = Signed Area",
      order: 33,
      useItWhen: "you need total change over an interval",
      looksLike: "integral from a to b of f(x) dx",
      doThis: "read it as signed area from left bound to right bound",
      thinkOfItAs: "adding up lots of tiny rectangles",
      watchOutFor: "forgetting below the x-axis counts negative",
      rememberThis: "definite integrals add change over an interval",
      quickExample: {
        problem: "What does integral from 0 to 2 of f(x) dx measure?",
        move: "Net accumulated area from x = 0 to x = 2.",
      },
      typicalProblemShapes: [
        "Integral signs with actual bounds",
        "Graph questions asking for total or net area",
      ],
      miniDrill: [
        {
          prompt: "Does area below the x-axis count positive or negative in a raw definite integral?",
          answer: "Negative.",
        },
        {
          prompt: "What does the interval [a, b] control?",
          answer: "Where accumulation starts and stops.",
        },
      ],
      memoryHook: "Bounds mean total over a stretch.",
      tags: ["integrals", "definite", "area"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "ftc-practical",
      chapter: "Chapter 4: Integrals",
      unit: "Integrals",
      topic: "Fundamental Theorem of Calculus",
      name: "FTC Practical Use",
      order: 34,
      useItWhen: "you need a quick definite integral or integral derivative",
      looksLike: "top-minus-bottom setup or d/dx of an integral to x",
      doThis: "use top minus bottom, or unwrap the inside",
      thinkOfItAs: "derivatives and integrals shaking hands",
      watchOutFor: "forgetting top minus bottom",
      rememberThis: "antiderivative to evaluate, original function to unwrap",
      quickExample: {
        problem: "Integral from 1 to 3 of 2x dx",
        move: "Use x^2, then do 3^2 - 1^2.",
      },
      typicalProblemShapes: [
        "Evaluate a definite integral using an antiderivative",
        "Differentiate an integral whose upper limit is x",
      ],
      miniDrill: [
        {
          prompt: "What is the quick evaluation pattern for a definite integral?",
          answer: "Antiderivative at top minus antiderivative at bottom.",
        },
        {
          prompt: "Derivative of integral from 0 to x of cos t dt?",
          answer: "cos x",
        },
      ],
      memoryHook: "Top minus bottom, or unwrap to the inside.",
      tags: ["integrals", "ftc", "evaluation"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "u-substitution",
      chapter: "Chapter 4: Integrals",
      unit: "Integrals",
      topic: "u-substitution basic intro",
      name: "u-Substitution",
      order: 35,
      useItWhen: "an inside expression and its derivative both show up",
      looksLike: "integral of 2x(x^2 + 1)^5 dx or integral of cos(3x) dx",
      doThis: "let u be the inside, swap to du, integrate, switch back",
      thinkOfItAs: "the chain rule running backward",
      watchOutFor: "choosing the wrong u or forgetting du",
      rememberThis: "inside plus inside-derivative is the green light",
      quickExample: {
        problem: "Integral of 2x(x^2 + 1)^5 dx",
        move: "Let u = x^2 + 1 so du = 2x dx.",
      },
      typicalProblemShapes: [
        "A big outer power with a neat inside derivative nearby",
        "Trig, exponential, or polynomial compositions inside an integral",
      ],
      miniDrill: [
        {
          prompt: "For integral of 6x(3x^2 + 4)^8 dx, what is the natural u?",
          answer: "u = 3x^2 + 4",
        },
        {
          prompt: "What derivative clue tells you u-sub might work?",
          answer: "The derivative of the inside expression is already present or nearly present.",
        },
      ],
      memoryHook: "Inside plus derivative means sub it out.",
      tags: ["integrals", "u-substitution", "chain-rule-backward"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "mean-value-theorem",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Mean Value Theorem",
      name: "Mean Value Theorem",
      order: 36,
      useItWhen: "you need a guaranteed average-slope-meets-instant-slope point",
      looksLike: "continuous on [a,b], differentiable on (a,b)",
      doThis: "check the conditions, then match secant slope to tangent slope",
      thinkOfItAs: "somewhere the speedometer matches the trip average",
      watchOutFor: "using it when the function has a corner or break",
      rememberThis: "average slope shows up as a tangent slope",
      quickExample: {
        problem: "What slope do you compare in MVT?",
        move: "The secant slope across the interval.",
      },
      typicalProblemShapes: [
        "A closed interval and an open interval condition check",
        "Questions asking to prove some c exists",
      ],
      miniDrill: [
        { prompt: "What two conditions must you check first?", answer: "Continuous on the closed interval and differentiable on the open interval." },
        { prompt: "What slope gets matched inside the interval?", answer: "The average secant slope." },
      ],
      memoryHook: "Average slope shows up somewhere inside.",
      tags: ["calc1", "applications", "mvt"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "curve-sketching",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Curve sketching summary",
      name: "Curve Sketching",
      order: 37,
      useItWhen: "you need the whole graph story",
      looksLike: "intercepts, asymptotes, increasing, concavity, extrema",
      doThis: "find the key features in a fixed order and build the graph",
      thinkOfItAs: "a checklist, not a guess",
      watchOutFor: "jumping to the sketch without checking derivative signs",
      rememberThis: "features first, sketch second",
      quickExample: {
        problem: "What comes before sketching the final shape?",
        move: "A feature checklist.",
      },
      typicalProblemShapes: [
        "Prompts asking for a full graph analysis",
        "Functions with asymptotes, extrema, and bend changes",
      ],
      miniDrill: [
        { prompt: "Do you want derivative sign charts here?", answer: "Yes." },
        { prompt: "Should asymptotes be checked before sketching?", answer: "Yes." },
      ],
      memoryHook: "Graph by checklist, not vibes.",
      tags: ["calc1", "applications", "curve-sketching"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "newtons-method",
      chapter: "Chapter 3: Applications of Differentiation",
      unit: "Applications",
      topic: "Newton's Method",
      name: "Newton's Method",
      order: 38,
      useItWhen: "you want a root approximation fast",
      looksLike: "x_(n+1) = x_n - f(x_n)/f'(x_n)",
      doThis: "start near the root and keep jumping with tangent lines",
      thinkOfItAs: "walking to the x-axis by tangents",
      watchOutFor: "starting too far away or dividing by a tiny derivative",
      rememberThis: "next x comes from the tangent line",
      quickExample: {
        problem: "What does Newton's Method use to improve a guess?",
        move: "A tangent-line step.",
      },
      typicalProblemShapes: [
        "Approximate a zero of a function",
        "Iteration formulas built from f and f-prime",
      ],
      miniDrill: [
        { prompt: "What two function pieces does Newton's Method need?", answer: "f(x) and f-prime(x)." },
        { prompt: "Does Newton's Method find an exact answer every time?", answer: "No. It is an approximation method." },
      ],
      memoryHook: "Tangent step, then tangent step again.",
      tags: ["calc1", "applications", "newtons-method"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "areas-between-curves",
      chapter: "Chapter 5: Applications of Integration",
      unit: "Applications of Integration",
      topic: "Areas between curves",
      name: "Area Between Curves",
      order: 39,
      useItWhen: "you need the space trapped between two graphs",
      looksLike: "top function minus bottom function",
      doThis: "pick the top and bottom, then integrate top minus bottom",
      thinkOfItAs: "subtracting stacked layers",
      watchOutFor: "using the lower curve first",
      rememberThis: "top minus bottom",
      quickExample: {
        problem: "What is the usual setup for area between y = f(x) and y = g(x)?",
        move: "Integrate top minus bottom.",
      },
      typicalProblemShapes: [
        "Two curves crossing over an interval",
        "A shaded region between graphs",
      ],
      miniDrill: [
        { prompt: "Which function goes first in the integrand?", answer: "The top function." },
        { prompt: "If left-right is easier, can you integrate with respect to y instead?", answer: "Yes." },
      ],
      memoryHook: "Area between curves = top minus bottom.",
      tags: ["calc1", "integration", "area-between-curves"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "disk-washer-method",
      chapter: "Chapter 5: Applications of Integration",
      unit: "Applications of Integration",
      topic: "Volumes by disks and washers",
      name: "Disk / Washer Method",
      order: 40,
      useItWhen: "a region spins and slices are circles or rings",
      looksLike: "volume of revolution around an axis",
      doThis: "use big radius squared minus small radius squared",
      thinkOfItAs: "stacking coins or donuts",
      watchOutFor: "using diameter instead of radius",
      rememberThis: "washer = big circle minus little circle",
      quickExample: {
        problem: "What changes from disk to washer?",
        move: "A hole appears, so subtract inner radius squared.",
      },
      typicalProblemShapes: [
        "Rotation around the x-axis or y-axis",
        "Cross sections perpendicular to the axis",
      ],
      miniDrill: [
        { prompt: "What power hits the radius?", answer: "Squared." },
        { prompt: "What constant sits in front?", answer: "Pi." },
      ],
      memoryHook: "Disk is one radius. Washer is outer minus inner.",
      tags: ["calc1", "integration", "volume", "washers"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "shell-method",
      chapter: "Chapter 5: Applications of Integration",
      unit: "Applications of Integration",
      topic: "Volumes by cylindrical shells",
      name: "Shell Method",
      order: 41,
      useItWhen: "spinning makes thin cylindrical shells easier than washers",
      looksLike: "2 pi times radius times height",
      doThis: "use shell radius and shell height, then integrate",
      thinkOfItAs: "wrapping the solid in thin paper tubes",
      watchOutFor: "mixing shell height with shell radius",
      rememberThis: "shells use radius times height",
      quickExample: {
        problem: "What constant starts the shell formula?",
        move: "2 pi.",
      },
      typicalProblemShapes: [
        "Rotation where washers feel awkward",
        "Slices parallel to the axis of rotation",
      ],
      miniDrill: [
        { prompt: "Shells use radius times what?", answer: "Height." },
        { prompt: "Do shells usually come from slices parallel or perpendicular to the axis?", answer: "Parallel." },
      ],
      memoryHook: "Shells = 2 pi radius height.",
      tags: ["calc1", "integration", "volume", "shells"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "work-integrals",
      chapter: "Chapter 5: Applications of Integration",
      unit: "Applications of Integration",
      topic: "Work",
      name: "Work as an Integral",
      order: 42,
      useItWhen: "force changes across distance",
      looksLike: "springs, lifting, pumping, variable force",
      doThis: "force times tiny distance, then integrate",
      thinkOfItAs: "adding tiny pushes",
      watchOutFor: "using one constant force when the force changes",
      rememberThis: "variable force means integrate force",
      quickExample: {
        problem: "What is the tiny piece in a work integral?",
        move: "Force times small distance.",
      },
      typicalProblemShapes: [
        "Hooke's Law spring problems",
        "Lifting chains, ropes, or liquids",
      ],
      miniDrill: [
        { prompt: "If force changes with x, do you multiply once or integrate?", answer: "Integrate." },
        { prompt: "What law often appears with springs?", answer: "Hooke's Law." },
      ],
      memoryHook: "Changing force means add tiny pushes.",
      tags: ["calc1", "integration", "work"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "average-value-function",
      chapter: "Chapter 5: Applications of Integration",
      unit: "Applications of Integration",
      topic: "Average value of a function",
      name: "Average Value of a Function",
      order: 43,
      useItWhen: "you need the average output over an interval",
      looksLike: "1 over b-a times an integral",
      doThis: "take the total from the integral, then divide by interval length",
      thinkOfItAs: "area turned into average height",
      watchOutFor: "forgetting the divide-by-length step",
      rememberThis: "average = integral divided by interval width",
      quickExample: {
        problem: "After the integral, what do you still divide by?",
        move: "b minus a.",
      },
      typicalProblemShapes: [
        "Average temperature, speed, or value over time",
        "A direct average-value formula prompt",
      ],
      miniDrill: [
        { prompt: "What does the integral give first?", answer: "The total accumulation." },
        { prompt: "What turns that total into an average?", answer: "Divide by interval length." },
      ],
      memoryHook: "Average height = total area divided by width.",
      tags: ["calc1", "integration", "average-value"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "limit-laws",
      chapter: "Chapter 1: Functions and Limits",
      unit: "Limits",
      topic: "Calculating limits using limit laws",
      name: "Limit Laws",
      order: 44,
      useItWhen: "the limit can be broken into smaller easy pieces",
      looksLike: "sum, difference, product, quotient, or powers inside a limit",
      doThis: "split the limit apart and simplify piece by piece",
      thinkOfItAs: "breaking one big box into small boxes",
      watchOutFor: "using the quotient law when the bottom limit is 0",
      rememberThis: "split what you can, then plug",
      quickExample: {
        problem: "Limit of (x^2 + 3x) as x goes to 2",
        move: "Take the limit of each term, then add.",
      },
      typicalProblemShapes: [
        "A polynomial built from smaller terms",
        "A fraction where the bottom limit stays nonzero",
      ],
      miniDrill: [
        {
          prompt: "Can you split the limit of a sum into two limits?",
          answer: "Yes.",
        },
        {
          prompt: "When does the quotient law break?",
          answer: "When the denominator limit is 0.",
        },
      ],
      memoryHook: "Break the limit before you battle it.",
      tags: ["calc1", "limits", "limit-laws"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "derivative-as-function",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "The derivative as a function",
      name: "Derivative Function",
      order: 45,
      useItWhen: "you want the rule for slope, not just one slope",
      looksLike: "f-prime of x or dy/dx",
      doThis: "differentiate once, then treat the result like a new function",
      thinkOfItAs: "a slope machine built from the original function",
      watchOutFor: "finding the slope at one point when the problem wants the full derivative",
      rememberThis: "f-prime gives slope everywhere it exists",
      quickExample: {
        problem: "If f(x) = x^3, what is the derivative function?",
        move: "f-prime(x) = 3x^2.",
      },
      typicalProblemShapes: [
        "Find f-prime(x), not just f-prime at a number",
        "A graph question asking where slope is positive or negative",
      ],
      miniDrill: [
        {
          prompt: "Is f-prime a number or a new function?",
          answer: "A new function.",
        },
        {
          prompt: "What does f-prime tell you?",
          answer: "The slope behavior of the original function.",
        },
      ],
      memoryHook: "Differentiate once, get a slope map.",
      tags: ["calc1", "derivatives", "f-prime"],
      difficulty: "Starter",
    }),
    makeCalcCard({
      id: "trig-derivatives",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Derivatives of trigonometric functions",
      name: "Trig Derivatives",
      order: 46,
      useItWhen: "sine, cosine, tangent, or friends show up",
      looksLike: "sin x, cos x, tan x, sec x",
      doThis: "use the standard trig derivative patterns, then chain rule if needed",
      thinkOfItAs: "a small list you memorize and deploy fast",
      watchOutFor: "forgetting the negative on d/dx of cos x",
      rememberThis: "sin goes to cos, cos goes to minus sin",
      quickExample: {
        problem: "Derivative of cos x",
        move: "It is minus sin x.",
      },
      typicalProblemShapes: [
        "Basic trig functions by themselves",
        "Trig functions with an inside expression like sin(3x)",
      ],
      miniDrill: [
        {
          prompt: "What is d/dx of sin x?",
          answer: "cos x.",
        },
        {
          prompt: "What is the trap on d/dx of cos x?",
          answer: "Missing the negative sign.",
        },
      ],
      memoryHook: "Sin to cos. Cos to minus sin.",
      tags: ["calc1", "derivatives", "trig"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "differentials",
      chapter: "Chapter 2: Derivatives",
      unit: "Derivatives",
      topic: "Linear approximations and differentials",
      name: "Differentials",
      order: 47,
      useItWhen: "you need a fast small-change estimate",
      looksLike: "dy = f-prime(x) dx",
      doThis: "take the derivative, multiply by the tiny input change, and estimate",
      thinkOfItAs: "zoomed-in math where curves act almost straight",
      watchOutFor: "using big changes as if the linear estimate stays perfect",
      rememberThis: "small dx gives a handy dy estimate",
      quickExample: {
        problem: "How do you estimate a small output change?",
        move: "Use dy = f-prime(x) dx.",
      },
      typicalProblemShapes: [
        "Approximate how much y changes when x changes a little",
        "Estimate error or quick nearby values",
      ],
      miniDrill: [
        {
          prompt: "What two pieces make dy?",
          answer: "f-prime(x) and dx.",
        },
        {
          prompt: "Do differentials work best for small or large changes?",
          answer: "Small changes.",
        },
      ],
      memoryHook: "Tiny input change, derivative times dx.",
      tags: ["calc1", "derivatives", "differentials", "linearization"],
      difficulty: "Standard",
    }),
    makeCalcCard({
      id: "area-distance-problems",
      chapter: "Chapter 4: Integrals",
      unit: "Integrals",
      topic: "Area and distance problems",
      name: "Area and Distance Problems",
      order: 48,
      useItWhen: "you need total accumulation from lots of tiny pieces",
      looksLike: "area under a curve or velocity adding into distance",
      doThis: "slice it into tiny pieces, add with an integral, then interpret the result",
      thinkOfItAs: "turning many little pieces into one total",
      watchOutFor: "mixing signed area with total distance",
      rememberThis: "integrals add tiny pieces into a total",
      quickExample: {
        problem: "What does the integral of velocity give first?",
        move: "Net change in position.",
      },
      typicalProblemShapes: [
        "Area under a rate graph",
        "Velocity over time turning into displacement or distance",
      ],
      miniDrill: [
        {
          prompt: "Does a definite integral add many tiny pieces?",
          answer: "Yes.",
        },
        {
          prompt: "For total distance, do negative velocity pieces stay negative?",
          answer: "No. Use absolute value thinking.",
        },
      ],
      memoryHook: "Integral = total from tiny pieces.",
      tags: ["calc1", "integrals", "accumulation", "distance"],
      difficulty: "Starter",
    }),
  ],
};
