import type { BubbleCard, CourseContent } from "@/content/schema";

function makeLinearCard(
  card: Omit<BubbleCard, "subject" | "course" | "courseCode">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Introduction to Linear Algebra",
    courseCode: "MATH 3A",
    ...card,
  };
}

export const linearAlgebraCourse: CourseContent = {
  id: "linear-algebra",
  subject: "Mathematics",
  title: "Introduction to Linear Algebra",
  institution: "UCI",
  courseCodes: ["MATH 3A"],
  aliases: ["Linear Algebra"],
  shortDescription:
    "Matrices, vector spaces, and eigen ideas taught as recognition-first moves.",
  units: [
    "Systems and Row Reduction",
    "Matrices",
    "Determinants",
    "Vector Spaces",
    "Orthogonality",
    "Transformations and Eigen",
  ],
  chapters: [
    "Chapter 1: Systems and Row Reduction",
    "Chapter 2: Matrix Algebra",
    "Chapter 3: Determinants",
    "Chapter 4: Vector Spaces",
    "Chapter 5: Orthogonality",
    "Chapter 6: Eigenvalues and Linear Transformations",
  ],
  cards: [
    makeLinearCard({
      id: "la-linear-systems",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Systems of linear equations",
      name: "Linear Systems",
      order: 1,
      useItWhen: "several equations are tied to the same variables",
      looksLike: "x + y = 3, 2x - y = 1, more equations than one line",
      doThis: "organize the system and solve it together, not one line at a time",
      thinkOfItAs: "one puzzle with many clues",
      watchOutFor: "treating each equation like a separate problem",
      rememberThis: "same variables means one system",
      quickExample: {
        problem: "Two equations, two unknowns. What is the big setup?",
        move: "Treat it as one system and line up the variables.",
      },
      typicalProblemShapes: [
        "A block of equations sharing x, y, z",
        "Questions asking for one solution, no solution, or infinitely many",
      ],
      miniDrill: [
        {
          prompt: "If three equations share x, y, z, is that one system or three separate jobs?",
          answer: "One system.",
        },
        {
          prompt: "What is the first recognition clue here?",
          answer: "Same variables repeated across several equations.",
        },
      ],
      memoryHook: "Shared variables means shared system.",
      tags: ["linear-algebra", "systems", "equations"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-augmented-matrix",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Augmented matrix",
      name: "Augmented Matrix",
      order: 2,
      useItWhen: "you want the system in compact matrix form",
      looksLike: "[coefficients | constants]",
      doThis: "strip the variables, keep the numbers, and use the bar for answers",
      thinkOfItAs: "the system with the words removed",
      watchOutFor: "mixing coefficient columns with the answer column",
      rememberThis: "left side coefficients, right side constants",
      quickExample: {
        problem: "x + 2y = 5 and 3x - y = 4",
        move: "Turn it into an augmented matrix with a constant column on the right.",
      },
      typicalProblemShapes: [
        "A system rewritten as a rectangle of numbers",
        "Row operations done on a matrix instead of equations",
      ],
      miniDrill: [
        {
          prompt: "What does the last column usually hold?",
          answer: "The constants.",
        },
        {
          prompt: "Do variable names appear inside the augmented matrix?",
          answer: "No. Just the numbers.",
        },
      ],
      memoryHook: "Numbers only, answers on the right.",
      tags: ["linear-algebra", "augmented-matrix", "systems"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-row-reduction",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Row reduction",
      name: "Row Reduction",
      order: 3,
      useItWhen: "you need to clean a system into an easier form",
      looksLike: "swap rows, scale rows, add multiples of rows",
      doThis: "use legal row moves until pivots stand out",
      thinkOfItAs: "clearing traffic so the important numbers show up",
      watchOutFor: "doing a move to one row but not updating the whole row",
      rememberThis: "row moves clean the system, not change it",
      quickExample: {
        problem: "A messy augmented matrix with lots of nonzero entries",
        move: "Use row operations to create pivot positions and zeros.",
      },
      typicalProblemShapes: [
        "Gaussian elimination",
        "Questions asking for REF or RREF",
      ],
      miniDrill: [
        {
          prompt: "Can you swap two rows?",
          answer: "Yes.",
        },
        {
          prompt: "Why row reduce at all?",
          answer: "To make the solution structure easier to read.",
        },
      ],
      memoryHook: "Clean the rows until the structure shows.",
      tags: ["linear-algebra", "row-reduction", "elimination"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-pivots-free-variables",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Pivot and free variables",
      name: "Pivot vs Free Variables",
      order: 4,
      useItWhen: "the reduced matrix is finished and you need the solution shape",
      looksLike: "some columns have pivots and some do not",
      doThis: "mark pivot columns, then let the nonpivot columns become free",
      thinkOfItAs: "pivot columns lead, free columns roam",
      watchOutFor: "calling every variable a pivot variable",
      rememberThis: "no pivot in the column means free variable",
      quickExample: {
        problem: "A reduced matrix has pivots in columns 1 and 3 only",
        move: "Columns 2 and 4 are free.",
      },
      typicalProblemShapes: [
        "RREF with one or more columns missing pivots",
        "Parametric solution questions",
      ],
      miniDrill: [
        {
          prompt: "What creates parameters in the answer?",
          answer: "Free variables.",
        },
        {
          prompt: "How do you spot a pivot variable?",
          answer: "Its column has a pivot.",
        },
      ],
      memoryHook: "No pivot, free variable.",
      tags: ["linear-algebra", "pivots", "free-variables"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-matrix-operations",
      chapter: "Chapter 2: Matrix Algebra",
      unit: "Matrices",
      topic: "Matrix addition and scalar multiplication",
      name: "Basic Matrix Operations",
      order: 5,
      useItWhen: "matrices have the same shape or a scalar is scaling the matrix",
      looksLike: "A + B, 3A",
      doThis: "add entry by entry or multiply every entry by the scalar",
      thinkOfItAs: "spreadsheet arithmetic",
      watchOutFor: "adding matrices with different sizes",
      rememberThis: "same size to add, scale every entry",
      quickExample: {
        problem: "Add two 2 by 2 matrices",
        move: "Match each entry with the one in the same spot.",
      },
      typicalProblemShapes: [
        "Two same-sized matrices being added",
        "A single number multiplying the whole matrix",
      ],
      miniDrill: [
        {
          prompt: "Can a 2 by 3 matrix add to a 3 by 2 matrix?",
          answer: "No.",
        },
        {
          prompt: "What does scalar multiplication touch?",
          answer: "Every entry.",
        },
      ],
      memoryHook: "Add by spot. Scale every slot.",
      tags: ["linear-algebra", "matrices", "operations"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-matrix-multiplication",
      chapter: "Chapter 2: Matrix Algebra",
      unit: "Matrices",
      topic: "Matrix multiplication",
      name: "Matrix Multiplication",
      order: 6,
      useItWhen: "you are composing matrix actions",
      looksLike: "AB with inside dimensions matching",
      doThis: "row by column, dot each row with each column",
      thinkOfItAs: "rows meet columns and make new entries",
      watchOutFor: "multiplying entry by entry or ignoring size mismatch",
      rememberThis: "inside sizes must match",
      quickExample: {
        problem: "Multiply a 2 by 3 matrix by a 3 by 4 matrix",
        move: "Legal because the inside 3 and 3 match.",
      },
      typicalProblemShapes: [
        "AB where size compatibility matters first",
        "Products that change the matrix size",
      ],
      miniDrill: [
        {
          prompt: "Can a 3 by 2 matrix multiply a 4 by 3 matrix on the right?",
          answer: "No. The inside sizes do not match.",
        },
        {
          prompt: "What rule builds one entry of AB?",
          answer: "Row by column.",
        },
      ],
      memoryHook: "Inside match, then row by column.",
      tags: ["linear-algebra", "matrix-multiplication", "matrices"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-identity-matrix",
      chapter: "Chapter 2: Matrix Algebra",
      unit: "Matrices",
      topic: "Identity matrix",
      name: "Identity Matrix",
      order: 7,
      useItWhen: "you need the do-nothing matrix",
      looksLike: "1s on the diagonal, 0s elsewhere",
      doThis: "recognize it as the matrix version of 1",
      thinkOfItAs: "the neutral setting",
      watchOutFor: "using the wrong size identity matrix",
      rememberThis: "identity leaves things alone",
      quickExample: {
        problem: "What happens to Ax if A is the identity?",
        move: "Nothing changes.",
      },
      typicalProblemShapes: [
        "Diagonal ones and zero elsewhere",
        "IA = A and AI = A",
      ],
      miniDrill: [
        {
          prompt: "What is the matrix version of multiplying by 1?",
          answer: "The identity matrix.",
        },
        {
          prompt: "Does a 2 by 2 identity work for a 3 by 3 matrix?",
          answer: "No.",
        },
      ],
      memoryHook: "Identity = matrix one.",
      tags: ["linear-algebra", "identity", "matrices"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-inverse-matrix",
      chapter: "Chapter 2: Matrix Algebra",
      unit: "Matrices",
      topic: "Inverse matrix",
      name: "Inverse Matrix",
      order: 8,
      useItWhen: "you want to undo a matrix action",
      looksLike: "A inverse, AA inverse = I",
      doThis: "check that the matrix is invertible, then use the inverse to reverse the action",
      thinkOfItAs: "the matrix undo button",
      watchOutFor: "assuming every square matrix has an inverse",
      rememberThis: "inverse only exists when the matrix is invertible",
      quickExample: {
        problem: "How do you undo Ax = b when A is invertible?",
        move: "Multiply by A inverse.",
      },
      typicalProblemShapes: [
        "Solve Ax = b using matrix language",
        "Questions asking whether a matrix is invertible",
      ],
      miniDrill: [
        {
          prompt: "What should A times A inverse equal?",
          answer: "The identity matrix.",
        },
        {
          prompt: "Does every square matrix have an inverse?",
          answer: "No.",
        },
      ],
      memoryHook: "Inverse means undo.",
      tags: ["linear-algebra", "inverse", "matrices"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-determinant",
      chapter: "Chapter 3: Determinants",
      unit: "Determinants",
      topic: "Determinant",
      name: "Determinant",
      order: 9,
      useItWhen: "you need a fast invertibility signal or area-volume scaling clue",
      looksLike: "det A or bars around a square matrix",
      doThis: "compute the determinant and check whether it is zero",
      thinkOfItAs: "a matrix health check",
      watchOutFor: "trying to take determinants of nonsquare matrices",
      rememberThis: "det zero usually means not invertible",
      quickExample: {
        problem: "A 2 by 2 matrix has determinant 0. What is the big conclusion?",
        move: "It is not invertible.",
      },
      typicalProblemShapes: [
        "Square matrices only",
        "Invertibility checks and area-scaling questions",
      ],
      miniDrill: [
        {
          prompt: "Can a rectangular matrix have a determinant?",
          answer: "No.",
        },
        {
          prompt: "What is the fast alarm value for determinants?",
          answer: "Zero.",
        },
      ],
      memoryHook: "Det zero means trouble.",
      tags: ["linear-algebra", "determinant", "invertibility"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-rank",
      chapter: "Chapter 3: Determinants",
      unit: "Determinants",
      topic: "Rank",
      name: "Rank",
      order: 10,
      useItWhen: "you want the number of independent pivot directions",
      looksLike: "rank A, pivot count, nonzero rows in echelon form",
      doThis: "row reduce and count pivot positions",
      thinkOfItAs: "how much real information the matrix keeps",
      watchOutFor: "counting every row instead of pivot rows",
      rememberThis: "rank is pivot count",
      quickExample: {
        problem: "How do you read rank from RREF?",
        move: "Count the pivots.",
      },
      typicalProblemShapes: [
        "Pivot counting after row reduction",
        "Questions about full rank or rank deficiency",
      ],
      miniDrill: [
        {
          prompt: "What is rank in one fast phrase?",
          answer: "The number of pivots.",
        },
        {
          prompt: "Does a zero row add to the rank?",
          answer: "No.",
        },
      ],
      memoryHook: "Rank = pivots that survived.",
      tags: ["linear-algebra", "rank", "row-reduction"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-vector-space",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Vector space idea",
      name: "Vector Space",
      order: 11,
      useItWhen: "the set is supposed to support vector addition and scalar scaling",
      looksLike: "sets of vectors, polynomials, matrices, or functions",
      doThis: "ask whether the set stays closed under add and scalar multiply",
      thinkOfItAs: "a legal playground for vector moves",
      watchOutFor: "assuming every set of vectors is automatically a vector space",
      rememberThis: "closed under add and scale",
      quickExample: {
        problem: "A set of vectors is proposed. What is the first check?",
        move: "See whether addition and scalar multiplication stay inside the set.",
      },
      typicalProblemShapes: [
        "Is this set a vector space?",
        "Sets defined by equations or restrictions",
      ],
      miniDrill: [
        {
          prompt: "What two moves must stay inside the set?",
          answer: "Addition and scalar multiplication.",
        },
        {
          prompt: "If scaling can leave the set, is it a vector space?",
          answer: "No.",
        },
      ],
      memoryHook: "Vector space means add and scale stay legal.",
      tags: ["linear-algebra", "vector-space", "closure"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-subspace-test",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Subspace test",
      name: "Subspace Test",
      order: 12,
      useItWhen: "the problem asks whether a set inside a vector space is itself a vector space",
      looksLike: "show W is a subspace of V",
      doThis: "check zero, closed under add, closed under scalar multiply",
      thinkOfItAs: "the fast bouncer test",
      watchOutFor: "forgetting to check the zero vector",
      rememberThis: "zero, add, scale",
      quickExample: {
        problem: "A set is defined by a linear equation. What test should you run?",
        move: "The subspace test.",
      },
      typicalProblemShapes: [
        "Sets defined by linear conditions",
        "Subspace or not subspace questions",
      ],
      miniDrill: [
        {
          prompt: "What are the three quick checks?",
          answer: "Zero, addition, scalar multiplication.",
        },
        {
          prompt: "If the zero vector is missing, can it be a subspace?",
          answer: "No.",
        },
      ],
      memoryHook: "Zero, add, scale.",
      tags: ["linear-algebra", "subspace", "vector-space"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-span",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Span",
      name: "Span",
      order: 13,
      useItWhen: "you need all linear combinations of given vectors",
      looksLike: "span of v1, v2, v3",
      doThis: "allow arbitrary scalar combinations and ask what space they can reach",
      thinkOfItAs: "the reach of the vectors",
      watchOutFor: "thinking span means just the listed vectors themselves",
      rememberThis: "span means all linear combinations",
      quickExample: {
        problem: "What does span of two nonparallel vectors in R2 usually give?",
        move: "Usually the whole plane.",
      },
      typicalProblemShapes: [
        "What space do these vectors generate?",
        "Questions about reaching a target vector by combinations",
      ],
      miniDrill: [
        {
          prompt: "Does span mean one combination or all combinations?",
          answer: "All combinations.",
        },
        {
          prompt: "What is the main question behind span?",
          answer: "What can these vectors build?",
        },
      ],
      memoryHook: "Span = everything these vectors can build.",
      tags: ["linear-algebra", "span", "vector-space"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-linear-independence",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Linear independence",
      name: "Linear Independence",
      order: 14,
      useItWhen: "you need to know whether one vector is secretly built from the others",
      looksLike: "independent or dependent set",
      doThis: "set the combination equal to zero and test whether only the trivial solution works",
      thinkOfItAs: "each vector pulling its own weight",
      watchOutFor: "calling a set independent when one vector is redundant",
      rememberThis: "only the zero-coefficient solution means independent",
      quickExample: {
        problem: "How do you test independence fast?",
        move: "Solve c1v1 + c2v2 + ... = 0.",
      },
      typicalProblemShapes: [
        "A list of vectors tested for redundancy",
        "Basis questions that ask if vectors are independent first",
      ],
      miniDrill: [
        {
          prompt: "What is the bad sign for independence?",
          answer: "A nontrivial solution to the zero combination.",
        },
        {
          prompt: "If one vector is a combination of the others, independent or dependent?",
          answer: "Dependent.",
        },
      ],
      memoryHook: "Redundant means dependent.",
      tags: ["linear-algebra", "independence", "span"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-basis-dimension",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Basis and dimension",
      name: "Basis and Dimension",
      order: 15,
      useItWhen: "you need the main building blocks and the size of the space",
      looksLike: "find a basis, what is the dimension",
      doThis: "look for a set that is both independent and spanning, then count it",
      thinkOfItAs: "the smallest full toolkit",
      watchOutFor: "using a set that spans but is not independent",
      rememberThis: "basis = independent + spanning",
      quickExample: {
        problem: "What does dimension count?",
        move: "How many basis vectors you need.",
      },
      typicalProblemShapes: [
        "Find a basis for a subspace",
        "Count the dimension after finding pivots or basis vectors",
      ],
      miniDrill: [
        {
          prompt: "What two jobs must a basis do?",
          answer: "Span the space and stay independent.",
        },
        {
          prompt: "What is dimension in one line?",
          answer: "The number of vectors in a basis.",
        },
      ],
      memoryHook: "Basis builds the space without extras.",
      tags: ["linear-algebra", "basis", "dimension"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-dot-orthogonality",
      chapter: "Chapter 5: Orthogonality",
      unit: "Orthogonality",
      topic: "Dot product and orthogonality",
      name: "Orthogonality",
      order: 16,
      useItWhen: "you need perpendicular vectors or right-angle geometry",
      looksLike: "u dot v = 0, orthogonal set",
      doThis: "compute the dot product and check whether it becomes zero",
      thinkOfItAs: "vectors crossing at a clean right angle",
      watchOutFor: "assuming small dot product means exactly orthogonal",
      rememberThis: "dot zero means perpendicular",
      quickExample: {
        problem: "How do you test whether two vectors are perpendicular?",
        move: "Take their dot product.",
      },
      typicalProblemShapes: [
        "Perpendicular vectors",
        "Orthogonal sets and projections",
      ],
      miniDrill: [
        {
          prompt: "What is the fast orthogonality test?",
          answer: "Dot product equals zero.",
        },
        {
          prompt: "Does orthogonal mean parallel?",
          answer: "No. It means perpendicular.",
        },
      ],
      memoryHook: "Dot zero, right angle.",
      tags: ["linear-algebra", "orthogonality", "dot-product"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-projection",
      chapter: "Chapter 5: Orthogonality",
      unit: "Orthogonality",
      topic: "Projection",
      name: "Projection",
      order: 17,
      useItWhen: "you need the shadow of one vector on another direction",
      looksLike: "proj of u onto v",
      doThis: "take the component in the target direction",
      thinkOfItAs: "dropping a shadow onto a line",
      watchOutFor: "forgetting which vector is the direction target",
      rememberThis: "projection keeps only the along-the-line part",
      quickExample: {
        problem: "What does a projection keep?",
        move: "Only the part pointing along the chosen direction.",
      },
      typicalProblemShapes: [
        "Best approximation on a line",
        "Vector decomposition into along and perpendicular parts",
      ],
      miniDrill: [
        {
          prompt: "What picture helps here most?",
          answer: "A shadow landing on a line.",
        },
        {
          prompt: "Does projection keep the sideways part?",
          answer: "No.",
        },
      ],
      memoryHook: "Projection = shadow on the line.",
      tags: ["linear-algebra", "projection", "orthogonality"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-linear-transformation",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "Linear transformations",
      name: "Linear Transformation",
      order: 18,
      useItWhen: "a rule takes vectors in and sends vectors out in a structure-preserving way",
      looksLike: "T(x), matrix times vector, maps between vector spaces",
      doThis: "check whether the rule respects add and scalar multiply",
      thinkOfItAs: "a machine that bends space without breaking linear rules",
      watchOutFor: "calling every vector rule linear",
      rememberThis: "linear means add and scale survive",
      quickExample: {
        problem: "How do you test whether T is linear?",
        move: "Check additivity and scalar compatibility.",
      },
      typicalProblemShapes: [
        "Rules that map vectors to vectors",
        "Questions asking if a transformation is linear",
      ],
      miniDrill: [
        {
          prompt: "What two linear tests matter most?",
          answer: "Additivity and scalar multiplication.",
        },
        {
          prompt: "Is every vector-valued rule automatically linear?",
          answer: "No.",
        },
      ],
      memoryHook: "Linear rule keeps add and scale.",
      tags: ["linear-algebra", "linear-transformation", "matrices"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-eigenvalues-eigenvectors",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "Eigenvalues and eigenvectors",
      name: "Eigenvalues and Eigenvectors",
      order: 19,
      useItWhen: "a transformation stretches a vector without turning it away from its line",
      looksLike: "Av = lambda v",
      doThis: "look for directions that stay on the same line after the matrix acts",
      thinkOfItAs: "special directions the matrix respects",
      watchOutFor: "thinking every vector is an eigenvector",
      rememberThis: "same line, new size",
      quickExample: {
        problem: "What makes v an eigenvector?",
        move: "Av lands on the same line as v.",
      },
      typicalProblemShapes: [
        "Av = lambda v",
        "Find eigenvalues or eigenvectors of a matrix",
      ],
      miniDrill: [
        {
          prompt: "What stays the same for an eigenvector?",
          answer: "Its direction line.",
        },
        {
          prompt: "What changes for an eigenvector?",
          answer: "Its size, by the eigenvalue.",
        },
      ],
      memoryHook: "Eigenvector keeps the line.",
      tags: ["linear-algebra", "eigenvalues", "eigenvectors"],
      difficulty: "Stretch",
    }),
    makeLinearCard({
      id: "la-diagonalization",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "Diagonalization",
      name: "Diagonalization",
      order: 20,
      useItWhen: "you want a matrix rewritten in a much easier eigen-basis form",
      looksLike: "A = P D P inverse",
      doThis: "collect enough independent eigenvectors to build P",
      thinkOfItAs: "changing into the matrix's favorite coordinates",
      watchOutFor: "trying to diagonalize without enough independent eigenvectors",
      rememberThis: "enough eigenvectors makes the matrix go diagonal",
      quickExample: {
        problem: "What is the big requirement for diagonalization?",
        move: "You need enough independent eigenvectors.",
      },
      typicalProblemShapes: [
        "A = P D P inverse setup",
        "Questions asking whether a matrix is diagonalizable",
      ],
      miniDrill: [
        {
          prompt: "What kind of matrix sits in the middle?",
          answer: "A diagonal matrix.",
        },
        {
          prompt: "What usually blocks diagonalization?",
          answer: "Not enough independent eigenvectors.",
        },
      ],
      memoryHook: "Enough eigenvectors unlock diagonal form.",
      tags: ["linear-algebra", "diagonalization", "eigenvalues"],
      difficulty: "Stretch",
    }),
    makeLinearCard({
      id: "la-consistency",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Consistent vs inconsistent systems",
      name: "Consistent vs Inconsistent",
      order: 4.2,
      useItWhen: "row reduction finishes and you need to classify the system",
      looksLike: "a row like 0 0 0 | 1 or a clean solved system",
      doThis: "look for impossible rows first",
      thinkOfItAs: "does the system still make sense or does it contradict itself",
      watchOutFor: "missing the impossible row at the bottom",
      rememberThis: "impossible row means no solution",
      quickExample: {
        problem: "What does 0 = 1 in the last row mean?",
        move: "The system is inconsistent.",
      },
      typicalProblemShapes: [
        "RREF classification questions",
        "One solution, no solution, or infinitely many solution checks",
      ],
      miniDrill: [
        {
          prompt: "What is the fastest no-solution clue?",
          answer: "A contradictory row like 0 = 1.",
        },
        {
          prompt: "Can a consistent system have free variables?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Bad row, no solution.",
      tags: ["linear-algebra", "systems", "consistency"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-homogeneous-system",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Homogeneous systems",
      name: "Homogeneous System",
      order: 4.3,
      useItWhen: "the right-hand side is all zeros",
      looksLike: "Ax = 0",
      doThis: "remember the zero solution always exists, then check for free variables",
      thinkOfItAs: "the system with no outside push",
      watchOutFor: "forgetting the trivial solution is always there",
      rememberThis: "Ax = 0 always has at least the zero solution",
      quickExample: {
        problem: "What solution does every homogeneous system have?",
        move: "The trivial zero solution.",
      },
      typicalProblemShapes: [
        "Null space setup",
        "Questions about nontrivial solutions",
      ],
      miniDrill: [
        {
          prompt: "When does a homogeneous system have nontrivial solutions?",
          answer: "When free variables appear.",
        },
        {
          prompt: "Is the zero solution ever missing from Ax = 0?",
          answer: "No.",
        },
      ],
      memoryHook: "Homogeneous means zero always works.",
      tags: ["linear-algebra", "homogeneous", "null-space"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-transpose-symmetric",
      chapter: "Chapter 2: Matrix Algebra",
      unit: "Matrices",
      topic: "Transpose and symmetric matrices",
      name: "Transpose and Symmetric",
      order: 8.2,
      useItWhen: "a matrix flips across the diagonal or gets compared to its transpose",
      looksLike: "A transpose, symmetric matrix, a_ij equals a_ji",
      doThis: "swap rows with columns, then compare",
      thinkOfItAs: "reflecting the matrix in its diagonal mirror",
      watchOutFor: "changing entries instead of just swapping positions",
      rememberThis: "symmetric means equal to its transpose",
      quickExample: {
        problem: "What makes a matrix symmetric?",
        move: "A equals A transpose.",
      },
      typicalProblemShapes: [
        "Compute a transpose",
        "Check whether a square matrix is symmetric",
      ],
      miniDrill: [
        {
          prompt: "What does transpose do first?",
          answer: "It swaps rows and columns.",
        },
        {
          prompt: "Can a non-square matrix be symmetric?",
          answer: "No.",
        },
      ],
      memoryHook: "Transpose flips. Symmetric matches the flip.",
      tags: ["linear-algebra", "transpose", "symmetric"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-cofactor-cramers",
      chapter: "Chapter 3: Determinants",
      unit: "Determinants",
      topic: "Cofactor expansion and Cramer's Rule",
      name: "Cofactor and Cramer's Rule",
      order: 10.2,
      useItWhen: "a determinant is expanded by a row or column or a small system is solved by determinants",
      looksLike: "cofactor signs, replace one column, divide by det A",
      doThis: "pick a smart row or column, and only use Cramer's Rule on small invertible square systems",
      thinkOfItAs: "determinant surgery one row at a time",
      watchOutFor: "using Cramer's Rule when det A is zero",
      rememberThis: "Cramer's Rule only works when det A is not zero",
      quickExample: {
        problem: "What is the first determinant check before Cramer's Rule?",
        move: "Make sure det A is not zero.",
      },
      typicalProblemShapes: [
        "3 by 3 determinant expansions",
        "Small systems solved with determinant formulas",
      ],
      miniDrill: [
        {
          prompt: "What sign pattern guides cofactors?",
          answer: "Alternating plus minus signs.",
        },
        {
          prompt: "Can Cramer's Rule solve a singular system?",
          answer: "No.",
        },
      ],
      memoryHook: "No nonzero determinant, no Cramer's Rule.",
      tags: ["linear-algebra", "cofactor", "cramers-rule", "determinant"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-column-null-space",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Column space and null space",
      name: "Column Space vs Null Space",
      order: 15.2,
      useItWhen: "you need to know what outputs a matrix can make or what inputs it kills",
      looksLike: "Col A, Nul A, Ax = b, Ax = 0",
      doThis: "think outputs for column space and zero-producing inputs for null space",
      thinkOfItAs: "what the matrix can create versus what it wipes out",
      watchOutFor: "mixing up vectors in the domain with vectors in the codomain",
      rememberThis: "column space is outputs, null space is zero inputs",
      quickExample: {
        problem: "What does null space collect?",
        move: "All vectors sent to zero.",
      },
      typicalProblemShapes: [
        "Solve Ax = 0 to describe the null space",
        "Pivot columns used to describe the column space",
      ],
      miniDrill: [
        {
          prompt: "Which space lives in the input side?",
          answer: "The null space.",
        },
        {
          prompt: "Which space describes reachable outputs?",
          answer: "The column space.",
        },
      ],
      memoryHook: "Columns make outputs. Null makes zero.",
      tags: ["linear-algebra", "column-space", "null-space"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-coordinates-change-basis",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Coordinates and change of basis",
      name: "Coordinates and Change of Basis",
      order: 15.3,
      useItWhen: "the same vector is described in a nonstandard basis",
      looksLike: "coordinate vector relative to B, change-of-basis matrix",
      doThis: "treat the basis as the language and convert the vector into that language",
      thinkOfItAs: "same point, different coordinate accent",
      watchOutFor: "forgetting which basis the coordinates belong to",
      rememberThis: "coordinates depend on the basis",
      quickExample: {
        problem: "Do coordinates change when the basis changes?",
        move: "Yes. The vector stays the same, but the description changes.",
      },
      typicalProblemShapes: [
        "Find coordinates relative to a basis",
        "Convert between standard and nonstandard coordinates",
      ],
      miniDrill: [
        {
          prompt: "Does the actual vector change when the basis changes?",
          answer: "No.",
        },
        {
          prompt: "What changes with a new basis?",
          answer: "Its coordinates.",
        },
      ],
      memoryHook: "Same vector, new language.",
      tags: ["linear-algebra", "coordinates", "basis"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-orthonormal-gram-schmidt",
      chapter: "Chapter 5: Orthogonality",
      unit: "Orthogonality",
      topic: "Orthonormal sets and Gram-Schmidt",
      name: "Orthonormal and Gram-Schmidt",
      order: 17.2,
      useItWhen: "you want perpendicular unit vectors from a messy basis",
      looksLike: "orthonormal basis, Gram-Schmidt process",
      doThis: "strip off projections, then normalize",
      thinkOfItAs: "straighten the vectors, then resize them",
      watchOutFor: "normalizing before removing the old direction pieces",
      rememberThis: "subtract projections, then normalize",
      quickExample: {
        problem: "What are the two big stages of Gram-Schmidt?",
        move: "Make vectors orthogonal, then turn them into unit vectors.",
      },
      typicalProblemShapes: [
        "Build an orthonormal basis",
        "Projection-heavy orthogonality problems",
      ],
      miniDrill: [
        {
          prompt: "What does orthonormal mean in one phrase?",
          answer: "Perpendicular and length one.",
        },
        {
          prompt: "What comes after removing projections?",
          answer: "Normalize.",
        },
      ],
      memoryHook: "Straighten, then shrink to 1.",
      tags: ["linear-algebra", "orthonormal", "gram-schmidt"],
      difficulty: "Stretch",
    }),
    makeLinearCard({
      id: "la-least-squares",
      chapter: "Chapter 5: Orthogonality",
      unit: "Orthogonality",
      topic: "Least squares",
      name: "Least Squares",
      order: 17.3,
      useItWhen: "Ax = b has no exact solution and you want the closest fit",
      looksLike: "overdetermined system, best-fit line, A transpose A x = A transpose b",
      doThis: "project onto the column space and solve the normal equations",
      thinkOfItAs: "best possible miss",
      watchOutFor: "treating a no-solution system like it still has an exact answer",
      rememberThis: "least squares finds the closest fit, not a perfect hit",
      quickExample: {
        problem: "When do normal equations show up?",
        move: "When you want the least-squares solution.",
      },
      typicalProblemShapes: [
        "Best-fit line or data fit questions",
        "Overdetermined systems",
      ],
      miniDrill: [
        {
          prompt: "What kind of system often leads to least squares?",
          answer: "A system with more equations than exact solutions.",
        },
        {
          prompt: "Does least squares make the residual exactly zero?",
          answer: "Not usually.",
        },
      ],
      memoryHook: "No exact fit? Take the closest fit.",
      tags: ["linear-algebra", "least-squares", "orthogonality"],
      difficulty: "Stretch",
    }),
    makeLinearCard({
      id: "la-characteristic-polynomial",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "Characteristic polynomial",
      name: "Characteristic Polynomial",
      order: 19.2,
      useItWhen: "you need eigenvalues from a matrix",
      looksLike: "det(A - lambda I) = 0",
      doThis: "set up A minus lambda I, take the determinant, and solve",
      thinkOfItAs: "the eigenvalue finder equation",
      watchOutFor: "forgetting the lambda I part",
      rememberThis: "eigenvalues come from det(A minus lambda I)",
      quickExample: {
        problem: "What equation starts the eigenvalue hunt?",
        move: "det(A - lambda I) = 0.",
      },
      typicalProblemShapes: [
        "Find eigenvalues of a matrix",
        "Characteristic polynomial setup",
      ],
      miniDrill: [
        {
          prompt: "What gets subtracted from A before the determinant?",
          answer: "Lambda times the identity.",
        },
        {
          prompt: "What do the roots of the characteristic polynomial give?",
          answer: "The eigenvalues.",
        },
      ],
      memoryHook: "Subtract lambda I, then solve.",
      tags: ["linear-algebra", "characteristic-polynomial", "eigenvalues"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-echelon-vs-rref",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Echelon form versus reduced echelon form",
      name: "REF vs RREF",
      order: 3.5,
      useItWhen: "a matrix is nearly cleaned up and you need to name the form",
      looksLike: "stair-step pivots, zeros below pivots, maybe zeros above too",
      doThis: "check pivot shape first, then ask whether each pivot is a lone 1",
      thinkOfItAs: "REF is cleaned, RREF is fully polished",
      watchOutFor: "calling a matrix RREF just because it has pivots",
      rememberThis: "RREF means pivot 1s with zeros above and below",
      quickExample: {
        problem: "What extra thing does RREF have that REF may not?",
        move: "Zeros above each pivot too.",
      },
      typicalProblemShapes: [
        "Classify a reduced matrix",
        "Stop row reduction at REF or keep going to RREF",
      ],
      miniDrill: [
        {
          prompt: "Can REF still have nonzero entries above a pivot?",
          answer: "Yes.",
        },
        {
          prompt: "What must every pivot equal in RREF?",
          answer: "1.",
        },
      ],
      memoryHook: "RREF is REF plus cleaner pivots.",
      tags: ["linear-algebra", "rref", "ref", "row-reduction"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-ax-equals-b",
      chapter: "Chapter 1: Systems and Row Reduction",
      unit: "Systems and Row Reduction",
      topic: "Matrix equation Ax = b",
      name: "Ax = b",
      order: 4.5,
      useItWhen: "a system is written as one matrix equation",
      looksLike: "Ax = b, coefficient matrix times variable vector",
      doThis: "read A as the action, x as the unknowns, and b as the target",
      thinkOfItAs: "one machine trying to hit one output",
      watchOutFor: "mixing the role of x and b",
      rememberThis: "Ax = b is the matrix version of a linear system",
      quickExample: {
        problem: "What does b represent in Ax = b?",
        move: "The target output vector.",
      },
      typicalProblemShapes: [
        "Rewrite a system as Ax = b",
        "Ask whether b lies in the column space of A",
      ],
      miniDrill: [
        {
          prompt: "What does x stand for in Ax = b?",
          answer: "The unknown vector.",
        },
        {
          prompt: "What part of Ax = b is fixed data besides A?",
          answer: "b.",
        },
      ],
      memoryHook: "A acts, x is unknown, b is target.",
      tags: ["linear-algebra", "matrix-equation", "systems"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-invertible-matrix-theorem",
      chapter: "Chapter 2: Matrix Algebra",
      unit: "Matrices",
      topic: "Invertible Matrix Theorem",
      name: "Invertible Matrix Theorem",
      order: 8.2,
      useItWhen: "you want many equivalent ways to spot an invertible matrix fast",
      looksLike: "det nonzero, pivots in every column, unique solution, inverse exists",
      doThis: "recognize one invertible clue and cash in the others",
      thinkOfItAs: "one green light unlocks the whole list",
      watchOutFor: "memorizing one test and forgetting the equivalent ones",
      rememberThis: "invertible shows up in many disguises",
      quickExample: {
        problem: "If a square matrix has a pivot in every column, what else is true fast?",
        move: "It is invertible.",
      },
      typicalProblemShapes: [
        "Decide whether a square matrix is invertible",
        "Translate one invertibility fact into another",
      ],
      miniDrill: [
        {
          prompt: "For a square matrix, does det not equal 0 suggest invertible or singular?",
          answer: "Invertible.",
        },
        {
          prompt: "Does invertible mean Ax = 0 only has the trivial solution?",
          answer: "Yes.",
        },
      ],
      memoryHook: "One invertible clue unlocks the whole package.",
      tags: ["linear-algebra", "invertible", "theorem", "matrices"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-lu-factorization",
      chapter: "Chapter 2: Matrix Algebra",
      unit: "Matrices",
      topic: "LU factorization",
      name: "LU Factorization",
      order: 8.6,
      useItWhen: "you solve many systems with the same matrix A",
      looksLike: "A = LU, lower times upper",
      doThis: "factor once, then solve Ly = b and Ux = y",
      thinkOfItAs: "pre-splitting the work into two easier solves",
      watchOutFor: "trying LU before checking whether pivot issues force row swaps",
      rememberThis: "factor once, solve twice",
      quickExample: {
        problem: "Why use LU instead of row reducing from scratch every time?",
        move: "It saves work when A stays the same.",
      },
      typicalProblemShapes: [
        "Repeated Ax = b problems with the same coefficient matrix",
        "Lower-upper decomposition questions",
      ],
      miniDrill: [
        {
          prompt: "What shapes do L and U usually have?",
          answer: "L is lower triangular and U is upper triangular.",
        },
        {
          prompt: "After A = LU, what system do you solve first?",
          answer: "Ly = b.",
        },
      ],
      memoryHook: "LU splits one hard solve into two easy ones.",
      tags: ["linear-algebra", "lu", "factorization"],
      difficulty: "Stretch",
    }),
    makeLinearCard({
      id: "la-determinant-zero-test",
      chapter: "Chapter 3: Determinants",
      unit: "Determinants",
      topic: "What det = 0 tells you",
      name: "det = 0 Test",
      order: 10.3,
      useItWhen: "you need a fast singular versus invertible check",
      looksLike: "det(A) = 0 or det(A) not equal 0",
      doThis: "treat zero determinant as the red flag for collapse and lost invertibility",
      thinkOfItAs: "the matrix got flattened",
      watchOutFor: "computing the inverse after det already told you it cannot exist",
      rememberThis: "det 0 means singular",
      quickExample: {
        problem: "If det(A) = 0, can A be invertible?",
        move: "No.",
      },
      typicalProblemShapes: [
        "Quick invertibility checks",
        "Area or volume scaling collapsing to zero",
      ],
      miniDrill: [
        {
          prompt: "What does det not equal 0 usually signal for a square matrix?",
          answer: "Invertible.",
        },
        {
          prompt: "Does det = 0 suggest dependent columns?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Zero determinant, no inverse.",
      tags: ["linear-algebra", "determinant", "invertible"],
      difficulty: "Starter",
    }),
    makeLinearCard({
      id: "la-rank-nullity",
      chapter: "Chapter 4: Vector Spaces",
      unit: "Vector Spaces",
      topic: "Rank-nullity theorem",
      name: "Rank-Nullity",
      order: 15.6,
      useItWhen: "you need the dimension balance between outputs and hidden freedom",
      looksLike: "rank plus nullity equals number of columns",
      doThis: "count pivot directions and free directions together",
      thinkOfItAs: "used dimensions plus leftover freedom",
      watchOutFor: "mixing up number of rows with number of columns in the formula",
      rememberThis: "rank + nullity = number of columns",
      quickExample: {
        problem: "If a matrix has 6 columns and rank 4, what is the nullity?",
        move: "2.",
      },
      typicalProblemShapes: [
        "Dimension count questions",
        "Kernel and image size comparisons",
      ],
      miniDrill: [
        {
          prompt: "What does nullity count?",
          answer: "Free directions in the kernel.",
        },
        {
          prompt: "Does rank-nullity use the number of columns or rows?",
          answer: "Columns.",
        },
      ],
      memoryHook: "Used directions plus free directions equals total columns.",
      tags: ["linear-algebra", "rank-nullity", "dimension"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-orthogonal-matrix",
      chapter: "Chapter 5: Orthogonality",
      unit: "Orthogonality",
      topic: "Orthogonal matrices",
      name: "Orthogonal Matrix",
      order: 16.6,
      useItWhen: "the columns are orthonormal and the inverse should be easy",
      looksLike: "Q transpose Q = I",
      doThis: "check orthonormal columns, then swap inverse work for a transpose",
      thinkOfItAs: "a rigid move that keeps lengths and angles",
      watchOutFor: "assuming perpendicular columns are enough without normalization",
      rememberThis: "orthogonal matrix means Q inverse equals Q transpose",
      quickExample: {
        problem: "What is the fast inverse of an orthogonal matrix?",
        move: "Its transpose.",
      },
      typicalProblemShapes: [
        "Rotation or reflection matrices",
        "Orthonormal column tests",
      ],
      miniDrill: [
        {
          prompt: "Do orthogonal matrix columns need unit length too?",
          answer: "Yes.",
        },
        {
          prompt: "What equation is the quick test?",
          answer: "Q transpose Q = I.",
        },
      ],
      memoryHook: "Orthonormal columns make transpose equal inverse.",
      tags: ["linear-algebra", "orthogonal-matrix", "orthogonality"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-matrix-of-transformation",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "Matrix of a linear transformation",
      name: "Matrix of a Transformation",
      order: 18.4,
      useItWhen: "a geometric rule needs a matrix in coordinates",
      looksLike: "T(v), standard basis, image of e_1 and e_2",
      doThis: "send basis vectors through T and use those outputs as columns",
      thinkOfItAs: "recording what the machine does to the basis directions",
      watchOutFor: "forgetting matrix columns come from transformed basis vectors",
      rememberThis: "columns are T of the basis vectors",
      quickExample: {
        problem: "How do you build the matrix for T quickly?",
        move: "Find T on the basis vectors and stack the outputs as columns.",
      },
      typicalProblemShapes: [
        "Turn a formula for T into a matrix",
        "Find the standard matrix of a transformation",
      ],
      miniDrill: [
        {
          prompt: "What becomes the first column of the matrix?",
          answer: "T of the first basis vector.",
        },
        {
          prompt: "Do rows or columns store the transformed basis vectors?",
          answer: "Columns.",
        },
      ],
      memoryHook: "Transform the basis, then stack the columns.",
      tags: ["linear-algebra", "linear-transformation", "matrix"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-kernel-range",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "Kernel and range",
      name: "Kernel vs Range",
      order: 18.5,
      useItWhen: "you need to separate what maps to zero from what outputs are reachable",
      looksLike: "ker(T), range(T), null space, image",
      doThis: "treat the kernel as lost inputs and the range as possible outputs",
      thinkOfItAs: "what disappears versus what can be produced",
      watchOutFor: "mixing up where the kernel lives and where the range lives",
      rememberThis: "kernel lives in the input space, range lives in the output space",
      quickExample: {
        problem: "Where does the kernel of T live?",
        move: "In the domain.",
      },
      typicalProblemShapes: [
        "Find ker(T) or range(T)",
        "One-to-one and onto checks",
      ],
      miniDrill: [
        {
          prompt: "What output defines the kernel?",
          answer: "Zero.",
        },
        {
          prompt: "What does the range collect?",
          answer: "All outputs T can make.",
        },
      ],
      memoryHook: "Kernel = lost inputs. Range = reachable outputs.",
      tags: ["linear-algebra", "kernel", "range", "transformation"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-one-to-one-onto",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "One-to-one versus onto for linear maps",
      name: "One-to-One vs Onto",
      order: 18.6,
      useItWhen: "a linear map is tested for injective or surjective behavior",
      looksLike: "one-to-one, onto, trivial kernel, full range",
      doThis: "use kernel for one-to-one and range for onto",
      thinkOfItAs: "injective means no collisions, onto means no missed targets",
      watchOutFor: "checking the wrong space for the wrong property",
      rememberThis: "one-to-one talks to kernel, onto talks to range",
      quickExample: {
        problem: "What is the fast one-to-one test for a linear map?",
        move: "Check whether the kernel is only zero.",
      },
      typicalProblemShapes: [
        "Decide injective or surjective",
        "Square matrix equivalence checks",
      ],
      miniDrill: [
        {
          prompt: "If ker(T) has more than zero, is T one-to-one?",
          answer: "No.",
        },
        {
          prompt: "If range(T) misses outputs, is T onto?",
          answer: "No.",
        },
      ],
      memoryHook: "Kernel for injective, range for onto.",
      tags: ["linear-algebra", "injective", "surjective", "transformation"],
      difficulty: "Standard",
    }),
    makeLinearCard({
      id: "la-eigenspace",
      chapter: "Chapter 6: Eigenvalues and Linear Transformations",
      unit: "Transformations and Eigen",
      topic: "Eigenspaces",
      name: "Eigenspace",
      order: 19.1,
      useItWhen: "an eigenvalue is known and you need its matching vectors",
      looksLike: "(A - lambda I)x = 0",
      doThis: "plug in the eigenvalue and solve the homogeneous system",
      thinkOfItAs: "all vectors stretching in the same special direction",
      watchOutFor: "forgetting the zero vector is not an eigenvector even though it solves the system",
      rememberThis: "eigenspace comes from the null space of A minus lambda I",
      quickExample: {
        problem: "How do you find eigenvectors after finding lambda?",
        move: "Solve (A - lambda I)x = 0.",
      },
      typicalProblemShapes: [
        "Find a basis for an eigenspace",
        "Use eigenvectors after the eigenvalues are known",
      ],
      miniDrill: [
        {
          prompt: "What matrix do you build for eigenspace work?",
          answer: "A - lambda I.",
        },
        {
          prompt: "Is the zero vector an eigenvector?",
          answer: "No.",
        },
      ],
      memoryHook: "Eigenvalue first, null space next.",
      tags: ["linear-algebra", "eigenspace", "eigenvectors"],
      difficulty: "Standard",
    }),
  ],
};
