import type { BubbleCard, CourseContent } from "@/content/schema";

function makeProbabilityCard(
  card: Omit<BubbleCard, "subject" | "course" | "courseCode">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Probability",
    courseCode: "MATH 130A",
    ...card,
  };
}

export const probabilityCourse: CourseContent = {
  id: "probability",
  subject: "Mathematics",
  title: "Probability",
  institution: "UCI",
  courseCodes: ["MATH 130A"],
  aliases: ["Probability I"],
  shortDescription: "Counting, conditional probability, random variables, and expectation.",
  units: [
    "Counting",
    "Probability Basics",
    "Random Variables",
    "Joint Behavior",
    "Expectation and Variance",
    "Concentration and Limits",
  ],
  chapters: [
    "Chapter 1: Combinatorial Analysis",
    "Chapter 2: Probability: The Basics",
    "Chapter 3: Discrete Random Variables",
    "Chapter 4: Continuous Random Variables",
    "Chapter 5: Joint Distribution and Independence",
    "Chapter 6: Properties of Expectation",
    "Chapter 7: Covariance and Variance of Sums of Random Variables",
    "Chapter 8: Introduction to Concentration Inequalities",
    "Chapter 9: Central Limit Theorem",
  ],
  cards: [
    makeProbabilityCard({
      id: "prob-counting-rules",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Basic counting rules",
      name: "Basic Counting Rules",
      order: 1,
      useItWhen: "a problem asks how many outcomes are possible",
      looksLike: "how many ways..., choices in stages, either/or cases",
      doThis: "multiply for stages, add for separate cases",
      thinkOfItAs: "and means multiply, or means add",
      watchOutFor: "adding when the choices happen in sequence",
      rememberThis: "and multiply, or add",
      quickExample: {
        problem: "3 shirt choices and 4 pants choices. How many outfits?",
        move: "Multiply: 3 times 4.",
      },
      typicalProblemShapes: [
        "A process built from step 1 then step 2",
        "Separate non-overlapping cases that must be combined",
      ],
      miniDrill: [
        {
          prompt: "If choices happen in stages, do you add or multiply?",
          answer: "Multiply.",
        },
        {
          prompt: "If cases are separate alternatives, do you add or multiply?",
          answer: "Add.",
        },
      ],
      memoryHook: "And multiply. Or add.",
      tags: ["probability", "counting", "combinatorics"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-permutations",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Permutations",
      name: "Permutations",
      order: 2,
      useItWhen: "order matters",
      looksLike: "arrangements, lineups, rankings, passwords",
      doThis: "count ordered selections with factorial-style formulas",
      thinkOfItAs: "same people, different order, different outcome",
      watchOutFor: "using combinations when order matters",
      rememberThis: "permutations care about order",
      quickExample: {
        problem: "Choose and order 3 students from 10.",
        move: "Use a permutation count, not a combination count.",
      },
      typicalProblemShapes: [
        "Arrange objects in a row",
        "Choose winners with 1st, 2nd, and 3rd places",
      ],
      miniDrill: [
        {
          prompt: "Does order matter in a permutation?",
          answer: "Yes.",
        },
        {
          prompt: "Is ABC the same as CBA in a permutation problem?",
          answer: "No.",
        },
      ],
      memoryHook: "Permutation = arrangement.",
      tags: ["probability", "permutations", "counting"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-combinations",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Combinations",
      name: "Combinations",
      order: 3,
      useItWhen: "order does not matter",
      looksLike: "choose a committee, pick a hand, select a group",
      doThis: "count unordered selections with n choose k",
      thinkOfItAs: "same group, same outcome, no matter the order",
      watchOutFor: "counting the same group multiple times in different orders",
      rememberThis: "combinations ignore order",
      quickExample: {
        problem: "Choose 5 cards from a deck.",
        move: "Use a combination because the order of the 5 cards does not matter.",
      },
      typicalProblemShapes: [
        "Committee or team selection",
        "Hands, subsets, or chosen groups",
      ],
      miniDrill: [
        {
          prompt: "Does order matter in combinations?",
          answer: "No.",
        },
        {
          prompt: "Which is bigger for the same n and k: permutations or combinations?",
          answer: "Permutations, because they count more orderings.",
        },
      ],
      memoryHook: "Combination = choose a group.",
      tags: ["probability", "combinations", "counting"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-multinomial",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Multinomial coefficients",
      name: "Multinomial Coefficients",
      order: 4,
      useItWhen: "a set is split into several labeled groups",
      looksLike: "divide n objects into buckets of sizes a, b, c",
      doThis: "count how many ways to split into the group sizes",
      thinkOfItAs: "combinations with more than two buckets",
      watchOutFor: "treating a many-group split like one simple choose",
      rememberThis: "many buckets means multinomial",
      quickExample: {
        problem: "Split 10 people into groups of 4, 3, and 3.",
        move: "Use a multinomial count.",
      },
      typicalProblemShapes: [
        "Assign objects into labeled categories",
        "Count outcomes with several category totals fixed",
      ],
      miniDrill: [
        {
          prompt: "What is the multinomial idea in one phrase?",
          answer: "Split into several buckets.",
        },
        {
          prompt: "Is it just a one-step choose when there are 3 or more labeled groups?",
          answer: "No.",
        },
      ],
      memoryHook: "More than two groups? Think multinomial.",
      tags: ["probability", "multinomial", "counting"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-axioms",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Axioms of probability",
      name: "Probability Axioms",
      order: 5,
      useItWhen: "you need the basic rules probability must obey",
      looksLike: "P(A), P(sample space), disjoint events",
      doThis: "use nonnegative, whole space equals 1, and add disjoint events",
      thinkOfItAs: "the ground rules every probability model must follow",
      watchOutFor: "adding probabilities of overlapping events like they are disjoint",
      rememberThis: "whole space is 1",
      quickExample: {
        problem: "What is P(sample space)?",
        move: "1.",
      },
      typicalProblemShapes: [
        "Basic event calculations",
        "Checking whether a rule can be a probability model",
      ],
      miniDrill: [
        {
          prompt: "Can a probability be negative?",
          answer: "No.",
        },
        {
          prompt: "When can you add P(A) and P(B) directly?",
          answer: "When A and B are disjoint.",
        },
      ],
      memoryHook: "Probabilities live between 0 and 1, and all outcomes total 1.",
      tags: ["probability", "axioms", "basics"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-conditional",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Conditional probability",
      name: "Conditional Probability",
      order: 6,
      useItWhen: "the problem says given that something already happened",
      looksLike: "P(A given B)",
      doThis: "shrink the sample space to B, then measure A inside it",
      thinkOfItAs: "zooming in after new information arrives",
      watchOutFor: "using the old sample space after a condition changes the setup",
      rememberThis: "conditioning shrinks the universe",
      quickExample: {
        problem: "What changes first when you condition on B?",
        move: "The sample space shrinks to B.",
      },
      typicalProblemShapes: [
        "Given that a card is red, what is the chance it is a heart?",
        "Given a test is positive, what is the chance the patient has the disease?",
      ],
      miniDrill: [
        {
          prompt: "What does conditional probability do to the sample space?",
          answer: "It shrinks it.",
        },
        {
          prompt: "Can P(A given B) differ from P(A)?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Given B means live inside B.",
      tags: ["probability", "conditional", "basics"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-independence",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Independence",
      name: "Independence",
      order: 7,
      useItWhen: "one event does not change the chance of the other",
      looksLike: "independent events, product rule for events",
      doThis: "check whether P(A and B) equals P(A) times P(B)",
      thinkOfItAs: "knowing one tells you nothing new about the other",
      watchOutFor: "confusing disjoint with independent",
      rememberThis: "independent means product rule",
      quickExample: {
        problem: "What quick equation checks independence?",
        move: "P(A and B) = P(A)P(B).",
      },
      typicalProblemShapes: [
        "Repeated trials like coin flips",
        "Questions asking whether information changes probability",
      ],
      miniDrill: [
        {
          prompt: "Can disjoint nonzero events be independent?",
          answer: "No.",
        },
        {
          prompt: "What is the signature formula for independence?",
          answer: "P(A and B) = P(A)P(B).",
        },
      ],
      memoryHook: "No influence means product rule.",
      tags: ["probability", "independence", "conditional"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-bayes",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Bayes' Formula",
      name: "Bayes' Formula",
      order: 8,
      useItWhen: "you need to reverse the condition",
      looksLike: "P(A given B) but you know P(B given A)",
      doThis: "use prior times likelihood over total evidence",
      thinkOfItAs: "reversing the arrow after new evidence",
      watchOutFor: "forgetting the denominator that totals all ways B can happen",
      rememberThis: "reverse the condition carefully",
      quickExample: {
        problem: "What usually goes in the denominator of Bayes?",
        move: "The total probability of the evidence.",
      },
      typicalProblemShapes: [
        "Medical test questions",
        "Spam filters or diagnosis style reversal problems",
      ],
      miniDrill: [
        {
          prompt: "Does Bayes reverse conditional direction?",
          answer: "Yes.",
        },
        {
          prompt: "What is the big trap in Bayes problems?",
          answer: "Ignoring base rates and the full denominator.",
        },
      ],
      memoryHook: "Bayes flips the condition, not the logic.",
      tags: ["probability", "bayes", "conditional"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-expected-value",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Random variables and expectation",
      name: "Expected Value",
      order: 9,
      useItWhen: "you need the long-run average payoff",
      looksLike: "E(X), average gain, average number, mean",
      doThis: "multiply each value by its probability and add",
      thinkOfItAs: "the weighted average of all possible outcomes",
      watchOutFor: "averaging values without using probabilities",
      rememberThis: "expected value is weighted average",
      quickExample: {
        problem: "What is the basic expectation move?",
        move: "Value times probability, then add.",
      },
      typicalProblemShapes: [
        "Games of chance and expected payoff",
        "Average count or average cost questions",
      ],
      miniDrill: [
        {
          prompt: "Do unlikely big outcomes still matter to expectation?",
          answer: "Yes, if the payoff is big enough.",
        },
        {
          prompt: "Is expectation just the most likely value?",
          answer: "No.",
        },
      ],
      memoryHook: "Expectation = weighted average.",
      tags: ["probability", "expectation", "random-variable"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-linearity",
      chapter: "Chapter 6: Properties of Expectation",
      unit: "Expectation and Variance",
      topic: "Linearity of expectation",
      name: "Linearity of Expectation",
      order: 10,
      useItWhen: "a random total is a sum of smaller random pieces",
      looksLike: "E(X + Y + ...)",
      doThis: "split expectation across the sum even if the variables are dependent",
      thinkOfItAs: "expectation distributes over addition",
      watchOutFor: "thinking independence is required here",
      rememberThis: "linearity does not need independence",
      quickExample: {
        problem: "Do you need independence for E(X + Y) = E(X) + E(Y)?",
        move: "No.",
      },
      typicalProblemShapes: [
        "Expected number of successes, matches, or collisions",
        "Indicator-variable counting arguments",
      ],
      miniDrill: [
        {
          prompt: "What is the fast move for expectation of a sum?",
          answer: "Split the sum.",
        },
        {
          prompt: "Does dependence break linearity of expectation?",
          answer: "No.",
        },
      ],
      memoryHook: "Expectation splits sums for free.",
      tags: ["probability", "linearity", "expectation"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-variance",
      chapter: "Chapter 7: Covariance and Variance of Sums of Random Variables",
      unit: "Expectation and Variance",
      topic: "Variance",
      name: "Variance",
      order: 11,
      useItWhen: "you care about spread, not just average",
      looksLike: "Var(X), spread around the mean",
      doThis: "measure average squared distance from the mean",
      thinkOfItAs: "how noisy the random variable is",
      watchOutFor: "treating variance like standard deviation or like the mean itself",
      rememberThis: "variance measures spread",
      quickExample: {
        problem: "What does variance tell you that expectation does not?",
        move: "How spread out the outcomes are.",
      },
      typicalProblemShapes: [
        "Risk or volatility questions",
        "Variance of sums and transformations",
      ],
      miniDrill: [
        {
          prompt: "Can two random variables have the same expectation but different variance?",
          answer: "Yes.",
        },
        {
          prompt: "Does variance measure center or spread?",
          answer: "Spread.",
        },
      ],
      memoryHook: "Mean is center. Variance is spread.",
      tags: ["probability", "variance", "spread"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-distributions",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Special distributions",
      name: "Common Distributions",
      order: 12,
      useItWhen: "a problem smells like repeated trials, waiting time, or rare counts",
      looksLike: "Bernoulli, Binomial, Geometric, Poisson, Normal",
      doThis: "match the story to the distribution pattern before using formulas",
      thinkOfItAs: "story first, formula second",
      watchOutFor: "using a distribution formula before checking the setup assumptions",
      rememberThis: "recognize the story pattern",
      quickExample: {
        problem: "Repeated yes/no trials with fixed p. What model fits?",
        move: "Binomial if you count successes, geometric if you wait for the first success.",
      },
      typicalProblemShapes: [
        "Independent repeated trials",
        "Rare-event counts in a fixed interval",
      ],
      miniDrill: [
        {
          prompt: "Count successes in n independent trials. Which model?",
          answer: "Binomial.",
        },
        {
          prompt: "Wait for the first success. Which model?",
          answer: "Geometric.",
        },
      ],
      memoryHook: "Match the story before the formula.",
      tags: ["probability", "distribution", "binomial", "geometric", "poisson"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-continuous-density",
      chapter: "Chapter 4: Continuous Random Variables",
      unit: "Random Variables",
      topic: "Continuous distributions and density",
      name: "Density Functions",
      order: 13,
      useItWhen: "the random variable can take a continuum of values",
      looksLike: "f(x), density curve, integrate for probability",
      doThis: "use area under the density over an interval",
      thinkOfItAs: "continuous probability lives in area, not point masses",
      watchOutFor: "asking for probability at one exact point like it has a chunk of mass",
      rememberThis: "continuous probabilities come from intervals",
      quickExample: {
        problem: "How do you get probability from a density?",
        move: "Integrate over the interval.",
      },
      typicalProblemShapes: [
        "Normal or uniform density questions",
        "Probability over a range of values",
      ],
      miniDrill: [
        {
          prompt: "What is the probability at one exact point for a continuous variable?",
          answer: "0.",
        },
        {
          prompt: "What gives probability on an interval?",
          answer: "Area under the density curve.",
        },
      ],
      memoryHook: "Density means area, not point mass.",
      tags: ["probability", "continuous", "density"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-joint-distribution",
      chapter: "Chapter 5: Joint Distribution and Independence",
      unit: "Joint Behavior",
      topic: "Joint distributions",
      name: "Joint Distributions",
      order: 14,
      useItWhen: "two random variables are tracked together",
      looksLike: "P(X = x, Y = y) or joint density f(x, y)",
      doThis: "read the pair behavior first, then get marginals or conditionals from it",
      thinkOfItAs: "one table or surface for two variables at once",
      watchOutFor: "multiplying marginals when independence is not given",
      rememberThis: "joint comes first, marginals can come from it",
      quickExample: {
        problem: "What does a joint distribution describe?",
        move: "How two variables behave together.",
      },
      typicalProblemShapes: [
        "Two-way tables or density surfaces",
        "Find marginal or conditional distributions from a joint one",
      ],
      miniDrill: [
        {
          prompt: "Can you get marginals from a joint distribution?",
          answer: "Yes.",
        },
        {
          prompt: "Does joint always equal product of marginals?",
          answer: "No. Only under independence.",
        },
      ],
      memoryHook: "Joint tells the whole pair story.",
      tags: ["probability", "joint-distribution", "independence"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-covariance-correlation",
      chapter: "Chapter 7: Covariance and Variance of Sums of Random Variables",
      unit: "Joint Behavior",
      topic: "Covariance and correlation",
      name: "Covariance and Correlation",
      order: 15,
      useItWhen: "you need to know whether two variables move together",
      looksLike: "Cov(X,Y), Corr(X,Y)",
      doThis: "use covariance for direction of relationship and correlation for scaled strength",
      thinkOfItAs: "do they rise together, fall opposite, or barely connect",
      watchOutFor: "treating zero correlation like guaranteed independence",
      rememberThis: "correlation is scaled covariance",
      quickExample: {
        problem: "What does positive covariance suggest?",
        move: "The variables tend to move in the same direction.",
      },
      typicalProblemShapes: [
        "Scatterplot-style dependence questions",
        "Variance of a sum using covariance terms",
      ],
      miniDrill: [
        {
          prompt: "Does correlation have units?",
          answer: "No.",
        },
        {
          prompt: "Does zero correlation always mean independence?",
          answer: "No.",
        },
      ],
      memoryHook: "Covariance shows direction. Correlation rescales it.",
      tags: ["probability", "covariance", "correlation"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-markov-chebyshev",
      chapter: "Chapter 8: Introduction to Concentration Inequalities",
      unit: "Concentration and Limits",
      topic: "Markov and Chebyshev inequalities",
      name: "Markov and Chebyshev",
      order: 16,
      useItWhen: "you need a quick upper bound without full distribution details",
      looksLike: "bound the chance a random variable gets large",
      doThis: "use Markov for nonnegative variables and Chebyshev when variance is available",
      thinkOfItAs: "rough but reliable guardrails",
      watchOutFor: "expecting these bounds to be sharp",
      rememberThis: "Markov uses mean, Chebyshev uses variance",
      quickExample: {
        problem: "Which bound uses variance explicitly?",
        move: "Chebyshev.",
      },
      typicalProblemShapes: [
        "Upper bounds on tail probabilities",
        "Questions with expectation or variance but no exact distribution",
      ],
      miniDrill: [
        {
          prompt: "What extra ingredient does Chebyshev need beyond expectation?",
          answer: "Variance.",
        },
        {
          prompt: "What is the main job of these inequalities?",
          answer: "Give probability bounds.",
        },
      ],
      memoryHook: "Markov for rough mean bounds, Chebyshev for spread bounds.",
      tags: ["probability", "markov", "chebyshev", "concentration"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-clt",
      chapter: "Chapter 9: Central Limit Theorem",
      unit: "Concentration and Limits",
      topic: "Central Limit Theorem",
      name: "Central Limit Theorem",
      order: 17,
      useItWhen: "a sum or average of many random pieces shows up",
      looksLike: "large n, sample mean, standardized sum",
      doThis: "normalize the sum or average and approximate with a normal shape",
      thinkOfItAs: "many random bumps blending into a bell curve",
      watchOutFor: "using CLT with tiny sample sizes or strong dependence without checking assumptions",
      rememberThis: "many small random pieces often look normal",
      quickExample: {
        problem: "What usually becomes approximately normal under CLT?",
        move: "A properly standardized sum or average of many variables.",
      },
      typicalProblemShapes: [
        "Sample means for large n",
        "Approximate probabilities for sums of independent terms",
      ],
      miniDrill: [
        {
          prompt: "Does CLT talk about a single variable or many combined variables?",
          answer: "Many combined variables.",
        },
        {
          prompt: "What shape usually appears in the limit?",
          answer: "A normal bell curve.",
        },
      ],
      memoryHook: "Big random sums drift toward normal.",
      tags: ["probability", "clt", "normal", "limit"],
      difficulty: "Stretch",
    }),
    makeProbabilityCard({
      id: "prob-inclusion-exclusion",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Inclusion-exclusion",
      name: "Inclusion-Exclusion",
      order: 8.2,
      useItWhen: "two events overlap and plain addition double-counts",
      looksLike: "P(A union B) with overlap",
      doThis: "add both events, then subtract the overlap once",
      thinkOfItAs: "fixing the double count",
      watchOutFor: "adding overlapping events like they are disjoint",
      rememberThis: "add both, subtract the overlap",
      quickExample: {
        problem: "What term gets subtracted in P(A union B)?",
        move: "Subtract P(A intersection B).",
      },
      typicalProblemShapes: [
        "At least one of two events happens",
        "Union of overlapping events",
      ],
      miniDrill: [
        {
          prompt: "Why subtract the intersection?",
          answer: "Because it was counted twice.",
        },
        {
          prompt: "If events are disjoint, what happens to the overlap term?",
          answer: "It becomes 0.",
        },
      ],
      memoryHook: "Union with overlap? Subtract the middle.",
      tags: ["probability", "union", "inclusion-exclusion"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-total-probability",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Law of total probability",
      name: "Law of Total Probability",
      order: 8.3,
      useItWhen: "one event can happen through several clean cases",
      looksLike: "split into cases, partition, conditional pieces",
      doThis: "break the sample space into non-overlapping cases and add the case paths",
      thinkOfItAs: "build the answer door by door",
      watchOutFor: "using cases that overlap",
      rememberThis: "split into cases, then add",
      quickExample: {
        problem: "When is the law of total probability useful?",
        move: "When an event can happen through several separate cases.",
      },
      typicalProblemShapes: [
        "Several groups or sources feeding one event",
        "Bayes-style setups with a partition",
      ],
      miniDrill: [
        {
          prompt: "What kind of case split do you need?",
          answer: "A partition.",
        },
        {
          prompt: "Can the cases overlap?",
          answer: "No.",
        },
      ],
      memoryHook: "Break it up, then add the paths.",
      tags: ["probability", "total-probability", "bayes"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-pmf-cdf",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "PMF and CDF",
      name: "PMF vs CDF",
      order: 12.2,
      useItWhen: "you need exact point probability or built-up probability up to a cutoff",
      looksLike: "P(X = x), F(x) = P(X <= x)",
      doThis: "use PMF for one exact value and CDF for everything up to that value",
      thinkOfItAs: "PMF is one spot, CDF is the pile-up",
      watchOutFor: "using the CDF like it gives exact point mass automatically",
      rememberThis: "PMF is exact, CDF accumulates",
      quickExample: {
        problem: "What does a CDF collect?",
        move: "All probability up to a cutoff.",
      },
      typicalProblemShapes: [
        "Tables of discrete random variable values",
        "Convert between exact and cumulative probability",
      ],
      miniDrill: [
        {
          prompt: "Which one answers P(X = 3) directly?",
          answer: "The PMF.",
        },
        {
          prompt: "Which one keeps building as x moves right?",
          answer: "The CDF.",
        },
      ],
      memoryHook: "PMF picks a point. CDF piles up.",
      tags: ["probability", "pmf", "cdf", "random-variable"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-binomial",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Binomial distribution",
      name: "Binomial Pattern",
      order: 12.3,
      useItWhen: "you count successes in a fixed number of independent yes-no trials",
      looksLike: "n trials, same p, exactly k successes",
      doThis: "check fixed n, same p, independence, then use the binomial setup",
      thinkOfItAs: "repeat the same trial n times and count wins",
      watchOutFor: "using binomial when the number of trials is not fixed",
      rememberThis: "fixed tries, count successes",
      quickExample: {
        problem: "What are the main binomial clues?",
        move: "Fixed number of independent trials with the same success chance.",
      },
      typicalProblemShapes: [
        "Exactly k successes in n tries",
        "Repeated independent success-failure experiments",
      ],
      miniDrill: [
        {
          prompt: "Does binomial need a fixed number of trials?",
          answer: "Yes.",
        },
        {
          prompt: "What are you counting?",
          answer: "The number of successes.",
        },
      ],
      memoryHook: "Fixed tries, count the wins.",
      tags: ["probability", "binomial", "distribution"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-geometric",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Geometric distribution",
      name: "Geometric Pattern",
      order: 12.4,
      useItWhen: "you wait for the first success",
      looksLike: "first success on trial k",
      doThis: "spot repeated independent trials and a stop-on-first-success story",
      thinkOfItAs: "keep trying until one success lands",
      watchOutFor: "using geometric when the story counts total successes",
      rememberThis: "geometric means wait time",
      quickExample: {
        problem: "What is the geometric story in one line?",
        move: "How long until the first success.",
      },
      typicalProblemShapes: [
        "First success on trial k",
        "Repeated independent trials with no fixed stop count",
      ],
      miniDrill: [
        {
          prompt: "Does geometric count waiting time or total successes?",
          answer: "Waiting time.",
        },
        {
          prompt: "Is the number of trials fixed in advance?",
          answer: "No.",
        },
      ],
      memoryHook: "Geometric = wait for one win.",
      tags: ["probability", "geometric", "distribution"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-poisson",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Poisson distribution",
      name: "Poisson Pattern",
      order: 12.5,
      useItWhen: "you count rare events in a time or space window",
      looksLike: "arrivals, defects, calls, hits in an interval",
      doThis: "check for count-in-a-window with average rate lambda",
      thinkOfItAs: "rare events dripping into a bucket",
      watchOutFor: "using Poisson on a fixed-trial success story",
      rememberThis: "Poisson counts events in a window",
      quickExample: {
        problem: "What kind of story fits Poisson best?",
        move: "Count rare arrivals in an interval.",
      },
      typicalProblemShapes: [
        "Calls per hour",
        "Defects per page or arrivals per minute",
      ],
      miniDrill: [
        {
          prompt: "What parameter drives Poisson?",
          answer: "The average rate lambda.",
        },
        {
          prompt: "Does Poisson count a window or waiting time?",
          answer: "A window count.",
        },
      ],
      memoryHook: "Poisson = events per window.",
      tags: ["probability", "poisson", "distribution"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-normal-pattern",
      chapter: "Chapter 4: Continuous Random Variables",
      unit: "Random Variables",
      topic: "Normal distribution",
      name: "Normal Pattern",
      order: 13.2,
      useItWhen: "a bell-shaped continuous model shows up",
      looksLike: "mean mu, standard deviation sigma, bell curve",
      doThis: "think interval area and standardize when needed",
      thinkOfItAs: "the classic bell model",
      watchOutFor: "treating normal like a point-mass discrete model",
      rememberThis: "normal means bell curve area",
      quickExample: {
        problem: "What do you usually compute under a normal curve?",
        move: "Area over an interval.",
      },
      typicalProblemShapes: [
        "Bell-shaped measurement models",
        "Z-score and standardization questions",
      ],
      miniDrill: [
        {
          prompt: "What does standardizing create?",
          answer: "A z-score.",
        },
        {
          prompt: "Do exact point probabilities matter in a continuous normal model?",
          answer: "No. Intervals matter.",
        },
      ],
      memoryHook: "Normal = bell curve intervals.",
      tags: ["probability", "normal", "continuous"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-variance-sum",
      chapter: "Chapter 7: Covariance and Variance of Sums of Random Variables",
      unit: "Expectation and Variance",
      topic: "Variance of sums",
      name: "Variance of a Sum",
      order: 15.2,
      useItWhen: "several random pieces are being added",
      looksLike: "Var(X + Y), independent sums, covariance terms",
      doThis: "check independence first before you add variances",
      thinkOfItAs: "spread combines, but not always for free",
      watchOutFor: "adding variances blindly without checking dependence",
      rememberThis: "variance adds cleanly only under independence",
      quickExample: {
        problem: "When does Var(X + Y) equal Var(X) + Var(Y)?",
        move: "When X and Y are independent.",
      },
      typicalProblemShapes: [
        "Sums of random variables",
        "Comparisons between expectation and variance rules",
      ],
      miniDrill: [
        {
          prompt: "Does variance always add like expectation?",
          answer: "No.",
        },
        {
          prompt: "What condition makes variance add cleanly?",
          answer: "Independence.",
        },
      ],
      memoryHook: "Expectation always adds. Variance needs help.",
      tags: ["probability", "variance", "sum", "independence"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-indicator",
      chapter: "Chapter 6: Properties of Expectation",
      unit: "Expectation and Variance",
      topic: "Indicator variables",
      name: "Indicator Variables",
      order: 15.3,
      useItWhen: "you want to count random events with 0-1 flags",
      looksLike: "I_A, event happened or not, expected count",
      doThis: "turn each event into a 0-1 switch, then sum the switches",
      thinkOfItAs: "tiny on-off counters",
      watchOutFor: "forgetting indicators are random variables too",
      rememberThis: "count with 0-1 switches",
      quickExample: {
        problem: "Why use indicator variables?",
        move: "They turn counting problems into expectation problems.",
      },
      typicalProblemShapes: [
        "Expected number of matches, collisions, or hits",
        "Linearity of expectation tricks",
      ],
      miniDrill: [
        {
          prompt: "What values can an indicator take?",
          answer: "Only 0 or 1.",
        },
        {
          prompt: "What do indicators make easier?",
          answer: "Expected counting.",
        },
      ],
      memoryHook: "If it can be counted, try a 0-1 switch.",
      tags: ["probability", "indicator", "expectation"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-lln",
      chapter: "Chapter 9: Central Limit Theorem",
      unit: "Concentration and Limits",
      topic: "Law of Large Numbers",
      name: "Law of Large Numbers",
      order: 17.2,
      useItWhen: "sample averages keep growing and you care about the long-run center",
      looksLike: "average of many trials, long-run frequency, sample mean",
      doThis: "separate where the average goes from what shape the distribution has",
      thinkOfItAs: "long runs settle near the true mean",
      watchOutFor: "confusing LLN with CLT",
      rememberThis: "LLN says where averages go; CLT says how they look",
      quickExample: {
        problem: "What does the Law of Large Numbers say in plain English?",
        move: "Long-run averages drift toward the true mean.",
      },
      typicalProblemShapes: [
        "Repeated sampling and average outcomes",
        "Questions comparing LLN and CLT",
      ],
      miniDrill: [
        {
          prompt: "Does LLN talk more about center or bell shape?",
          answer: "Center.",
        },
        {
          prompt: "What theorem is more about normal shape for big sums or averages?",
          answer: "The Central Limit Theorem.",
        },
      ],
      memoryHook: "LLN finds the mean. CLT finds the shape.",
      tags: ["probability", "lln", "sample-mean"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-stars-and-bars",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Counting nonnegative integer solutions",
      name: "Stars and Bars",
      order: 4.5,
      useItWhen: "you count ways to split a total into buckets",
      looksLike: "x1 + x2 + ... + xn = k with xi nonnegative",
      doThis: "turn the total into stars and use bars to split the buckets",
      thinkOfItAs: "one row of objects with dividers",
      watchOutFor: "forgetting whether zero is allowed",
      rememberThis: "sum into buckets means stars and bars",
      quickExample: {
        problem: "What pattern fits x1 + x2 + x3 = 7 with xi nonnegative?",
        move: "Stars and bars.",
      },
      typicalProblemShapes: [
        "Nonnegative integer solution counts",
        "Distribute identical balls into bins",
      ],
      miniDrill: [
        {
          prompt: "What changes first if every xi must be at least 1?",
          answer: "Shift each variable down by 1 before counting.",
        },
        {
          prompt: "Does stars and bars count ordered buckets or unordered groups?",
          answer: "Ordered buckets.",
        },
      ],
      memoryHook: "Objects and dividers.",
      tags: ["probability", "counting", "stars-and-bars"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-equally-likely",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Equally likely outcomes",
      name: "Equally Likely Outcomes",
      order: 5.5,
      useItWhen: "every outcome is equally likely",
      looksLike: "fair die, fair card draw, random permutation, uniform sample space",
      doThis: "count favorable outcomes over total outcomes",
      thinkOfItAs: "probability becomes a fraction of the sample space",
      watchOutFor: "using favorable over total when outcomes are not equally likely",
      rememberThis: "counting works only after equal-likelihood check",
      quickExample: {
        problem: "What is the first probability move on a fair die problem?",
        move: "Count good outcomes and divide by 6.",
      },
      typicalProblemShapes: [
        "Cards, dice, coin flips, and random permutations",
        "Probability from raw counting",
      ],
      miniDrill: [
        {
          prompt: "Can you use favorable over total if outcomes are weighted differently?",
          answer: "No.",
        },
        {
          prompt: "What is the denominator in an equally likely sample space?",
          answer: "The total number of outcomes.",
        },
      ],
      memoryHook: "Equal chance first, then count.",
      tags: ["probability", "equally-likely", "counting"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-secretary-problem",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Secretary problem",
      name: "Secretary Problem",
      order: 7.6,
      useItWhen: "choices arrive one by one and rejected options are gone forever",
      looksLike: "interview sequence, best-so-far rule, stop and choose now",
      doThis: "skip an early sample, then take the first option that beats everything seen so far",
      thinkOfItAs: "sample first, then pounce on the first standout",
      watchOutFor: "trying to compare with future candidates you have not seen",
      rememberThis: "skip some, then take the next best-so-far",
      quickExample: {
        problem: "What is the recognition clue for secretary-style problems?",
        move: "Sequential choice with no going back.",
      },
      typicalProblemShapes: [
        "Optimal stopping problems",
        "Pick the best item from a one-pass sequence",
      ],
      miniDrill: [
        {
          prompt: "Can you return to a rejected candidate in the classic setup?",
          answer: "No.",
        },
        {
          prompt: "What is the usual strategy shape?",
          answer: "Observe first, then choose the next record-breaker.",
        },
      ],
      memoryHook: "Sample, then grab the next standout.",
      tags: ["probability", "secretary-problem", "optimal-stopping"],
      difficulty: "Stretch",
    }),
    makeProbabilityCard({
      id: "prob-coupon-collector",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Coupon collector",
      name: "Coupon Collector",
      order: 10.2,
      useItWhen: "you keep sampling until every type has appeared",
      looksLike: "collect all n types, repeated draws, waiting time",
      doThis: "split the total wait into stages and add the expected waits",
      thinkOfItAs: "the last missing item takes the longest",
      watchOutFor: "treating every new coupon stage like it has the same chance",
      rememberThis: "collect-all problems break into stages",
      quickExample: {
        problem: "What is the usual move for collect-all expectation?",
        move: "Add the waiting times for each new coupon.",
      },
      typicalProblemShapes: [
        "Collect every card, sticker, or coupon type",
        "Expected time until all categories appear",
      ],
      miniDrill: [
        {
          prompt: "Does the final missing type usually arrive quickly or slowly?",
          answer: "Slowly.",
        },
        {
          prompt: "What theorem makes the stage split easy?",
          answer: "Linearity of expectation.",
        },
      ],
      memoryHook: "Collect-all means stage-by-stage waiting.",
      tags: ["probability", "coupon-collector", "expectation"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-negative-binomial",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Negative binomial pattern",
      name: "Negative Binomial Pattern",
      order: 12.05,
      useItWhen: "you wait for the r-th success, not just the first one",
      looksLike: "number of trials until r successes",
      doThis: "recognize repeated geometric waiting bundled to hit a target number of successes",
      thinkOfItAs: "geometric, but keep going until success number r",
      watchOutFor: "confusing number of successes with number of trials",
      rememberThis: "negative binomial = wait for the r-th success",
      quickExample: {
        problem: "What changes from geometric to negative binomial?",
        move: "You wait for the r-th success instead of the first.",
      },
      typicalProblemShapes: [
        "Trials until the 3rd or 5th success",
        "Repeated Bernoulli waiting-time questions",
      ],
      miniDrill: [
        {
          prompt: "Is geometric the special case r = 1?",
          answer: "Yes.",
        },
        {
          prompt: "Does negative binomial count successes or total trials?",
          answer: "Usually total trials until the r-th success.",
        },
      ],
      memoryHook: "Geometric waits for one. Negative binomial waits for r.",
      tags: ["probability", "negative-binomial", "distribution"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-hypergeometric",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Hypergeometric pattern",
      name: "Hypergeometric Pattern",
      order: 12.1,
      useItWhen: "you sample without replacement from a finite population",
      looksLike: "deck of cards, good items in a population, draws without replacement",
      doThis: "count good draws with combinations and remember probabilities change each draw",
      thinkOfItAs: "binomial without replacement",
      watchOutFor: "using independence or binomial when the population is shrinking",
      rememberThis: "no replacement means hypergeometric",
      quickExample: {
        problem: "What is the fast recognition clue for hypergeometric?",
        move: "Sampling without replacement from a fixed pool.",
      },
      typicalProblemShapes: [
        "Cards, marbles, and defect samples without replacement",
        "Count how many successes appear in a fixed draw size",
      ],
      miniDrill: [
        {
          prompt: "Are the draws independent in hypergeometric sampling?",
          answer: "No.",
        },
        {
          prompt: "What common distribution does hypergeometric resemble?",
          answer: "Binomial, but without replacement.",
        },
      ],
      memoryHook: "Without replacement breaks independence.",
      tags: ["probability", "hypergeometric", "distribution"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-uniform-continuous",
      chapter: "Chapter 4: Continuous Random Variables",
      unit: "Random Variables",
      topic: "Continuous uniform distribution",
      name: "Continuous Uniform",
      order: 13.05,
      useItWhen: "every point in an interval is equally likely by density",
      looksLike: "X on [a,b], flat density, random point on an interval",
      doThis: "treat probability as interval length over total length",
      thinkOfItAs: "flat chance across a stretch",
      watchOutFor: "trying to give a positive probability to one exact point",
      rememberThis: "uniform on an interval means length ratios",
      quickExample: {
        problem: "How do you find P(c <= X <= d) for uniform on [a,b]?",
        move: "Use interval length over total length.",
      },
      typicalProblemShapes: [
        "Random points on a line segment",
        "Flat density over an interval",
      ],
      miniDrill: [
        {
          prompt: "What is the probability of one exact point in a continuous model?",
          answer: "0.",
        },
        {
          prompt: "What geometric idea drives continuous uniform?",
          answer: "Length.",
        },
      ],
      memoryHook: "Flat interval means length over length.",
      tags: ["probability", "uniform", "continuous"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-exponential",
      chapter: "Chapter 4: Continuous Random Variables",
      unit: "Random Variables",
      topic: "Exponential distribution",
      name: "Exponential Pattern",
      order: 13.15,
      useItWhen: "you model waiting time until the next arrival",
      looksLike: "wait time, rate lambda, memoryless continuous model",
      doThis: "think waiting time, not event count, and use the rate parameter",
      thinkOfItAs: "the waiting-time partner of Poisson",
      watchOutFor: "mixing up Poisson counts with exponential waits",
      rememberThis: "Poisson counts, exponential waits",
      quickExample: {
        problem: "What story fits exponential best?",
        move: "Time until the next event.",
      },
      typicalProblemShapes: [
        "Waiting time until the next call or arrival",
        "Memoryless continuous models",
      ],
      miniDrill: [
        {
          prompt: "Does exponential count events or time?",
          answer: "Time.",
        },
        {
          prompt: "What discrete distribution is its close count partner?",
          answer: "Poisson.",
        },
      ],
      memoryHook: "Exponential waits for the next event.",
      tags: ["probability", "exponential", "continuous"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-normal-approximation",
      chapter: "Chapter 4: Continuous Random Variables",
      unit: "Random Variables",
      topic: "Normal approximation to a binomial",
      name: "Normal Approximation",
      order: 13.25,
      useItWhen: "a binomial has large n and you want a quick probability estimate",
      looksLike: "Bin(n,p) with big sample size, bell-shape approximation",
      doThis: "match the mean and spread, then approximate with a normal curve",
      thinkOfItAs: "swap a chunky count curve for a smooth bell",
      watchOutFor: "using it when n is too small or the binomial is too skewed",
      rememberThis: "big binomial can act normal",
      quickExample: {
        problem: "When should a binomial start making you think normal approximation?",
        move: "When n is large enough for a bell-shape estimate to make sense.",
      },
      typicalProblemShapes: [
        "Approximate a binomial probability quickly",
        "Large sample success counts",
      ],
      miniDrill: [
        {
          prompt: "Is normal approximation exact?",
          answer: "No. It is an estimate.",
        },
        {
          prompt: "What discrete model is being approximated here?",
          answer: "Binomial.",
        },
      ],
      memoryHook: "Large binomial, smooth bell estimate.",
      tags: ["probability", "normal-approximation", "binomial"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-conditional-distribution",
      chapter: "Chapter 5: Joint Distribution and Independence",
      unit: "Joint Behavior",
      topic: "Conditional distributions",
      name: "Conditional Distribution",
      order: 14.5,
      useItWhen: "one variable is pinned down and you want the other after that information",
      looksLike: "X given Y = y, conditional PMF, conditional density",
      doThis: "freeze the given information, then renormalize inside that slice",
      thinkOfItAs: "zooming in on one strip of the joint picture",
      watchOutFor: "using the original total probability after conditioning",
      rememberThis: "condition first, then renormalize",
      quickExample: {
        problem: "What happens to a joint distribution when you condition on Y = y?",
        move: "You slice it and rescale inside that slice.",
      },
      typicalProblemShapes: [
        "Find X given Y = y",
        "Work from a joint table or density to a conditional law",
      ],
      miniDrill: [
        {
          prompt: "Does conditioning usually shrink the universe you work in?",
          answer: "Yes.",
        },
        {
          prompt: "What must conditional probabilities still add to?",
          answer: "1 inside the conditioned slice.",
        },
      ],
      memoryHook: "Slice first, then rescale.",
      tags: ["probability", "conditional-distribution", "joint"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-conditional-expectation",
      chapter: "Chapter 7: Covariance and Variance of Sums of Random Variables",
      unit: "Expectation and Variance",
      topic: "Conditional expectation",
      name: "Conditional Expectation",
      order: 16.1,
      useItWhen: "extra information changes your best average guess",
      looksLike: "E[X given Y], average after information, tower rule",
      doThis: "take the expected value inside the conditioned world first",
      thinkOfItAs: "the average after the new clue arrives",
      watchOutFor: "treating conditional expectation like a single fixed number in every situation",
      rememberThis: "condition first, average second",
      quickExample: {
        problem: "What does E[X given Y] mean in plain English?",
        move: "The average value of X once Y is known.",
      },
      typicalProblemShapes: [
        "Expected value with partial information",
        "Tower rule and law of total expectation problems",
      ],
      miniDrill: [
        {
          prompt: "Does knowing more information usually change the average guess?",
          answer: "It can.",
        },
        {
          prompt: "What order of operations helps here?",
          answer: "Condition, then average.",
        },
      ],
      memoryHook: "New clue, new average.",
      tags: ["probability", "conditional-expectation", "expectation"],
      difficulty: "Stretch",
    }),
    makeProbabilityCard({
      id: "prob-chernoff",
      chapter: "Chapter 8: Introduction to Concentration Inequalities",
      unit: "Concentration and Limits",
      topic: "Chernoff bounds",
      name: "Chernoff Bound",
      order: 16.7,
      useItWhen: "a sum of many independent indicator-style variables should stay near its mean",
      looksLike: "tail probability for a binomial-like sum, exp(-c n) style bound",
      doThis: "recognize it as the sharper concentration tool for independent sums",
      thinkOfItAs: "the strong no-big-deviation guardrail",
      watchOutFor: "using Chebyshev when the problem is really built for Chernoff",
      rememberThis: "independent Bernoulli sums concentrate sharply",
      quickExample: {
        problem: "When is Chernoff usually stronger than Chebyshev?",
        move: "For sums of independent indicator-type variables.",
      },
      typicalProblemShapes: [
        "Large deviation bounds for binomial-style sums",
        "Show a random count stays near its mean with high probability",
      ],
      miniDrill: [
        {
          prompt: "What structure usually appears before Chernoff?",
          answer: "Independent indicator or Bernoulli sums.",
        },
        {
          prompt: "Is Chernoff about exact probabilities or strong bounds?",
          answer: "Strong bounds.",
        },
      ],
      memoryHook: "Independent sums stay close with high probability.",
      tags: ["probability", "chernoff", "concentration"],
      difficulty: "Stretch",
    }),
    makeProbabilityCard({
      id: "prob-bernoulli-pattern",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Bernoulli pattern",
      name: "Bernoulli Pattern",
      order: 11.65,
      useItWhen: "one trial has just two outcomes like success or failure",
      looksLike: "0 or 1, yes or no, one shot with probability p",
      doThis: "treat it as the basic building block for binomial and indicator variables",
      thinkOfItAs: "one tiny success-fail switch",
      watchOutFor: "using Bernoulli when the experiment has many trials",
      rememberThis: "Bernoulli is one trial, not many",
      quickExample: {
        problem: "What distribution matches one coin flip coded as 1 for heads and 0 for tails?",
        move: "Bernoulli.",
      },
      typicalProblemShapes: [
        "Single success-failure trial",
        "0-1 random variable models",
      ],
      miniDrill: [
        {
          prompt: "How many values can a Bernoulli variable take?",
          answer: "Two.",
        },
        {
          prompt: "Is a Bernoulli variable a natural fit for one trial or many?",
          answer: "One trial.",
        },
      ],
      memoryHook: "One switch, two outcomes.",
      tags: ["probability", "bernoulli", "distribution"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-gamma-pattern",
      chapter: "Chapter 4: Continuous Random Variables",
      unit: "Random Variables",
      topic: "Gamma distribution pattern",
      name: "Gamma Pattern",
      order: 13.35,
      useItWhen: "you wait for several Poisson-style arrivals in continuous time",
      looksLike: "time until the r-th event, shape parameter, continuous wait model",
      doThis: "recognize it as the multi-arrival version of the exponential",
      thinkOfItAs: "exponential, but keep waiting for more events",
      watchOutFor: "mixing it up with a discrete negative binomial count story",
      rememberThis: "gamma waits for the r-th arrival in time",
      quickExample: {
        problem: "What continuous distribution generalizes exponential waiting?",
        move: "Gamma.",
      },
      typicalProblemShapes: [
        "Wait time until the 3rd or 5th arrival",
        "Continuous accumulation of waiting times",
      ],
      miniDrill: [
        {
          prompt: "What is the one-arrival special case of gamma?",
          answer: "Exponential.",
        },
        {
          prompt: "Does gamma count events or waiting time?",
          answer: "Waiting time.",
        },
      ],
      memoryHook: "Exponential waits for one, gamma waits for many.",
      tags: ["probability", "gamma", "continuous"],
      difficulty: "Stretch",
    }),
    makeProbabilityCard({
      id: "prob-independent-rvs",
      chapter: "Chapter 5: Joint Distribution and Independence",
      unit: "Joint Behavior",
      topic: "Independent random variables",
      name: "Independent Random Variables",
      order: 14.6,
      useItWhen: "the joint behavior should split into separate pieces",
      looksLike: "joint pmf factors, joint density factors, one variable tells you nothing about the other",
      doThis: "check whether the joint equals the product of the marginals",
      thinkOfItAs: "two random stories that do not interfere",
      watchOutFor: "assuming independence just because the variables look unrelated",
      rememberThis: "independence means joint equals product",
      quickExample: {
        problem: "What is the fast independence test from a joint table?",
        move: "Compare the joint entries to marginal products.",
      },
      typicalProblemShapes: [
        "Joint pmf or density factorization",
        "Check whether two random variables are independent",
      ],
      miniDrill: [
        {
          prompt: "What should P(X = x, Y = y) equal under independence?",
          answer: "P(X = x) times P(Y = y).",
        },
        {
          prompt: "Does zero covariance always prove independence?",
          answer: "No.",
        },
      ],
      memoryHook: "Joint splits into two pieces.",
      tags: ["probability", "independence", "joint"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-sum-independent-rvs",
      chapter: "Chapter 5: Joint Distribution and Independence",
      unit: "Joint Behavior",
      topic: "Sums of independent random variables",
      name: "Sum of Independent Variables",
      order: 14.7,
      useItWhen: "a new random variable is built as X + Y",
      looksLike: "sum of two variables, combine distributions, convolution feel",
      doThis: "sum over all ways the pieces can add to the target",
      thinkOfItAs: "collect every path that lands on the same total",
      watchOutFor: "adding probabilities from impossible pairs or forgetting all valid pairs",
      rememberThis: "sum distribution means gather all add-up-to-the-target cases",
      quickExample: {
        problem: "How do you find P(X + Y = 5) for discrete independent variables?",
        move: "Add all joint cases where the two values total 5.",
      },
      typicalProblemShapes: [
        "Distribution of X + Y",
        "Dice-sum style problems",
      ],
      miniDrill: [
        {
          prompt: "Do you check one pair or every pair that makes the total?",
          answer: "Every pair.",
        },
        {
          prompt: "Why does independence help here?",
          answer: "It lets the joint pieces multiply cleanly.",
        },
      ],
      memoryHook: "Add totals by gathering all matching pairs.",
      tags: ["probability", "sum", "independent", "convolution"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-lotus",
      chapter: "Chapter 6: Properties of Expectation",
      unit: "Expectation and Variance",
      topic: "Expectation of a function",
      name: "Function of a Random Variable",
      order: 15.15,
      useItWhen: "you need E[g(X)] without first finding the full distribution of g(X)",
      looksLike: "E[g(X)], transformed variable, square or indicator inside expectation",
      doThis: "apply the function to the outcomes first, then average with the original law of X",
      thinkOfItAs: "push the function inside the average",
      watchOutFor: "trying to replace E[g(X)] with g(E[X])",
      rememberThis: "average the transformed values, not the average first",
      quickExample: {
        problem: "How do you get E[X squared] from the distribution of X?",
        move: "Square each value first, then average.",
      },
      typicalProblemShapes: [
        "Expectation of squared values or indicators",
        "Need E[g(X)] from the original pmf or density",
      ],
      miniDrill: [
        {
          prompt: "Is E[X squared] usually the same as E[X] squared?",
          answer: "No.",
        },
        {
          prompt: "What do you transform first, the outcomes or the expectation?",
          answer: "The outcomes.",
        },
      ],
      memoryHook: "Transform first, average second.",
      tags: ["probability", "expectation", "lotus"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-tail-bound-strategy",
      chapter: "Chapter 8: Introduction to Concentration Inequalities",
      unit: "Concentration and Limits",
      topic: "Tail bound strategy",
      name: "Tail Bound Strategy",
      order: 16.55,
      useItWhen: "a problem wants a quick bound on being far from the mean",
      looksLike: "P(X large), deviation bound, not exact probability",
      doThis: "pick the roughest bound that fits the information you actually have",
      thinkOfItAs: "choose the right hammer: mean only, variance, or strong independence",
      watchOutFor: "chasing an exact distribution when the problem only wants a bound",
      rememberThis: "Markov uses mean, Chebyshev uses variance, Chernoff uses independence",
      quickExample: {
        problem: "What bound uses only nonnegativity and expectation?",
        move: "Markov.",
      },
      typicalProblemShapes: [
        "Upper-bound a tail probability fast",
        "Choose between Markov, Chebyshev, and Chernoff",
      ],
      miniDrill: [
        {
          prompt: "What extra ingredient does Chebyshev have over Markov?",
          answer: "Variance.",
        },
        {
          prompt: "What structure often makes Chernoff the best choice here?",
          answer: "Independent Bernoulli-type sums.",
        },
      ],
      memoryHook: "Mean, variance, independence: choose your bound.",
      tags: ["probability", "tail-bounds", "markov", "chebyshev", "chernoff"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-standardize-clt",
      chapter: "Chapter 9: Central Limit Theorem",
      unit: "Concentration and Limits",
      topic: "Standardizing for the CLT",
      name: "Standardize for CLT",
      order: 17.1,
      useItWhen: "a sum or sample mean needs the normal approximation setup",
      looksLike: "subtract the mean, divide by standard deviation, z-style expression",
      doThis: "center first, scale second, then use the normal picture",
      thinkOfItAs: "turn the messy sum into a standard bell-scale version",
      watchOutFor: "forgetting to divide by the right spread for the sum or average",
      rememberThis: "CLT starts with center and scale",
      quickExample: {
        problem: "What are the first two CLT setup moves?",
        move: "Subtract the mean and divide by the standard deviation.",
      },
      typicalProblemShapes: [
        "Normal approximation for sample means or sums",
        "Set up a z-style variable before using CLT",
      ],
      miniDrill: [
        {
          prompt: "Do you standardize before or after using the normal table idea?",
          answer: "Before.",
        },
        {
          prompt: "What does standardizing do in one phrase?",
          answer: "Centers and rescales the random quantity.",
        },
      ],
      memoryHook: "Center, scale, then bell curve.",
      tags: ["probability", "clt", "standardization"],
      difficulty: "Standard",
    }),
  ],
};
