import type { BubbleCard, CourseContent } from "@/content/schema";

function makeProbabilityCard(
  card: Omit<BubbleCard, "subject" | "course">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Probability",
    ...card,
  };
}

export const probabilityCourse: CourseContent = {
  id: "probability",
  subject: "Mathematics",
  title: "Probability",
  shortDescription: "Counting, conditional probability, random variables, and expectation.",
  units: [
    "Counting",
    "Probability Basics",
    "Random Variables",
    "Joint Behavior",
    "Expectation and Variance",
    "Concentration and Limits",
  ],
  chapters: [
    "Chapter 1: Combinatorial Analysis",
    "Chapter 2: Probability: The Basics",
    "Chapter 3: Discrete Random Variables",
    "Chapter 4: Continuous Random Variables",
    "Chapter 5: Joint Distribution and Independence",
    "Chapter 6: Properties of Expectation",
    "Chapter 7: Covariance and Variance of Sums of Random Variables",
    "Chapter 8: Introduction to Concentration Inequalities",
    "Chapter 9: Central Limit Theorem",
  ],
  cards: [
    makeProbabilityCard({
      id: "prob-counting-rules",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Basic counting rules",
      name: "Basic Counting Rules",
      order: 1,
      useItWhen: "a problem asks how many outcomes are possible",
      looksLike: "how many ways..., choices in stages, either/or cases",
      doThis: "multiply for stages, add for separate cases",
      thinkOfItAs: "and means multiply, or means add",
      watchOutFor: "adding when the choices happen in sequence",
      rememberThis: "and multiply, or add",
      quickExample: {
        problem: "3 shirt choices and 4 pants choices. How many outfits?",
        move: "Multiply: 3 times 4.",
      },
      typicalProblemShapes: [
        "A process built from step 1 then step 2",
        "Separate non-overlapping cases that must be combined",
      ],
      miniDrill: [
        {
          prompt: "If choices happen in stages, do you add or multiply?",
          answer: "Multiply.",
        },
        {
          prompt: "If cases are separate alternatives, do you add or multiply?",
          answer: "Add.",
        },
      ],
      memoryHook: "And multiply. Or add.",
      tags: ["probability", "counting", "combinatorics"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-permutations",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Permutations",
      name: "Permutations",
      order: 2,
      useItWhen: "order matters",
      looksLike: "arrangements, lineups, rankings, passwords",
      doThis: "count ordered selections with factorial-style formulas",
      thinkOfItAs: "same people, different order, different outcome",
      watchOutFor: "using combinations when order matters",
      rememberThis: "permutations care about order",
      quickExample: {
        problem: "Choose and order 3 students from 10.",
        move: "Use a permutation count, not a combination count.",
      },
      typicalProblemShapes: [
        "Arrange objects in a row",
        "Choose winners with 1st, 2nd, and 3rd places",
      ],
      miniDrill: [
        {
          prompt: "Does order matter in a permutation?",
          answer: "Yes.",
        },
        {
          prompt: "Is ABC the same as CBA in a permutation problem?",
          answer: "No.",
        },
      ],
      memoryHook: "Permutation = arrangement.",
      tags: ["probability", "permutations", "counting"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-combinations",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Combinations",
      name: "Combinations",
      order: 3,
      useItWhen: "order does not matter",
      looksLike: "choose a committee, pick a hand, select a group",
      doThis: "count unordered selections with n choose k",
      thinkOfItAs: "same group, same outcome, no matter the order",
      watchOutFor: "counting the same group multiple times in different orders",
      rememberThis: "combinations ignore order",
      quickExample: {
        problem: "Choose 5 cards from a deck.",
        move: "Use a combination because the order of the 5 cards does not matter.",
      },
      typicalProblemShapes: [
        "Committee or team selection",
        "Hands, subsets, or chosen groups",
      ],
      miniDrill: [
        {
          prompt: "Does order matter in combinations?",
          answer: "No.",
        },
        {
          prompt: "Which is bigger for the same n and k: permutations or combinations?",
          answer: "Permutations, because they count more orderings.",
        },
      ],
      memoryHook: "Combination = choose a group.",
      tags: ["probability", "combinations", "counting"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-multinomial",
      chapter: "Chapter 1: Combinatorial Analysis",
      unit: "Counting",
      topic: "Multinomial coefficients",
      name: "Multinomial Coefficients",
      order: 4,
      useItWhen: "a set is split into several labeled groups",
      looksLike: "divide n objects into buckets of sizes a, b, c",
      doThis: "count how many ways to split into the group sizes",
      thinkOfItAs: "combinations with more than two buckets",
      watchOutFor: "treating a many-group split like one simple choose",
      rememberThis: "many buckets means multinomial",
      quickExample: {
        problem: "Split 10 people into groups of 4, 3, and 3.",
        move: "Use a multinomial count.",
      },
      typicalProblemShapes: [
        "Assign objects into labeled categories",
        "Count outcomes with several category totals fixed",
      ],
      miniDrill: [
        {
          prompt: "What is the multinomial idea in one phrase?",
          answer: "Split into several buckets.",
        },
        {
          prompt: "Is it just a one-step choose when there are 3 or more labeled groups?",
          answer: "No.",
        },
      ],
      memoryHook: "More than two groups? Think multinomial.",
      tags: ["probability", "multinomial", "counting"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-axioms",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Axioms of probability",
      name: "Probability Axioms",
      order: 5,
      useItWhen: "you need the basic rules probability must obey",
      looksLike: "P(A), P(sample space), disjoint events",
      doThis: "use nonnegative, whole space equals 1, and add disjoint events",
      thinkOfItAs: "the ground rules every probability model must follow",
      watchOutFor: "adding probabilities of overlapping events like they are disjoint",
      rememberThis: "whole space is 1",
      quickExample: {
        problem: "What is P(sample space)?",
        move: "1.",
      },
      typicalProblemShapes: [
        "Basic event calculations",
        "Checking whether a rule can be a probability model",
      ],
      miniDrill: [
        {
          prompt: "Can a probability be negative?",
          answer: "No.",
        },
        {
          prompt: "When can you add P(A) and P(B) directly?",
          answer: "When A and B are disjoint.",
        },
      ],
      memoryHook: "Probabilities live between 0 and 1, and all outcomes total 1.",
      tags: ["probability", "axioms", "basics"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-conditional",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Conditional probability",
      name: "Conditional Probability",
      order: 6,
      useItWhen: "the problem says given that something already happened",
      looksLike: "P(A given B)",
      doThis: "shrink the sample space to B, then measure A inside it",
      thinkOfItAs: "zooming in after new information arrives",
      watchOutFor: "using the old sample space after a condition changes the setup",
      rememberThis: "conditioning shrinks the universe",
      quickExample: {
        problem: "What changes first when you condition on B?",
        move: "The sample space shrinks to B.",
      },
      typicalProblemShapes: [
        "Given that a card is red, what is the chance it is a heart?",
        "Given a test is positive, what is the chance the patient has the disease?",
      ],
      miniDrill: [
        {
          prompt: "What does conditional probability do to the sample space?",
          answer: "It shrinks it.",
        },
        {
          prompt: "Can P(A given B) differ from P(A)?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Given B means live inside B.",
      tags: ["probability", "conditional", "basics"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-independence",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Independence",
      name: "Independence",
      order: 7,
      useItWhen: "one event does not change the chance of the other",
      looksLike: "independent events, product rule for events",
      doThis: "check whether P(A and B) equals P(A) times P(B)",
      thinkOfItAs: "knowing one tells you nothing new about the other",
      watchOutFor: "confusing disjoint with independent",
      rememberThis: "independent means product rule",
      quickExample: {
        problem: "What quick equation checks independence?",
        move: "P(A and B) = P(A)P(B).",
      },
      typicalProblemShapes: [
        "Repeated trials like coin flips",
        "Questions asking whether information changes probability",
      ],
      miniDrill: [
        {
          prompt: "Can disjoint nonzero events be independent?",
          answer: "No.",
        },
        {
          prompt: "What is the signature formula for independence?",
          answer: "P(A and B) = P(A)P(B).",
        },
      ],
      memoryHook: "No influence means product rule.",
      tags: ["probability", "independence", "conditional"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-bayes",
      chapter: "Chapter 2: Probability: The Basics",
      unit: "Probability Basics",
      topic: "Bayes' Formula",
      name: "Bayes' Formula",
      order: 8,
      useItWhen: "you need to reverse the condition",
      looksLike: "P(A given B) but you know P(B given A)",
      doThis: "use prior times likelihood over total evidence",
      thinkOfItAs: "reversing the arrow after new evidence",
      watchOutFor: "forgetting the denominator that totals all ways B can happen",
      rememberThis: "reverse the condition carefully",
      quickExample: {
        problem: "What usually goes in the denominator of Bayes?",
        move: "The total probability of the evidence.",
      },
      typicalProblemShapes: [
        "Medical test questions",
        "Spam filters or diagnosis style reversal problems",
      ],
      miniDrill: [
        {
          prompt: "Does Bayes reverse conditional direction?",
          answer: "Yes.",
        },
        {
          prompt: "What is the big trap in Bayes problems?",
          answer: "Ignoring base rates and the full denominator.",
        },
      ],
      memoryHook: "Bayes flips the condition, not the logic.",
      tags: ["probability", "bayes", "conditional"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-expected-value",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Random variables and expectation",
      name: "Expected Value",
      order: 9,
      useItWhen: "you need the long-run average payoff",
      looksLike: "E(X), average gain, average number, mean",
      doThis: "multiply each value by its probability and add",
      thinkOfItAs: "the weighted average of all possible outcomes",
      watchOutFor: "averaging values without using probabilities",
      rememberThis: "expected value is weighted average",
      quickExample: {
        problem: "What is the basic expectation move?",
        move: "Value times probability, then add.",
      },
      typicalProblemShapes: [
        "Games of chance and expected payoff",
        "Average count or average cost questions",
      ],
      miniDrill: [
        {
          prompt: "Do unlikely big outcomes still matter to expectation?",
          answer: "Yes, if the payoff is big enough.",
        },
        {
          prompt: "Is expectation just the most likely value?",
          answer: "No.",
        },
      ],
      memoryHook: "Expectation = weighted average.",
      tags: ["probability", "expectation", "random-variable"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-linearity",
      chapter: "Chapter 6: Properties of Expectation",
      unit: "Expectation and Variance",
      topic: "Linearity of expectation",
      name: "Linearity of Expectation",
      order: 10,
      useItWhen: "a random total is a sum of smaller random pieces",
      looksLike: "E(X + Y + ...)",
      doThis: "split expectation across the sum even if the variables are dependent",
      thinkOfItAs: "expectation distributes over addition",
      watchOutFor: "thinking independence is required here",
      rememberThis: "linearity does not need independence",
      quickExample: {
        problem: "Do you need independence for E(X + Y) = E(X) + E(Y)?",
        move: "No.",
      },
      typicalProblemShapes: [
        "Expected number of successes, matches, or collisions",
        "Indicator-variable counting arguments",
      ],
      miniDrill: [
        {
          prompt: "What is the fast move for expectation of a sum?",
          answer: "Split the sum.",
        },
        {
          prompt: "Does dependence break linearity of expectation?",
          answer: "No.",
        },
      ],
      memoryHook: "Expectation splits sums for free.",
      tags: ["probability", "linearity", "expectation"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-variance",
      chapter: "Chapter 7: Covariance and Variance of Sums of Random Variables",
      unit: "Expectation and Variance",
      topic: "Variance",
      name: "Variance",
      order: 11,
      useItWhen: "you care about spread, not just average",
      looksLike: "Var(X), spread around the mean",
      doThis: "measure average squared distance from the mean",
      thinkOfItAs: "how noisy the random variable is",
      watchOutFor: "treating variance like standard deviation or like the mean itself",
      rememberThis: "variance measures spread",
      quickExample: {
        problem: "What does variance tell you that expectation does not?",
        move: "How spread out the outcomes are.",
      },
      typicalProblemShapes: [
        "Risk or volatility questions",
        "Variance of sums and transformations",
      ],
      miniDrill: [
        {
          prompt: "Can two random variables have the same expectation but different variance?",
          answer: "Yes.",
        },
        {
          prompt: "Does variance measure center or spread?",
          answer: "Spread.",
        },
      ],
      memoryHook: "Mean is center. Variance is spread.",
      tags: ["probability", "variance", "spread"],
      difficulty: "Starter",
    }),
    makeProbabilityCard({
      id: "prob-distributions",
      chapter: "Chapter 3: Discrete Random Variables",
      unit: "Random Variables",
      topic: "Special distributions",
      name: "Common Distributions",
      order: 12,
      useItWhen: "a problem smells like repeated trials, waiting time, or rare counts",
      looksLike: "Bernoulli, Binomial, Geometric, Poisson, Normal",
      doThis: "match the story to the distribution pattern before using formulas",
      thinkOfItAs: "story first, formula second",
      watchOutFor: "using a distribution formula before checking the setup assumptions",
      rememberThis: "recognize the story pattern",
      quickExample: {
        problem: "Repeated yes/no trials with fixed p. What model fits?",
        move: "Binomial if you count successes, geometric if you wait for the first success.",
      },
      typicalProblemShapes: [
        "Independent repeated trials",
        "Rare-event counts in a fixed interval",
      ],
      miniDrill: [
        {
          prompt: "Count successes in n independent trials. Which model?",
          answer: "Binomial.",
        },
        {
          prompt: "Wait for the first success. Which model?",
          answer: "Geometric.",
        },
      ],
      memoryHook: "Match the story before the formula.",
      tags: ["probability", "distribution", "binomial", "geometric", "poisson"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-continuous-density",
      chapter: "Chapter 4: Continuous Random Variables",
      unit: "Random Variables",
      topic: "Continuous distributions and density",
      name: "Density Functions",
      order: 13,
      useItWhen: "the random variable can take a continuum of values",
      looksLike: "f(x), density curve, integrate for probability",
      doThis: "use area under the density over an interval",
      thinkOfItAs: "continuous probability lives in area, not point masses",
      watchOutFor: "asking for probability at one exact point like it has a chunk of mass",
      rememberThis: "continuous probabilities come from intervals",
      quickExample: {
        problem: "How do you get probability from a density?",
        move: "Integrate over the interval.",
      },
      typicalProblemShapes: [
        "Normal or uniform density questions",
        "Probability over a range of values",
      ],
      miniDrill: [
        {
          prompt: "What is the probability at one exact point for a continuous variable?",
          answer: "0.",
        },
        {
          prompt: "What gives probability on an interval?",
          answer: "Area under the density curve.",
        },
      ],
      memoryHook: "Density means area, not point mass.",
      tags: ["probability", "continuous", "density"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-joint-distribution",
      chapter: "Chapter 5: Joint Distribution and Independence",
      unit: "Joint Behavior",
      topic: "Joint distributions",
      name: "Joint Distributions",
      order: 14,
      useItWhen: "two random variables are tracked together",
      looksLike: "P(X = x, Y = y) or joint density f(x, y)",
      doThis: "read the pair behavior first, then get marginals or conditionals from it",
      thinkOfItAs: "one table or surface for two variables at once",
      watchOutFor: "multiplying marginals when independence is not given",
      rememberThis: "joint comes first, marginals can come from it",
      quickExample: {
        problem: "What does a joint distribution describe?",
        move: "How two variables behave together.",
      },
      typicalProblemShapes: [
        "Two-way tables or density surfaces",
        "Find marginal or conditional distributions from a joint one",
      ],
      miniDrill: [
        {
          prompt: "Can you get marginals from a joint distribution?",
          answer: "Yes.",
        },
        {
          prompt: "Does joint always equal product of marginals?",
          answer: "No. Only under independence.",
        },
      ],
      memoryHook: "Joint tells the whole pair story.",
      tags: ["probability", "joint-distribution", "independence"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-covariance-correlation",
      chapter: "Chapter 7: Covariance and Variance of Sums of Random Variables",
      unit: "Joint Behavior",
      topic: "Covariance and correlation",
      name: "Covariance and Correlation",
      order: 15,
      useItWhen: "you need to know whether two variables move together",
      looksLike: "Cov(X,Y), Corr(X,Y)",
      doThis: "use covariance for direction of relationship and correlation for scaled strength",
      thinkOfItAs: "do they rise together, fall opposite, or barely connect",
      watchOutFor: "treating zero correlation like guaranteed independence",
      rememberThis: "correlation is scaled covariance",
      quickExample: {
        problem: "What does positive covariance suggest?",
        move: "The variables tend to move in the same direction.",
      },
      typicalProblemShapes: [
        "Scatterplot-style dependence questions",
        "Variance of a sum using covariance terms",
      ],
      miniDrill: [
        {
          prompt: "Does correlation have units?",
          answer: "No.",
        },
        {
          prompt: "Does zero correlation always mean independence?",
          answer: "No.",
        },
      ],
      memoryHook: "Covariance shows direction. Correlation rescales it.",
      tags: ["probability", "covariance", "correlation"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-markov-chebyshev",
      chapter: "Chapter 8: Introduction to Concentration Inequalities",
      unit: "Concentration and Limits",
      topic: "Markov and Chebyshev inequalities",
      name: "Markov and Chebyshev",
      order: 16,
      useItWhen: "you need a quick upper bound without full distribution details",
      looksLike: "bound the chance a random variable gets large",
      doThis: "use Markov for nonnegative variables and Chebyshev when variance is available",
      thinkOfItAs: "rough but reliable guardrails",
      watchOutFor: "expecting these bounds to be sharp",
      rememberThis: "Markov uses mean, Chebyshev uses variance",
      quickExample: {
        problem: "Which bound uses variance explicitly?",
        move: "Chebyshev.",
      },
      typicalProblemShapes: [
        "Upper bounds on tail probabilities",
        "Questions with expectation or variance but no exact distribution",
      ],
      miniDrill: [
        {
          prompt: "What extra ingredient does Chebyshev need beyond expectation?",
          answer: "Variance.",
        },
        {
          prompt: "What is the main job of these inequalities?",
          answer: "Give probability bounds.",
        },
      ],
      memoryHook: "Markov for rough mean bounds, Chebyshev for spread bounds.",
      tags: ["probability", "markov", "chebyshev", "concentration"],
      difficulty: "Standard",
    }),
    makeProbabilityCard({
      id: "prob-clt",
      chapter: "Chapter 9: Central Limit Theorem",
      unit: "Concentration and Limits",
      topic: "Central Limit Theorem",
      name: "Central Limit Theorem",
      order: 17,
      useItWhen: "a sum or average of many random pieces shows up",
      looksLike: "large n, sample mean, standardized sum",
      doThis: "normalize the sum or average and approximate with a normal shape",
      thinkOfItAs: "many random bumps blending into a bell curve",
      watchOutFor: "using CLT with tiny sample sizes or strong dependence without checking assumptions",
      rememberThis: "many small random pieces often look normal",
      quickExample: {
        problem: "What usually becomes approximately normal under CLT?",
        move: "A properly standardized sum or average of many variables.",
      },
      typicalProblemShapes: [
        "Sample means for large n",
        "Approximate probabilities for sums of independent terms",
      ],
      miniDrill: [
        {
          prompt: "Does CLT talk about a single variable or many combined variables?",
          answer: "Many combined variables.",
        },
        {
          prompt: "What shape usually appears in the limit?",
          answer: "A normal bell curve.",
        },
      ],
      memoryHook: "Big random sums drift toward normal.",
      tags: ["probability", "clt", "normal", "limit"],
      difficulty: "Stretch",
    }),
  ],
};
