import type { BubbleCard, CourseContent } from "@/content/schema";

function makeProofCard(
  card: Omit<BubbleCard, "subject" | "course">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Intro to Proof",
    ...card,
  };
}

export const proofCourse: CourseContent = {
  id: "intro-proof",
  subject: "Mathematics",
  title: "Intro to Proof",
  shortDescription: "Logic, proof patterns, sets, induction, and proof-writing basics.",
  units: [
    "Proof Basics",
    "Logic and Quantifiers",
    "Sets and Functions",
    "Number Theory Basics",
    "Induction",
    "Relations and Cardinality",
  ],
  chapters: [
    "Chapter 1: A Paradigm Shift",
    "Chapter 2: Logic and the Language of Proofs",
    "Chapter 3: Sets and Functions",
    "Chapter 4: Divisibility and the Euclidean Algorithm",
    "Chapter 5: Mathematical Induction and Well-ordering",
    "Chapter 7: Relations and Partitions",
    "Chapter 8: Cardinalities of Infinite Sets",
  ],
  cards: [
    makeProofCard({
      id: "proof-what-counts",
      chapter: "Chapter 1: A Paradigm Shift",
      unit: "Proof Basics",
      topic: "What counts as a proof",
      name: "What Counts as a Proof",
      order: 1,
      useItWhen: "you need to justify a statement, not just test examples",
      looksLike: "show that..., prove that..., justify why...",
      doThis: "start from known facts and build a chain that forces the conclusion",
      thinkOfItAs: "closing every loophole, not just giving a vibe",
      watchOutFor: "using one example like it proves the whole statement",
      rememberThis: "examples suggest, proofs finish",
      quickExample: {
        problem: "Why is checking n = 1, 2, 3 not enough?",
        move: "Because the claim is about all cases, not a few cases.",
      },
      typicalProblemShapes: [
        "A universal statement about all integers or all real numbers",
        "A claim where examples feel convincing but do not settle it",
      ],
      miniDrill: [
        {
          prompt: "Does one correct example prove a universal statement?",
          answer: "No. It only shows the claim can happen once.",
        },
        {
          prompt: "What should a proof do to the conclusion?",
          answer: "Make it unavoidable from accepted facts.",
        },
      ],
      memoryHook: "Examples point. Proofs lock it in.",
      tags: ["proof", "basics", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-definitions",
      chapter: "Chapter 1: A Paradigm Shift",
      unit: "Proof Basics",
      topic: "Definitions, theorems, and conjectures",
      name: "Definitions vs Theorems",
      order: 2,
      useItWhen: "you need to know whether to unpack a definition or prove a claim",
      looksLike: "even number, injective, theorem, conjecture",
      doThis: "if it is a definition, unpack it; if it is a theorem, prove it or use it",
      thinkOfItAs: "definitions are rules of the game, theorems are wins inside the game",
      watchOutFor: "trying to prove a definition instead of using it",
      rememberThis: "definitions get unpacked, theorems get justified",
      quickExample: {
        problem: "To prove a number is even, what do you reach for first?",
        move: "The definition: write it as 2k.",
      },
      typicalProblemShapes: [
        "A proof begins with a word like even, prime, injective, or subset",
        "A problem asks whether a statement is proved or still a conjecture",
      ],
      miniDrill: [
        {
          prompt: "What is the fastest start when a proof uses a technical word?",
          answer: "Write down the exact definition.",
        },
        {
          prompt: "Is a conjecture already proved?",
          answer: "No. It is a claim believed or suspected but not yet established.",
        },
      ],
      memoryHook: "Technical word? Open the definition.",
      tags: ["proof", "definitions", "theorems"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-direct",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Direct proof",
      name: "Direct Proof",
      order: 3,
      useItWhen: "you can start from the hypothesis and push forward",
      looksLike: "if P then Q and the path from P to Q is straightforward",
      doThis: "assume the hypothesis, use algebra or definitions, and land on the conclusion",
      thinkOfItAs: "walking straight from start to finish",
      watchOutFor: "starting from the conclusion and pretending that proves it",
      rememberThis: "assume P, reach Q",
      quickExample: {
        problem: "If n is even, prove n squared is even.",
        move: "Write n = 2k and simplify.",
      },
      typicalProblemShapes: [
        "If-then statements with algebraic structure",
        "Claims where definitions and substitution move the proof forward",
      ],
      miniDrill: [
        {
          prompt: "What do you assume first in a direct proof of if P then Q?",
          answer: "Assume P.",
        },
        {
          prompt: "Does a direct proof usually unpack definitions early?",
          answer: "Yes. That is often the whole move.",
        },
      ],
      memoryHook: "Start at P and walk to Q.",
      tags: ["proof", "direct-proof", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-contrapositive",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Proof by contrapositive",
      name: "Contrapositive",
      order: 4,
      useItWhen: "the conclusion is easier to negate than prove directly",
      looksLike: "if P then Q, but not Q then not P looks cleaner",
      doThis: "flip and negate the statement, then prove that version",
      thinkOfItAs: "taking the back road because the front road is blocked",
      watchOutFor: "proving the converse instead of the contrapositive",
      rememberThis: "flip and negate both parts",
      quickExample: {
        problem: "If n squared is even, prove n is even.",
        move: "Use the contrapositive: if n is odd, then n squared is odd.",
      },
      typicalProblemShapes: [
        "A direct proof gets messy but the negated conclusion is simple",
        "Odd/even or divisibility claims",
      ],
      miniDrill: [
        {
          prompt: "What is the contrapositive of if P then Q?",
          answer: "If not Q, then not P.",
        },
        {
          prompt: "Does the contrapositive have the same truth value as the original?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Flip it, negate it, prove that.",
      tags: ["proof", "contrapositive", "logic"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-contradiction",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Proof by contradiction",
      name: "Contradiction",
      order: 5,
      useItWhen: "assuming the opposite creates an impossible result",
      looksLike: "assume not..., then reach a clash",
      doThis: "assume the claim is false and push until something breaks",
      thinkOfItAs: "following a bad path until it crashes",
      watchOutFor: "ending with something surprising but not actually impossible",
      rememberThis: "assume the opposite, force a contradiction",
      quickExample: {
        problem: "How do many irrationality proofs start?",
        move: "Assume the number is rational, then derive an impossibility.",
      },
      typicalProblemShapes: [
        "Existence or irrationality proofs",
        "Statements where the opposite assumption is easy to write down",
      ],
      miniDrill: [
        {
          prompt: "What do you assume first in a contradiction proof?",
          answer: "Assume the claim you want is false.",
        },
        {
          prompt: "What counts as a contradiction?",
          answer: "A true impossibility like 0 = 1 or both P and not P.",
        },
      ],
      memoryHook: "Assume opposite. Crash the logic.",
      tags: ["proof", "contradiction", "logic"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-quantifiers",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Quantifiers",
      name: "Quantifiers",
      order: 6,
      useItWhen: "a statement says for all or there exists",
      looksLike: "for every x..., there exists y...",
      doThis: "track who chooses what and in what order",
      thinkOfItAs: "a script where order changes the whole meaning",
      watchOutFor: "swapping for all and there exists like they mean the same thing",
      rememberThis: "quantifier order matters",
      quickExample: {
        problem: "Why do 'for every x there exists y' and 'there exists y for every x' differ?",
        move: "Because the chooser changes, so the claim changes.",
      },
      typicalProblemShapes: [
        "Statements with all, some, every, or exists",
        "Negations of logical statements",
      ],
      miniDrill: [
        {
          prompt: "Does changing quantifier order change meaning?",
          answer: "Yes. A lot.",
        },
        {
          prompt: "What is the main thing to track in a quantified statement?",
          answer: "Who gets chosen first and by whom.",
        },
      ],
      memoryHook: "All and exists are not interchangeable.",
      tags: ["proof", "quantifiers", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-negating-quantifiers",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Negating quantified statements",
      name: "Negating Quantifiers",
      order: 7,
      useItWhen: "you need the opposite of a statement with all or exists",
      looksLike: "not for all..., not there exists...",
      doThis: "swap for all with there exists and negate the inside claim",
      thinkOfItAs: "flip the quantifier, flip the statement",
      watchOutFor: "negating only the inside and forgetting to swap the quantifier",
      rememberThis: "not all becomes exists not",
      quickExample: {
        problem: "Negate 'for every x, P(x)'.",
        move: "There exists an x such that not P(x).",
      },
      typicalProblemShapes: [
        "Statements where the proof needs a clean negation first",
        "Set or function claims using every and exists",
      ],
      miniDrill: [
        {
          prompt: "What does not-for-all become?",
          answer: "There exists at least one counterexample.",
        },
        {
          prompt: "What does not-there-exists become?",
          answer: "For all, not.",
        },
      ],
      memoryHook: "Swap the quantifier and negate the core.",
      tags: ["proof", "negation", "quantifiers"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-sets-subsets",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "Sets and subset proofs",
      name: "Subset Proofs",
      order: 8,
      useItWhen: "you need to show one set sits inside another",
      looksLike: "prove A is a subset of B",
      doThis: "pick a generic element of A and show it must also be in B",
      thinkOfItAs: "follow one random member across the fence",
      watchOutFor: "trying to compare whole sets without using elements",
      rememberThis: "to prove subset, chase an element",
      quickExample: {
        problem: "How do you start A subset of B?",
        move: "Take x in A.",
      },
      typicalProblemShapes: [
        "Union, intersection, and complement identities",
        "Set equality proofs built from two subset proofs",
      ],
      miniDrill: [
        {
          prompt: "How do you prove A equals B?",
          answer: "Show A subset of B and B subset of A.",
        },
        {
          prompt: "What is the standard first move for a subset proof?",
          answer: "Pick an arbitrary element in the left set.",
        },
      ],
      memoryHook: "Set proof? Grab one element.",
      tags: ["proof", "sets", "subset"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-functions",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "One-to-one and onto functions",
      name: "Injective vs Surjective",
      order: 9,
      useItWhen: "a proof asks whether a function is one-to-one or onto",
      looksLike: "show f is injective, surjective, or bijective",
      doThis: "for injective, start with equal outputs; for onto, start with a target output",
      thinkOfItAs: "injective means no collision, surjective means no misses",
      watchOutFor: "using the wrong starting point for the wrong property",
      rememberThis: "injective starts with outputs equal; onto starts with target chosen",
      quickExample: {
        problem: "How do you start an injective proof?",
        move: "Assume f(a) = f(b).",
      },
      typicalProblemShapes: [
        "Functions between sets or number systems",
        "Proofs asking for bijection or inverse-function logic",
      ],
      miniDrill: [
        {
          prompt: "What is the first move for surjective?",
          answer: "Take an arbitrary target y in the codomain.",
        },
        {
          prompt: "What does bijective mean?",
          answer: "Injective and surjective.",
        },
      ],
      memoryHook: "No collisions, no misses.",
      tags: ["proof", "functions", "injective", "surjective"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-divisibility",
      chapter: "Chapter 4: Divisibility and the Euclidean Algorithm",
      unit: "Number Theory Basics",
      topic: "Divisibility and congruence",
      name: "Divisibility and Congruence",
      order: 10,
      useItWhen: "integers, remainders, or mod language show up",
      looksLike: "a divides b, a congruent to b mod n",
      doThis: "rewrite divisibility as multiples and congruence as same remainder class",
      thinkOfItAs: "mod means numbers land in the same bucket",
      watchOutFor: "treating congruence like ordinary equality in every context",
      rememberThis: "divides means multiple; mod means same remainder",
      quickExample: {
        problem: "What does a congruent to b mod n mean?",
        move: "n divides a minus b.",
      },
      typicalProblemShapes: [
        "Even/odd or remainder arguments",
        "Proofs that reduce expressions modulo n",
      ],
      miniDrill: [
        {
          prompt: "What does a divides b mean?",
          answer: "b = ak for some integer k.",
        },
        {
          prompt: "What does mod say two numbers share?",
          answer: "The same remainder class.",
        },
      ],
      memoryHook: "Mod = same bucket after division.",
      tags: ["proof", "number-theory", "divisibility", "congruence"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-euclidean-algorithm",
      chapter: "Chapter 4: Divisibility and the Euclidean Algorithm",
      unit: "Number Theory Basics",
      topic: "Greatest common divisors and the Euclidean Algorithm",
      name: "Euclidean Algorithm",
      order: 11,
      useItWhen: "you need a gcd quickly",
      looksLike: "gcd(a, b) with repeated division",
      doThis: "keep replacing the pair by divisor and remainder until the remainder is 0",
      thinkOfItAs: "shrinking the problem without changing the gcd",
      watchOutFor: "stopping too early before the remainder hits 0",
      rememberThis: "last nonzero remainder is the gcd",
      quickExample: {
        problem: "What is the gcd at the end of the Euclidean Algorithm?",
        move: "The last nonzero remainder.",
      },
      typicalProblemShapes: [
        "Large gcd computations",
        "Number theory proofs using repeated division",
      ],
      miniDrill: [
        {
          prompt: "What replaces the pair (a, b) in the next step?",
          answer: "The old divisor and the old remainder.",
        },
        {
          prompt: "When do you stop?",
          answer: "When the remainder becomes 0.",
        },
      ],
      memoryHook: "Keep the remainder chain going.",
      tags: ["proof", "gcd", "euclidean-algorithm"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-induction",
      chapter: "Chapter 5: Mathematical Induction and Well-ordering",
      unit: "Induction",
      topic: "Proof by induction",
      name: "Proof by Induction",
      order: 12,
      useItWhen: "a statement depends on a positive integer n",
      looksLike: "prove for all n, recursive formulas, sums, inequalities",
      doThis: "do base case, assume k case, then prove k plus 1 case",
      thinkOfItAs: "setting up dominoes and then tipping one",
      watchOutFor: "using the thing you are trying to prove without saying it is the inductive hypothesis",
      rememberThis: "base, assume, push forward",
      quickExample: {
        problem: "What are the three core pieces of induction?",
        move: "Base case, inductive hypothesis, inductive step.",
      },
      typicalProblemShapes: [
        "Sum formulas and divisibility by n",
        "Statements with n plus 1 built from n",
      ],
      miniDrill: [
        {
          prompt: "What is the purpose of the base case?",
          answer: "Start the chain.",
        },
        {
          prompt: "What happens in the inductive step?",
          answer: "Use the k case to prove the k plus 1 case.",
        },
      ],
      memoryHook: "Base, assume, next case.",
      tags: ["proof", "induction", "domino"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-strong-induction",
      chapter: "Chapter 5: Mathematical Induction and Well-ordering",
      unit: "Induction",
      topic: "Strong induction",
      name: "Strong Induction",
      order: 13,
      useItWhen: "the next step needs more than just the previous case",
      looksLike: "assume all cases up to k, prove case k plus 1",
      doThis: "assume the whole block before k plus 1, not just the single k case",
      thinkOfItAs: "using the whole ladder below you, not one rung",
      watchOutFor: "using many earlier cases while pretending you only assumed one",
      rememberThis: "strong induction assumes all earlier cases",
      quickExample: {
        problem: "When is strong induction better than ordinary induction?",
        move: "When the next case depends on several earlier cases.",
      },
      typicalProblemShapes: [
        "Recursive definitions with multiple previous terms",
        "Prime factorization or decomposition arguments",
      ],
      miniDrill: [
        {
          prompt: "What is the big difference in strong induction?",
          answer: "You assume all earlier cases up to k.",
        },
        {
          prompt: "Do strong and ordinary induction prove the same kind of universal result?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Need more history? Use strong induction.",
      tags: ["proof", "strong-induction", "recursion"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-equivalence-relations",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Equivalence relations",
      name: "Equivalence Relations",
      order: 14,
      useItWhen: "a relation claims objects count as the same in some way",
      looksLike: "show reflexive, symmetric, and transitive",
      doThis: "check the three properties one by one",
      thinkOfItAs: "a legal same-team rule",
      watchOutFor: "proving only one or two of the properties",
      rememberThis: "equivalence means three checks",
      quickExample: {
        problem: "What three properties define an equivalence relation?",
        move: "Reflexive, symmetric, transitive.",
      },
      typicalProblemShapes: [
        "Relations on numbers, sets, or functions",
        "Proofs that a relation creates classes or partitions",
      ],
      miniDrill: [
        {
          prompt: "If a relation is missing symmetry, is it an equivalence relation?",
          answer: "No.",
        },
        {
          prompt: "What structure often appears after an equivalence relation?",
          answer: "Equivalence classes or a partition.",
        },
      ],
      memoryHook: "Reflexive, symmetric, transitive. All three.",
      tags: ["proof", "relations", "equivalence"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-countable-uncountable",
      chapter: "Chapter 8: Cardinalities of Infinite Sets",
      unit: "Relations and Cardinality",
      topic: "Countable and uncountable sets",
      name: "Countable vs Uncountable",
      order: 15,
      useItWhen: "a problem compares sizes of infinite sets",
      looksLike: "countable, uncountable, bijection to naturals, diagonal argument",
      doThis: "look for a listing if countable or a diagonal-style escape if uncountable",
      thinkOfItAs: "can you put them in a numbered list or not",
      watchOutFor: "thinking infinite automatically means uncountable",
      rememberThis: "countable means listable",
      quickExample: {
        problem: "What is the core question for countability?",
        move: "Can the set be listed in sequence like 1, 2, 3, ...?",
      },
      typicalProblemShapes: [
        "Integers, rationals, and reals comparisons",
        "Arguments using bijections or Cantor's diagonal idea",
      ],
      miniDrill: [
        {
          prompt: "Are the integers countable?",
          answer: "Yes.",
        },
        {
          prompt: "What is the classic move to show the reals are uncountable?",
          answer: "Diagonalization.",
        },
      ],
      memoryHook: "Infinite is not one-size-fits-all.",
      tags: ["proof", "countable", "uncountable", "cardinality"],
      difficulty: "Stretch",
    }),
  ],
};
