import type { BubbleCard, CourseContent } from "@/content/schema";

function makeProofCard(
  card: Omit<BubbleCard, "subject" | "course" | "courseCode">,
): BubbleCard {
  return {
    subject: "Mathematics",
    course: "Introduction to Abstract Mathematics",
    courseCode: "MATH 13",
    ...card,
  };
}

export const proofCourse: CourseContent = {
  id: "intro-proof",
  subject: "Mathematics",
  title: "Introduction to Abstract Mathematics",
  institution: "UCI",
  courseCodes: ["MATH 13"],
  aliases: ["Intro to Proof", "Abstract Math"],
  shortDescription:
    "Logic, proof patterns, sets, induction, and abstract-math writing basics.",
  units: [
    "Proof Basics",
    "Logic and Quantifiers",
    "Sets and Functions",
    "Number Theory Basics",
    "Induction",
    "Set Theory II",
    "Relations and Cardinality",
  ],
  chapters: [
    "Chapter 1: A Paradigm Shift",
    "Chapter 2: Logic and the Language of Proofs",
    "Chapter 3: Sets and Functions",
    "Chapter 4: Divisibility and the Euclidean Algorithm",
    "Chapter 5: Mathematical Induction and Well-ordering",
    "Chapter 6: Set Theory, Part II",
    "Chapter 7: Relations and Partitions",
    "Chapter 8: Cardinalities of Infinite Sets",
  ],
  cards: [
    makeProofCard({
      id: "proof-what-counts",
      chapter: "Chapter 1: A Paradigm Shift",
      unit: "Proof Basics",
      topic: "What counts as a proof",
      name: "What Counts as a Proof",
      order: 1,
      useItWhen: "you need to justify a statement, not just test examples",
      looksLike: "show that..., prove that..., justify why...",
      doThis: "start from known facts and build a chain that forces the conclusion",
      thinkOfItAs: "closing every loophole, not just giving a vibe",
      watchOutFor: "using one example like it proves the whole statement",
      rememberThis: "examples suggest, proofs finish",
      quickExample: {
        problem: "Why is checking n = 1, 2, 3 not enough?",
        move: "Because the claim is about all cases, not a few cases.",
      },
      typicalProblemShapes: [
        "A universal statement about all integers or all real numbers",
        "A claim where examples feel convincing but do not settle it",
      ],
      miniDrill: [
        {
          prompt: "Does one correct example prove a universal statement?",
          answer: "No. It only shows the claim can happen once.",
        },
        {
          prompt: "What should a proof do to the conclusion?",
          answer: "Make it unavoidable from accepted facts.",
        },
      ],
      memoryHook: "Examples point. Proofs lock it in.",
      tags: ["proof", "basics", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-definitions",
      chapter: "Chapter 1: A Paradigm Shift",
      unit: "Proof Basics",
      topic: "Definitions, theorems, and conjectures",
      name: "Definitions vs Theorems",
      order: 2,
      useItWhen: "you need to know whether to unpack a definition or prove a claim",
      looksLike: "even number, injective, theorem, conjecture",
      doThis: "if it is a definition, unpack it; if it is a theorem, prove it or use it",
      thinkOfItAs: "definitions are rules of the game, theorems are wins inside the game",
      watchOutFor: "trying to prove a definition instead of using it",
      rememberThis: "definitions get unpacked, theorems get justified",
      quickExample: {
        problem: "To prove a number is even, what do you reach for first?",
        move: "The definition: write it as 2k.",
      },
      typicalProblemShapes: [
        "A proof begins with a word like even, prime, injective, or subset",
        "A problem asks whether a statement is proved or still a conjecture",
      ],
      miniDrill: [
        {
          prompt: "What is the fastest start when a proof uses a technical word?",
          answer: "Write down the exact definition.",
        },
        {
          prompt: "Is a conjecture already proved?",
          answer: "No. It is a claim believed or suspected but not yet established.",
        },
      ],
      memoryHook: "Technical word? Open the definition.",
      tags: ["proof", "definitions", "theorems"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-direct",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Direct proof",
      name: "Direct Proof",
      order: 3,
      useItWhen: "you can start from the hypothesis and push forward",
      looksLike: "if P then Q and the path from P to Q is straightforward",
      doThis: "assume the hypothesis, use algebra or definitions, and land on the conclusion",
      thinkOfItAs: "walking straight from start to finish",
      watchOutFor: "starting from the conclusion and pretending that proves it",
      rememberThis: "assume P, reach Q",
      quickExample: {
        problem: "If n is even, prove n squared is even.",
        move: "Write n = 2k and simplify.",
      },
      typicalProblemShapes: [
        "If-then statements with algebraic structure",
        "Claims where definitions and substitution move the proof forward",
      ],
      miniDrill: [
        {
          prompt: "What do you assume first in a direct proof of if P then Q?",
          answer: "Assume P.",
        },
        {
          prompt: "Does a direct proof usually unpack definitions early?",
          answer: "Yes. That is often the whole move.",
        },
      ],
      memoryHook: "Start at P and walk to Q.",
      tags: ["proof", "direct-proof", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-contrapositive",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Proof by contrapositive",
      name: "Contrapositive",
      order: 4,
      useItWhen: "the conclusion is easier to negate than prove directly",
      looksLike: "if P then Q, but not Q then not P looks cleaner",
      doThis: "flip and negate the statement, then prove that version",
      thinkOfItAs: "taking the back road because the front road is blocked",
      watchOutFor: "proving the converse instead of the contrapositive",
      rememberThis: "flip and negate both parts",
      quickExample: {
        problem: "If n squared is even, prove n is even.",
        move: "Use the contrapositive: if n is odd, then n squared is odd.",
      },
      typicalProblemShapes: [
        "A direct proof gets messy but the negated conclusion is simple",
        "Odd/even or divisibility claims",
      ],
      miniDrill: [
        {
          prompt: "What is the contrapositive of if P then Q?",
          answer: "If not Q, then not P.",
        },
        {
          prompt: "Does the contrapositive have the same truth value as the original?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Flip it, negate it, prove that.",
      tags: ["proof", "contrapositive", "logic"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-contradiction",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Proof by contradiction",
      name: "Contradiction",
      order: 5,
      useItWhen: "assuming the opposite creates an impossible result",
      looksLike: "assume not..., then reach a clash",
      doThis: "assume the claim is false and push until something breaks",
      thinkOfItAs: "following a bad path until it crashes",
      watchOutFor: "ending with something surprising but not actually impossible",
      rememberThis: "assume the opposite, force a contradiction",
      quickExample: {
        problem: "How do many irrationality proofs start?",
        move: "Assume the number is rational, then derive an impossibility.",
      },
      typicalProblemShapes: [
        "Existence or irrationality proofs",
        "Statements where the opposite assumption is easy to write down",
      ],
      miniDrill: [
        {
          prompt: "What do you assume first in a contradiction proof?",
          answer: "Assume the claim you want is false.",
        },
        {
          prompt: "What counts as a contradiction?",
          answer: "A true impossibility like 0 = 1 or both P and not P.",
        },
      ],
      memoryHook: "Assume opposite. Crash the logic.",
      tags: ["proof", "contradiction", "logic"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-quantifiers",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Quantifiers",
      name: "Quantifiers",
      order: 6,
      useItWhen: "a statement says for all or there exists",
      looksLike: "for every x..., there exists y...",
      doThis: "track who chooses what and in what order",
      thinkOfItAs: "a script where order changes the whole meaning",
      watchOutFor: "swapping for all and there exists like they mean the same thing",
      rememberThis: "quantifier order matters",
      quickExample: {
        problem: "Why do 'for every x there exists y' and 'there exists y for every x' differ?",
        move: "Because the chooser changes, so the claim changes.",
      },
      typicalProblemShapes: [
        "Statements with all, some, every, or exists",
        "Negations of logical statements",
      ],
      miniDrill: [
        {
          prompt: "Does changing quantifier order change meaning?",
          answer: "Yes. A lot.",
        },
        {
          prompt: "What is the main thing to track in a quantified statement?",
          answer: "Who gets chosen first and by whom.",
        },
      ],
      memoryHook: "All and exists are not interchangeable.",
      tags: ["proof", "quantifiers", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-negating-quantifiers",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Negating quantified statements",
      name: "Negating Quantifiers",
      order: 7,
      useItWhen: "you need the opposite of a statement with all or exists",
      looksLike: "not for all..., not there exists...",
      doThis: "swap for all with there exists and negate the inside claim",
      thinkOfItAs: "flip the quantifier, flip the statement",
      watchOutFor: "negating only the inside and forgetting to swap the quantifier",
      rememberThis: "not all becomes exists not",
      quickExample: {
        problem: "Negate 'for every x, P(x)'.",
        move: "There exists an x such that not P(x).",
      },
      typicalProblemShapes: [
        "Statements where the proof needs a clean negation first",
        "Set or function claims using every and exists",
      ],
      miniDrill: [
        {
          prompt: "What does not-for-all become?",
          answer: "There exists at least one counterexample.",
        },
        {
          prompt: "What does not-there-exists become?",
          answer: "For all, not.",
        },
      ],
      memoryHook: "Swap the quantifier and negate the core.",
      tags: ["proof", "negation", "quantifiers"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-sets-subsets",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "Sets and subset proofs",
      name: "Subset Proofs",
      order: 8,
      useItWhen: "you need to show one set sits inside another",
      looksLike: "prove A is a subset of B",
      doThis: "pick a generic element of A and show it must also be in B",
      thinkOfItAs: "follow one random member across the fence",
      watchOutFor: "trying to compare whole sets without using elements",
      rememberThis: "to prove subset, chase an element",
      quickExample: {
        problem: "How do you start A subset of B?",
        move: "Take x in A.",
      },
      typicalProblemShapes: [
        "Union, intersection, and complement identities",
        "Set equality proofs built from two subset proofs",
      ],
      miniDrill: [
        {
          prompt: "How do you prove A equals B?",
          answer: "Show A subset of B and B subset of A.",
        },
        {
          prompt: "What is the standard first move for a subset proof?",
          answer: "Pick an arbitrary element in the left set.",
        },
      ],
      memoryHook: "Set proof? Grab one element.",
      tags: ["proof", "sets", "subset"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-functions",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "One-to-one and onto functions",
      name: "Injective vs Surjective",
      order: 9,
      useItWhen: "a proof asks whether a function is one-to-one or onto",
      looksLike: "show f is injective, surjective, or bijective",
      doThis: "for injective, start with equal outputs; for onto, start with a target output",
      thinkOfItAs: "injective means no collision, surjective means no misses",
      watchOutFor: "using the wrong starting point for the wrong property",
      rememberThis: "injective starts with outputs equal; onto starts with target chosen",
      quickExample: {
        problem: "How do you start an injective proof?",
        move: "Assume f(a) = f(b).",
      },
      typicalProblemShapes: [
        "Functions between sets or number systems",
        "Proofs asking for bijection or inverse-function logic",
      ],
      miniDrill: [
        {
          prompt: "What is the first move for surjective?",
          answer: "Take an arbitrary target y in the codomain.",
        },
        {
          prompt: "What does bijective mean?",
          answer: "Injective and surjective.",
        },
      ],
      memoryHook: "No collisions, no misses.",
      tags: ["proof", "functions", "injective", "surjective"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-divisibility",
      chapter: "Chapter 4: Divisibility and the Euclidean Algorithm",
      unit: "Number Theory Basics",
      topic: "Divisibility and congruence",
      name: "Divisibility and Congruence",
      order: 10,
      useItWhen: "integers, remainders, or mod language show up",
      looksLike: "a divides b, a congruent to b mod n",
      doThis: "rewrite divisibility as multiples and congruence as same remainder class",
      thinkOfItAs: "mod means numbers land in the same bucket",
      watchOutFor: "treating congruence like ordinary equality in every context",
      rememberThis: "divides means multiple; mod means same remainder",
      quickExample: {
        problem: "What does a congruent to b mod n mean?",
        move: "n divides a minus b.",
      },
      typicalProblemShapes: [
        "Even/odd or remainder arguments",
        "Proofs that reduce expressions modulo n",
      ],
      miniDrill: [
        {
          prompt: "What does a divides b mean?",
          answer: "b = ak for some integer k.",
        },
        {
          prompt: "What does mod say two numbers share?",
          answer: "The same remainder class.",
        },
      ],
      memoryHook: "Mod = same bucket after division.",
      tags: ["proof", "number-theory", "divisibility", "congruence"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-euclidean-algorithm",
      chapter: "Chapter 4: Divisibility and the Euclidean Algorithm",
      unit: "Number Theory Basics",
      topic: "Greatest common divisors and the Euclidean Algorithm",
      name: "Euclidean Algorithm",
      order: 11,
      useItWhen: "you need a gcd quickly",
      looksLike: "gcd(a, b) with repeated division",
      doThis: "keep replacing the pair by divisor and remainder until the remainder is 0",
      thinkOfItAs: "shrinking the problem without changing the gcd",
      watchOutFor: "stopping too early before the remainder hits 0",
      rememberThis: "last nonzero remainder is the gcd",
      quickExample: {
        problem: "What is the gcd at the end of the Euclidean Algorithm?",
        move: "The last nonzero remainder.",
      },
      typicalProblemShapes: [
        "Large gcd computations",
        "Number theory proofs using repeated division",
      ],
      miniDrill: [
        {
          prompt: "What replaces the pair (a, b) in the next step?",
          answer: "The old divisor and the old remainder.",
        },
        {
          prompt: "When do you stop?",
          answer: "When the remainder becomes 0.",
        },
      ],
      memoryHook: "Keep the remainder chain going.",
      tags: ["proof", "gcd", "euclidean-algorithm"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-induction",
      chapter: "Chapter 5: Mathematical Induction and Well-ordering",
      unit: "Induction",
      topic: "Proof by induction",
      name: "Proof by Induction",
      order: 12,
      useItWhen: "a statement depends on a positive integer n",
      looksLike: "prove for all n, recursive formulas, sums, inequalities",
      doThis: "do base case, assume k case, then prove k plus 1 case",
      thinkOfItAs: "setting up dominoes and then tipping one",
      watchOutFor: "using the thing you are trying to prove without saying it is the inductive hypothesis",
      rememberThis: "base, assume, push forward",
      quickExample: {
        problem: "What are the three core pieces of induction?",
        move: "Base case, inductive hypothesis, inductive step.",
      },
      typicalProblemShapes: [
        "Sum formulas and divisibility by n",
        "Statements with n plus 1 built from n",
      ],
      miniDrill: [
        {
          prompt: "What is the purpose of the base case?",
          answer: "Start the chain.",
        },
        {
          prompt: "What happens in the inductive step?",
          answer: "Use the k case to prove the k plus 1 case.",
        },
      ],
      memoryHook: "Base, assume, next case.",
      tags: ["proof", "induction", "domino"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-strong-induction",
      chapter: "Chapter 5: Mathematical Induction and Well-ordering",
      unit: "Induction",
      topic: "Strong induction",
      name: "Strong Induction",
      order: 13,
      useItWhen: "the next step needs more than just the previous case",
      looksLike: "assume all cases up to k, prove case k plus 1",
      doThis: "assume the whole block before k plus 1, not just the single k case",
      thinkOfItAs: "using the whole ladder below you, not one rung",
      watchOutFor: "using many earlier cases while pretending you only assumed one",
      rememberThis: "strong induction assumes all earlier cases",
      quickExample: {
        problem: "When is strong induction better than ordinary induction?",
        move: "When the next case depends on several earlier cases.",
      },
      typicalProblemShapes: [
        "Recursive definitions with multiple previous terms",
        "Prime factorization or decomposition arguments",
      ],
      miniDrill: [
        {
          prompt: "What is the big difference in strong induction?",
          answer: "You assume all earlier cases up to k.",
        },
        {
          prompt: "Do strong and ordinary induction prove the same kind of universal result?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Need more history? Use strong induction.",
      tags: ["proof", "strong-induction", "recursion"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-equivalence-relations",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Equivalence relations",
      name: "Equivalence Relations",
      order: 14,
      useItWhen: "a relation ~ is supposed to mean two objects count as the same",
      looksLike: "reflexive: x~x, symmetric: x~y => y~x, transitive: x~y and y~z => x~z",
      doThis:
        "write the three mini-proofs: show x~x, assume x~y and show y~x, then assume x~y and y~z and show x~z",
      thinkOfItAs: "a legal same-team rule",
      watchOutFor:
        "proving only one or two checks, or forgetting to start with arbitrary x, y, z",
      rememberThis: "same relation = reflexive, symmetric, transitive",
      quickExample: {
        problem:
          "What proof pattern do you write for an equivalence relation?",
        move:
          "Show x~x, then x~y => y~x, then x~y and y~z => x~z.",
      },
      typicalProblemShapes: [
        "A relation like same parity, same remainder mod n, or same length",
        "A proof that starts with let x, y, z be arbitrary and then runs the three checks",
      ],
      miniDrill: [
        {
          prompt: "What does the reflexive check usually look like?",
          answer: "Start with an arbitrary x and show x~x.",
        },
        {
          prompt: "What does the transitive check usually look like?",
          answer: "Assume x~y and y~z, then prove x~z.",
        },
      ],
      memoryHook: "x~x, flip, chain.",
      tags: ["proof", "relations", "equivalence"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-countable-uncountable",
      chapter: "Chapter 8: Cardinalities of Infinite Sets",
      unit: "Relations and Cardinality",
      topic: "Countable and uncountable sets",
      name: "Countable vs Uncountable",
      order: 15,
      useItWhen: "a problem compares sizes of infinite sets",
      looksLike: "countable, uncountable, bijection to naturals, diagonal argument",
      doThis: "look for a listing if countable or a diagonal-style escape if uncountable",
      thinkOfItAs: "can you put them in a numbered list or not",
      watchOutFor: "thinking infinite automatically means uncountable",
      rememberThis: "countable means listable",
      quickExample: {
        problem: "What is the core question for countability?",
        move: "Can the set be listed in sequence like 1, 2, 3, ...?",
      },
      typicalProblemShapes: [
        "Integers, rationals, and reals comparisons",
        "Arguments using bijections or Cantor's diagonal idea",
      ],
      miniDrill: [
        {
          prompt: "Are the integers countable?",
          answer: "Yes.",
        },
        {
          prompt: "What is the classic move to show the reals are uncountable?",
          answer: "Diagonalization.",
        },
      ],
      memoryHook: "Infinite is not one-size-fits-all.",
      tags: ["proof", "countable", "uncountable", "cardinality"],
      difficulty: "Stretch",
    }),
    makeProofCard({
      id: "proof-counterexample",
      chapter: "Chapter 1: A Paradigm Shift",
      unit: "Proof Basics",
      topic: "Counterexamples",
      name: "Counterexample",
      order: 2.5,
      useItWhen: "a universal claim might be false",
      looksLike: "for all..., every..., always..., no exceptions",
      doThis: "find one case that breaks the claim",
      thinkOfItAs: "one crack that breaks the whole wall",
      watchOutFor: "giving an example that does not actually fit the claim",
      rememberThis: "one real exception kills a universal statement",
      quickExample: {
        problem: "How do you disprove 'all primes are odd'?",
        move: "Show 2 is prime and even.",
      },
      typicalProblemShapes: [
        "A bold statement about all numbers or all sets",
        "Prompts asking whether a claim is true or false",
      ],
      miniDrill: [
        {
          prompt: "How many counterexamples do you need to kill a universal claim?",
          answer: "Just one valid one.",
        },
        {
          prompt: "Can a counterexample ignore the conditions of the statement?",
          answer: "No. It has to fit the setup exactly.",
        },
      ],
      memoryHook: "One exception is enough.",
      tags: ["proof", "counterexample", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-converse-inverse",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Converse and inverse",
      name: "Converse vs Inverse",
      order: 3.5,
      useItWhen: "an if-then statement gets flipped or negated",
      looksLike: "if P then Q, if Q then P, if not P then not Q",
      doThis: "label each version before proving anything",
      thinkOfItAs: "same words, different wiring",
      watchOutFor: "mixing up converse with contrapositive",
      rememberThis: "converse flips, inverse negates, contrapositive does both",
      quickExample: {
        problem: "What is the converse of if P then Q?",
        move: "If Q then P.",
      },
      typicalProblemShapes: [
        "Logic warmups with implication statements",
        "Problems asking which form matches the original statement",
      ],
      miniDrill: [
        {
          prompt: "Which version is logically equivalent to if P then Q: converse or contrapositive?",
          answer: "Contrapositive.",
        },
        {
          prompt: "What is the inverse of if P then Q?",
          answer: "If not P then not Q.",
        },
      ],
      memoryHook: "Name the version before you prove it.",
      tags: ["proof", "logic", "converse", "inverse"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-biconditional",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Biconditional proofs",
      name: "If and Only If",
      order: 5.5,
      useItWhen: "a statement says if and only if",
      looksLike: "P iff Q, necessary and sufficient",
      doThis: "prove both directions separately",
      thinkOfItAs: "two doors, both must open",
      watchOutFor: "proving only one direction and stopping",
      rememberThis: "iff means two proofs",
      quickExample: {
        problem: "How do you prove P iff Q?",
        move: "Show P implies Q and Q implies P.",
      },
      typicalProblemShapes: [
        "Necessary and sufficient condition questions",
        "Statements written as iff or equivalence claims",
      ],
      miniDrill: [
        {
          prompt: "Can one direction prove an iff statement?",
          answer: "No. You need both.",
        },
        {
          prompt: "What are the two directions called?",
          answer: "Forward and backward, or each implication separately.",
        },
      ],
      memoryHook: "Iff = both ways.",
      tags: ["proof", "biconditional", "logic"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-set-operations",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "Union, intersection, and complement identities",
      name: "Set Operation Proofs",
      order: 8.5,
      useItWhen: "a problem claims two set expressions are equal",
      looksLike: "union, intersection, complement, set difference",
      doThis: "chase one element through the definitions on both sides",
      thinkOfItAs: "membership truth tables without the table",
      watchOutFor: "moving symbols around without checking membership meaning",
      rememberThis: "set identities are element chases",
      quickExample: {
        problem: "How do you prove A intersect (B union C) equals something?",
        move: "Take x in one side and unpack what that means.",
      },
      typicalProblemShapes: [
        "Distributive, De Morgan, or subset identities",
        "Set equalities with complements and intersections",
      ],
      miniDrill: [
        {
          prompt: "What is the standard first move in a set identity proof?",
          answer: "Pick an arbitrary element.",
        },
        {
          prompt: "Do you prove set equality in one direction or two?",
          answer: "Usually two subset directions.",
        },
      ],
      memoryHook: "Follow one element, not the symbols.",
      tags: ["proof", "sets", "union", "intersection"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-composition-inverse",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "Function composition and inverse functions",
      name: "Composition and Inverse",
      order: 9.5,
      useItWhen: "functions are stacked or you need to undo one",
      looksLike: "f composed with g, f inverse, one-to-one and onto",
      doThis: "track the input carefully and check the order",
      thinkOfItAs: "machines in a chain and the undo machine",
      watchOutFor: "reversing composition order by accident",
      rememberThis: "composition order matters",
      quickExample: {
        problem: "What is f composed with g of x?",
        move: "Do g first, then f.",
      },
      typicalProblemShapes: [
        "Compute f(g(x)) or g(f(x))",
        "Show a function has an inverse or use one",
      ],
      miniDrill: [
        {
          prompt: "In f composed with g, which function acts first?",
          answer: "g acts first.",
        },
        {
          prompt: "What property does a function need for an inverse to exist nicely?",
          answer: "It needs to be bijective.",
        },
      ],
      memoryHook: "Inside function goes first.",
      tags: ["proof", "functions", "composition", "inverse"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-division-algorithm",
      chapter: "Chapter 4: Divisibility and the Euclidean Algorithm",
      unit: "Number Theory Basics",
      topic: "Division Algorithm",
      name: "Division Algorithm",
      order: 10.5,
      useItWhen: "integers are broken into quotient and remainder",
      looksLike: "a = bq + r with 0 less than or equal to r less than b",
      doThis: "write the number in quotient-plus-remainder form",
      thinkOfItAs: "clean remainder packaging",
      watchOutFor: "forgetting the remainder bounds",
      rememberThis: "quotient plus remainder, with remainder small",
      quickExample: {
        problem: "What is the division algorithm form?",
        move: "a = bq + r with the remainder bounded.",
      },
      typicalProblemShapes: [
        "Proofs with parity or cases modulo n",
        "Gcd and remainder arguments",
      ],
      miniDrill: [
        {
          prompt: "What must be true about r in a = bq + r?",
          answer: "It has to stay between 0 and b minus 1.",
        },
        {
          prompt: "What does the division algorithm help you isolate?",
          answer: "The remainder class.",
        },
      ],
      memoryHook: "Every integer is quotient plus small remainder.",
      tags: ["proof", "division-algorithm", "number-theory"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-bezout",
      chapter: "Chapter 4: Divisibility and the Euclidean Algorithm",
      unit: "Number Theory Basics",
      topic: "Bezout identity",
      name: "Bezout Identity",
      order: 11.5,
      useItWhen: "gcd and linear combinations show up together",
      looksLike: "gcd(a, b) = ax + by",
      doThis: "run the Euclidean Algorithm backward to build the combination",
      thinkOfItAs: "unwinding the remainder chain",
      watchOutFor: "finding the gcd but never writing it as ax plus by",
      rememberThis: "the gcd can be built from a and b",
      quickExample: {
        problem: "How do you get ax + by from the Euclidean Algorithm?",
        move: "Back-substitute through the remainder steps.",
      },
      typicalProblemShapes: [
        "Show gcd(a, b) is a linear combination",
        "Solve number theory problems using gcd structure",
      ],
      miniDrill: [
        {
          prompt: "What identity links gcd to a linear combination?",
          answer: "Bezout's identity.",
        },
        {
          prompt: "What direction do you work after finding the gcd?",
          answer: "Backward through the steps.",
        },
      ],
      memoryHook: "Find gcd, then unwind.",
      tags: ["proof", "bezout", "gcd", "number-theory"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-well-ordering",
      chapter: "Chapter 5: Mathematical Induction and Well-ordering",
      unit: "Induction",
      topic: "Well-ordering principle",
      name: "Well-Ordering",
      order: 13.5,
      useItWhen: "a proof wants the smallest bad example",
      looksLike: "assume a nonempty set of counterexamples and choose the least one",
      doThis: "take the smallest counterexample and force a contradiction",
      thinkOfItAs: "hunt the first failure",
      watchOutFor: "using well-ordering without clearly defining the bad set",
      rememberThis: "pick the smallest bad case",
      quickExample: {
        problem: "What is the key move in a well-ordering proof?",
        move: "Assume bad cases exist and pick the smallest one.",
      },
      typicalProblemShapes: [
        "Minimal counterexample arguments",
        "Proofs tied to induction or positive integers",
      ],
      miniDrill: [
        {
          prompt: "What must the bad-case set be before you use well-ordering?",
          answer: "Nonempty and made of positive integers or naturals.",
        },
        {
          prompt: "Why choose the smallest bad case?",
          answer: "Because smaller cases then become usable against it.",
        },
      ],
      memoryHook: "Smallest bad case first.",
      tags: ["proof", "well-ordering", "induction"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-equivalence-classes",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Equivalence classes",
      name: "Equivalence Classes",
      order: 14.5,
      useItWhen: "an equivalence relation groups objects into same-type buckets",
      looksLike: "[a], congruence classes, same relation buckets",
      doThis: "fix one element and collect everything equivalent to it",
      thinkOfItAs: "one bucket of things counted as the same",
      watchOutFor: "treating a class like a single element instead of a whole set",
      rememberThis: "a class is the bucket around one element",
      quickExample: {
        problem: "What is [a] under an equivalence relation?",
        move: "The set of everything equivalent to a.",
      },
      typicalProblemShapes: [
        "Congruence mod n classes",
        "Relations that split a set into buckets",
      ],
      miniDrill: [
        {
          prompt: "Can two equivalence classes overlap partly?",
          answer: "No. They are either the same or disjoint.",
        },
        {
          prompt: "What builds an equivalence class?",
          answer: "One chosen element and the relation.",
        },
      ],
      memoryHook: "Pick one element, get its bucket.",
      tags: ["proof", "equivalence-class", "relations"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-partitions",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Partitions",
      name: "Partitions",
      order: 14.6,
      useItWhen: "a set is split into non-overlapping pieces",
      looksLike: "blocks, classes, pieces that cover the whole set",
      doThis: "check cover-all, nonempty, and no overlap between different blocks",
      thinkOfItAs: "cutting the set into clean pieces",
      watchOutFor: "allowing blocks to overlap or leave gaps",
      rememberThis: "partitions cover everything with no overlap",
      quickExample: {
        problem: "What are the two big partition rules?",
        move: "Cover the whole set and keep different blocks disjoint.",
      },
      typicalProblemShapes: [
        "Questions linking partitions and equivalence relations",
        "Families of subsets proposed as a partition",
      ],
      miniDrill: [
        {
          prompt: "Can a partition block be empty?",
          answer: "No.",
        },
        {
          prompt: "What happens if two blocks overlap?",
          answer: "Then it is not a partition unless they are really the same block.",
        },
      ],
      memoryHook: "Cover all, overlap none.",
      tags: ["proof", "partitions", "relations"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-bijections-countability",
      chapter: "Chapter 8: Cardinalities of Infinite Sets",
      unit: "Relations and Cardinality",
      topic: "Bijections and countability",
      name: "Bijections for Countability",
      order: 15.5,
      useItWhen: "you want to prove two infinite sets have the same size",
      looksLike: "find a bijection, list the set, pair the set with naturals",
      doThis: "build a one-to-one onto match or an explicit listing",
      thinkOfItAs: "same size means same pairing power",
      watchOutFor: "showing only injective or only surjective when you need a full match",
      rememberThis: "countable means matchable with naturals",
      quickExample: {
        problem: "How do you show a set is countable?",
        move: "List it or build a bijection with the natural numbers.",
      },
      typicalProblemShapes: [
        "Integers, evens, rationals, or other countability comparisons",
        "Questions asking for an explicit listing",
      ],
      miniDrill: [
        {
          prompt: "What kind of function proves two sets have the same cardinality?",
          answer: "A bijection.",
        },
        {
          prompt: "What set is the usual target for countability?",
          answer: "The natural numbers.",
        },
      ],
      memoryHook: "Countable means pair it with 1, 2, 3, ...",
      tags: ["proof", "bijection", "countable", "cardinality"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-diagonal-argument",
      chapter: "Chapter 8: Cardinalities of Infinite Sets",
      unit: "Relations and Cardinality",
      topic: "Cantor diagonal argument",
      name: "Diagonal Argument",
      order: 15.6,
      useItWhen: "a set is claimed to be listable but probably is not",
      looksLike: "suppose all reals are listed, then build a new one off the diagonal",
      doThis: "change the diagonal entries to make a missing object",
      thinkOfItAs: "escape every list by changing one spot in each row",
      watchOutFor: "building a new object that accidentally matches one listed entry",
      rememberThis: "diagonal change makes an escape item",
      quickExample: {
        problem: "What is the diagonal move for showing reals are uncountable?",
        move: "Create a new decimal that differs in the nth digit from the nth listed number.",
      },
      typicalProblemShapes: [
        "Reals, binary strings, or all subsets claims",
        "Proofs that no complete list can exist",
      ],
      miniDrill: [
        {
          prompt: "Why does the diagonal object avoid the whole list?",
          answer: "Because it differs from every listed item in at least one forced spot.",
        },
        {
          prompt: "What is the main contradiction in diagonalization?",
          answer: "The supposed full list missed the new object.",
        },
      ],
      memoryHook: "Change the diagonal, escape the list.",
      tags: ["proof", "diagonal", "uncountable", "cardinality"],
      difficulty: "Stretch",
    }),
    makeProofCard({
      id: "proof-cases",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Proof by cases",
      name: "Proof by Cases",
      order: 5.2,
      useItWhen: "the problem naturally splits into a few separate situations",
      looksLike: "even or odd, positive or negative, one case or the other",
      doThis: "cover every case and prove the claim in each one",
      thinkOfItAs: "several short proofs instead of one tangled proof",
      watchOutFor: "missing a case or letting two cases overlap badly",
      rememberThis: "split clean, finish all cases",
      quickExample: {
        problem: "How do you prove an integer statement that depends on even or odd?",
        move: "Do one even case and one odd case.",
      },
      typicalProblemShapes: [
        "Parity proofs",
        "Absolute value or sign-based arguments",
      ],
      miniDrill: [
        {
          prompt: "Can proof by cases skip one possibility?",
          answer: "No. Every real case has to be covered.",
        },
        {
          prompt: "When is proof by cases usually a good move?",
          answer: "When the setup already breaks into natural categories.",
        },
      ],
      memoryHook: "If the problem splits, let the proof split.",
      tags: ["proof", "cases", "logic"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-existence-uniqueness",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Existence and uniqueness",
      name: "Existence vs Uniqueness",
      order: 7.2,
      useItWhen: "a statement says there exists exactly one object",
      looksLike: "there exists a unique..., one and only one...",
      doThis: "prove existence first, then prove no second object can also work",
      thinkOfItAs: "build it, then show it is the only one",
      watchOutFor: "showing existence and forgetting uniqueness",
      rememberThis: "unique means existence plus only one",
      quickExample: {
        problem: "What are the two jobs in an existence-and-uniqueness proof?",
        move: "Show at least one exists, then show two such objects must be the same.",
      },
      typicalProblemShapes: [
        "Exactly one solution claims",
        "Definitions involving a unique object",
      ],
      miniDrill: [
        {
          prompt: "Does uniqueness alone prove something exists?",
          answer: "No.",
        },
        {
          prompt: "What extra step appears in uniqueness proofs?",
          answer: "Assume two objects work and prove they are equal.",
        },
      ],
      memoryHook: "Existence gets one. Uniqueness kills extras.",
      tags: ["proof", "existence", "uniqueness"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-power-set-cartesian",
      chapter: "Chapter 6: Set Theory, Part II",
      unit: "Set Theory II",
      topic: "Power sets and Cartesian products",
      name: "Power Set and Cartesian Product",
      order: 13.2,
      useItWhen: "the problem builds new sets from subsets or ordered pairs",
      looksLike: "P(A), A cross B, ordered pairs",
      doThis: "track whether the object is a subset or a pair",
      thinkOfItAs: "power set means all groups, Cartesian means all pairings",
      watchOutFor: "mixing up elements of A with subsets of A",
      rememberThis: "power set makes subsets, cross product makes pairs",
      quickExample: {
        problem: "What lives inside P(A)?",
        move: "Subsets of A, not ordinary elements of A.",
      },
      typicalProblemShapes: [
        "Count or compare power sets",
        "Build functions or relations on Cartesian products",
      ],
      miniDrill: [
        {
          prompt: "Is an element of the power set a single number or a subset?",
          answer: "A subset.",
        },
        {
          prompt: "What does A cross B contain?",
          answer: "Ordered pairs with first part from A and second part from B.",
        },
      ],
      memoryHook: "Power set = subsets. Cross product = pairs.",
      tags: ["proof", "sets", "power-set", "cartesian-product"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-images-preimages",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "Images and preimages",
      name: "Image vs Preimage",
      order: 9.2,
      useItWhen: "a function is acting on sets, not just single inputs",
      looksLike: "f(S), f inverse of T, image, preimage",
      doThis: "track which side of the function the set starts on",
      thinkOfItAs: "image goes forward, preimage pulls back",
      watchOutFor: "treating preimage like an inverse function when none exists",
      rememberThis: "image forward, preimage backward",
      quickExample: {
        problem: "What is the preimage of a set T?",
        move: "All inputs whose outputs land in T.",
      },
      typicalProblemShapes: [
        "Set identities involving functions",
        "Questions comparing f(A union B) and preimages of unions",
      ],
      miniDrill: [
        {
          prompt: "Does preimage need the function to be invertible?",
          answer: "No.",
        },
        {
          prompt: "Which way does image move?",
          answer: "From inputs forward to outputs.",
        },
      ],
      memoryHook: "Image pushes. Preimage pulls back.",
      tags: ["proof", "functions", "image", "preimage"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-relation-properties",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Basic relation properties",
      name: "Relation Properties",
      order: 14.1,
      useItWhen: "a relation needs to be tested before calling it special",
      looksLike: "reflexive, symmetric, antisymmetric, transitive",
      doThis: "test each property with its exact definition",
      thinkOfItAs: "a checklist before naming the relation",
      watchOutFor: "confusing symmetric with antisymmetric",
      rememberThis: "name the property only after the exact test",
      quickExample: {
        problem: "What is the fastest way to test a relation?",
        move: "Go property by property with the definitions in front of you.",
      },
      typicalProblemShapes: [
        "Relations on numbers or sets",
        "Warmups before equivalence relations or partial orders",
      ],
      miniDrill: [
        {
          prompt: "Does antisymmetric mean the same as not symmetric?",
          answer: "No.",
        },
        {
          prompt: "What is the safest move when testing relation properties?",
          answer: "Use the exact definition each time.",
        },
      ],
      memoryHook: "Relation names come after the checklist.",
      tags: ["proof", "relations", "reflexive", "antisymmetric"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-partial-orders",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Partial orders",
      name: "Partial Orders",
      order: 14.2,
      useItWhen: "a relation behaves like a comparison but not every pair is comparable",
      looksLike: "reflexive, antisymmetric, transitive",
      doThis: "check the three order properties, then ask whether all pairs can be compared",
      thinkOfItAs: "an ordering with some ties or incomparable pairs",
      watchOutFor: "thinking partial order means every pair must compare",
      rememberThis: "partial order is not total order",
      quickExample: {
        problem: "What is the extra question after proving a partial order?",
        move: "Ask whether every pair is comparable.",
      },
      typicalProblemShapes: [
        "Divisibility relations",
        "Subset relations on power sets",
      ],
      miniDrill: [
        {
          prompt: "What three properties define a partial order?",
          answer: "Reflexive, antisymmetric, transitive.",
        },
        {
          prompt: "Can a partial order leave some pairs incomparable?",
          answer: "Yes.",
        },
      ],
      memoryHook: "Partial order lets some pairs stay unmatched.",
      tags: ["proof", "partial-order", "relations"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-total-orders",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Total orders",
      name: "Total Orders",
      order: 14.25,
      useItWhen: "a partial order also compares every pair",
      looksLike: "ordered sets, comparability, every pair",
      doThis: "start from partial order, then check full comparability",
      thinkOfItAs: "a lineup where every two items can be compared",
      watchOutFor: "calling a relation total just because it has order properties",
      rememberThis: "total order = partial order plus comparability",
      quickExample: {
        problem: "What turns a partial order into a total order?",
        move: "Every pair has to be comparable.",
      },
      typicalProblemShapes: [
        "Standard less-than style relations",
        "Compare partial and total order examples",
      ],
      miniDrill: [
        {
          prompt: "What extra property does a total order need?",
          answer: "Comparability of every pair.",
        },
        {
          prompt: "Is subset on a power set usually total?",
          answer: "No.",
        },
      ],
      memoryHook: "Total means everyone can be compared.",
      tags: ["proof", "total-order", "relations"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-rationals-countable",
      chapter: "Chapter 8: Cardinalities of Infinite Sets",
      unit: "Relations and Cardinality",
      topic: "Why the rationals are countable",
      name: "Rationals Are Countable",
      order: 15.55,
      useItWhen: "students confuse infinite with too big to list",
      looksLike: "fractions, grid listing, diagonals through rationals",
      doThis: "build a listing strategy and skip duplicates carefully",
      thinkOfItAs: "walking through the fraction grid in a smart order",
      watchOutFor: "listing the same rational many times and calling it done",
      rememberThis: "infinite can still be listable",
      quickExample: {
        problem: "Why are rationals countable but reals are not?",
        move: "Rationals can be listed; diagonalization breaks lists of reals.",
      },
      typicalProblemShapes: [
        "Compare naturals, integers, rationals, and reals",
        "Questions about explicit listing methods",
      ],
      miniDrill: [
        {
          prompt: "What is the hard part of listing rationals?",
          answer: "Avoiding repeats like 1/2 and 2/4.",
        },
        {
          prompt: "Does countable mean finite?",
          answer: "No.",
        },
      ],
      memoryHook: "Countable just means listable.",
      tags: ["proof", "rationals", "countable", "cardinality"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-planning-writing",
      chapter: "Chapter 1: A Paradigm Shift",
      unit: "Proof Basics",
      topic: "Planning and writing a proof",
      name: "Plan the Proof First",
      order: 2.6,
      useItWhen: "you know the claim but do not know how to start",
      looksLike: "prove that..., blank page, too many ideas at once",
      doThis: "rewrite the claim, unpack definitions, test small cases, then sketch before writing",
      thinkOfItAs: "rough draft first, clean proof second",
      watchOutFor: "trying to write the polished proof before you know the move",
      rememberThis: "messy scratch first, clean story later",
      quickExample: {
        problem: "What do you do before writing formal sentences?",
        move: "Interpret the claim and sketch the route.",
      },
      typicalProblemShapes: [
        "A theorem feels true but the first line is unclear",
        "You know definitions but not the proof structure",
      ],
      miniDrill: [
        {
          prompt: "Should your first attempt usually be the final proof?",
          answer: "No. Sketch first.",
        },
        {
          prompt: "What should you unpack early in almost every proof?",
          answer: "The definitions.",
        },
      ],
      memoryHook: "Interpret, sketch, then write.",
      tags: ["proof", "writing", "strategy"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-propositions",
      chapter: "Chapter 2: Logic and the Language of Proofs",
      unit: "Logic and Quantifiers",
      topic: "Propositions and logical connectives",
      name: "Propositions and Connectives",
      order: 5.6,
      useItWhen: "a statement is built from and, or, not, or if-then",
      looksLike: "P and Q, P or Q, not P, if P then Q",
      doThis: "break the sentence into smaller statements and track the connector",
      thinkOfItAs: "grammar for math statements",
      watchOutFor: "reading 'or' like everyday speech when math usually means inclusive or",
      rememberThis: "the connector changes the whole claim",
      quickExample: {
        problem: "What does 'P or Q' usually mean in math?",
        move: "At least one is true, maybe both.",
      },
      typicalProblemShapes: [
        "Compound statements built from smaller claims",
        "Truth-value checks and rewrites",
      ],
      miniDrill: [
        {
          prompt: "Can 'P or Q' be true when both are true?",
          answer: "Yes.",
        },
        {
          prompt: "What should you isolate first in a long logic sentence?",
          answer: "The main connector.",
        },
      ],
      memoryHook: "Find the connector before the proof.",
      tags: ["proof", "logic", "propositions"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-set-notation",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "Set notation and describing a set",
      name: "Set Notation",
      order: 8.05,
      useItWhen: "a problem is written with braces, membership, or set-builder notation",
      looksLike: "{x in Z : ...}, element of, subset of, empty set",
      doThis: "translate the notation into plain English before proving anything",
      thinkOfItAs: "reading the set out loud",
      watchOutFor: "mixing up element of with subset of",
      rememberThis: "first read the set in words",
      quickExample: {
        problem: "What does {x in Z : x is even} mean?",
        move: "The set of all even integers.",
      },
      typicalProblemShapes: [
        "Set-builder notation that needs translation",
        "Membership or subset statements",
      ],
      miniDrill: [
        {
          prompt: "Does x in A mean x is a set?",
          answer: "Not necessarily. It means x is an element of A.",
        },
        {
          prompt: "What is the fast move for scary set notation?",
          answer: "Rewrite it in plain English.",
        },
      ],
      memoryHook: "Read the braces in plain English.",
      tags: ["proof", "sets", "notation"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-union-intersection-complement",
      chapter: "Chapter 3: Sets and Functions",
      unit: "Sets and Functions",
      topic: "Unions, intersections, and complements",
      name: "Union, Intersection, Complement",
      order: 8.6,
      useItWhen: "a set proof uses union, intersection, or complement symbols",
      looksLike: "A union B, A intersection B, A complement",
      doThis: "translate each symbol into an element test and prove membership both ways if needed",
      thinkOfItAs: "union means or, intersection means and, complement means not",
      watchOutFor: "waving at the symbols instead of proving element membership",
      rememberThis: "set proofs often become membership proofs",
      quickExample: {
        problem: "How do you prove A subset of B union C?",
        move: "Take x in A and show x lands in B or C.",
      },
      typicalProblemShapes: [
        "Set identities with union and intersection",
        "Prove two sets are equal",
      ],
      miniDrill: [
        {
          prompt: "What does x in A intersection B mean?",
          answer: "x is in both A and B.",
        },
        {
          prompt: "How do you usually prove two sets are equal?",
          answer: "Show each is a subset of the other.",
        },
      ],
      memoryHook: "Union or, intersection and, complement not.",
      tags: ["proof", "sets", "union", "intersection", "complement"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-recursive-processes",
      chapter: "Chapter 5: Mathematical Induction and Well-ordering",
      unit: "Induction",
      topic: "Recursive processes",
      name: "Recursive Process",
      order: 11.4,
      useItWhen: "a sequence or object is built from earlier steps",
      looksLike: "a_n depends on a_(n-1), recurrence, next term from old terms",
      doThis: "identify the base case and the update rule before using induction",
      thinkOfItAs: "today depends on yesterday",
      watchOutFor: "jumping into induction without knowing the recursion clearly",
      rememberThis: "base case plus update rule",
      quickExample: {
        problem: "What two things does a recursive definition need first?",
        move: "A starting value and a rule for the next step.",
      },
      typicalProblemShapes: [
        "Sequences defined from previous terms",
        "Tilings, steps, or counting built stage by stage",
      ],
      miniDrill: [
        {
          prompt: "What is missing if you only know a_n = a_(n-1) + 2?",
          answer: "A starting value.",
        },
        {
          prompt: "What proof method often matches recursion?",
          answer: "Induction.",
        },
      ],
      memoryHook: "Start value, then repeat rule.",
      tags: ["proof", "recursion", "induction"],
      difficulty: "Starter",
    }),
    makeProofCard({
      id: "proof-indexed-collections",
      chapter: "Chapter 6: Set Theory, Part II",
      unit: "Set Theory II",
      topic: "Indexed collections of sets",
      name: "Indexed Collections",
      order: 13.3,
      useItWhen: "the problem has A_i, unions over i, or intersections over many sets",
      looksLike: "A_i, union from i = 1 to n, intersection over all n",
      doThis: "treat the index like a label and translate the big union or intersection into words",
      thinkOfItAs: "a family of sets with name tags",
      watchOutFor: "forgetting whether the statement needs one index or all indices",
      rememberThis: "big union means some index, big intersection means every index",
      quickExample: {
        problem: "What does x in union A_i mean?",
        move: "x is in at least one set in the family.",
      },
      typicalProblemShapes: [
        "Statements about many sets at once",
        "Nested unions and intersections",
      ],
      miniDrill: [
        {
          prompt: "Does x in intersection A_i mean one set or every set?",
          answer: "Every set.",
        },
        {
          prompt: "What does the index i do here?",
          answer: "It labels which set you mean.",
        },
      ],
      memoryHook: "Union = some. Intersection = all.",
      tags: ["proof", "sets", "indexed-sets"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-well-defined",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Well-defined functions and operations",
      name: "Well-Defined",
      order: 14.6,
      useItWhen: "an object has many representatives and you need the output not to depend on the choice",
      looksLike: "[a] goes to ..., fractions, equivalence classes, mod classes",
      doThis: "pick two equivalent representatives and show they give the same output",
      thinkOfItAs: "different names, same result",
      watchOutFor: "checking only one representative and calling it done",
      rememberThis: "new rule must ignore the representative choice",
      quickExample: {
        problem: "What is the key test for a map on equivalence classes?",
        move: "Show equivalent inputs give the same output.",
      },
      typicalProblemShapes: [
        "Functions on quotient sets or congruence classes",
        "Operations defined using representatives",
      ],
      miniDrill: [
        {
          prompt: "What breaks a well-defined rule?",
          answer: "Two equivalent inputs give different outputs.",
        },
        {
          prompt: "Do you test one representative or two equivalent ones?",
          answer: "Two equivalent ones.",
        },
      ],
      memoryHook: "Same class, same output.",
      tags: ["proof", "well-defined", "equivalence"],
      difficulty: "Stretch",
    }),
    makeProofCard({
      id: "proof-congruence-classes",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Congruence classes mod n",
      name: "Congruence Classes",
      order: 14.7,
      useItWhen: "numbers are grouped by the same remainder mod n",
      looksLike: "[a] mod n, same remainder, clocks, residue classes",
      doThis: "translate the class into all numbers with that remainder and use remainder arithmetic",
      thinkOfItAs: "numbers living on the same clock position",
      watchOutFor: "mixing up one number with its whole class",
      rememberThis: "same remainder means same class",
      quickExample: {
        problem: "What numbers live in [2] mod 5?",
        move: "All integers that leave remainder 2 when divided by 5.",
      },
      typicalProblemShapes: [
        "Arithmetic mod n",
        "Equivalence relation examples from remainders",
      ],
      miniDrill: [
        {
          prompt: "Are 7 and 12 in the same class mod 5?",
          answer: "Yes. Both leave remainder 2.",
        },
        {
          prompt: "Does a congruence class mean one number or many?",
          answer: "Many.",
        },
      ],
      memoryHook: "Same remainder, same bucket.",
      tags: ["proof", "congruence", "mod", "equivalence"],
      difficulty: "Standard",
    }),
    makeProofCard({
      id: "proof-functions-partitions",
      chapter: "Chapter 7: Relations and Partitions",
      unit: "Relations and Cardinality",
      topic: "Functions and partitions",
      name: "Functions and Partitions",
      order: 14.8,
      useItWhen: "a function splits a set into fibers or preimage pieces",
      looksLike: "same output, preimage of y, domain split into groups",
      doThis: "group inputs by output and treat each group as one block",
      thinkOfItAs: "sorting inputs into output buckets",
      watchOutFor: "forgetting that different outputs give disjoint buckets",
      rememberThis: "a function partitions the domain into fibers",
      quickExample: {
        problem: "What is a fiber of a function?",
        move: "All inputs that land on the same output.",
      },
      typicalProblemShapes: [
        "Preimage sets of a function",
        "Partition built from equal outputs",
      ],
      miniDrill: [
        {
          prompt: "Can one input lie in two different fibers?",
          answer: "No.",
        },
        {
          prompt: "What decides the bucket of an input?",
          answer: "Its output value.",
        },
      ],
      memoryHook: "Same output, same bucket.",
      tags: ["proof", "functions", "partitions", "fibers"],
      difficulty: "Standard",
    }),
  ],
};
